{
  "hash": "0f0b622758b32c1ccee37a4a56c1e05b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linearna regresija\"\nsubtitle: \"Predviđanje i objašnjavanje s modelima\"\ndate: 2025-05-24\ncategories: [regresija, korelacija, R-kvadrat, dijagnostika, višestruka regresija]\ndraft: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n::: {.callout-note}\n## Ishodi učenja\n\nNakon ovog predavanja moći ćete:\n\n1. Objasniti razliku između korelacije i regresije.\n2. Provesti jednostavnu linearnu regresiju u R-u i interpretirati koeficijente.\n3. Interpretirati R-kvadrat kao mjeru kvalitete modela.\n4. Provjeriti pretpostavke linearne regresije dijagnostičkim grafovima.\n5. Provesti višestruku regresiju s više prediktora i interpretirati parcijalne koeficijente.\n6. Usporediti modele pomoću R-kvadrata, prilagođenog R-kvadrata i AIC-a.\n7. Prepoznati uobičajene probleme (multikolinearnost, utjecajne točke, nelinearnost).\n8. Napisati kompletni izvještaj regresijske analize.\n:::\n\n## Što pokreće angažman?\n\nZamislite sljedeću situaciju. Radite kao analitičarka društvenih mreža za srednje veliku medijsku kuću. Vaša šefica dolazi s pitanjem koje zvuči jednostavno: \"Koji faktori utječu na angažman naših Instagram objava?\" Želi znati je li stvar u duljini teksta, broju hashtagova, tipu sadržaja, pozivu na akciju, ili u nečem sasvim drugom. I još važnije, želi konkretne preporuke: što da radimo više, a što manje?\n\nDo sada ste u kolegiju naučili uspoređivati grupe. Hi-kvadrat test govori vam postoji li veza između kategoričkih varijabli. T-test uspoređuje prosjeke dviju grupa. ANOVA uspoređuje više grupa odjednom. Ali nijedno od toga ne odgovara na pitanje vaše šefice. Ona ne pita \"razlikuju li se grupe.\" Ona pita: koliko svaki faktor doprinosi angažmanu, u kojem smjeru, i koliko dobro možemo predvidjeti angažman na temelju tih faktora?\n\nZa to nam treba regresija. Regresija je, u najjednostavnijem smislu, alat koji modelira odnos između jedne ili više nezavisnih varijabli (koje zovemo prediktorima) i jedne zavisne varijable (koju zovemo ishodom). Umjesto da samo kaže \"postoji razlika\", regresija kvantificira: za svaki dodatni hashtag, angažman se mijenja za toliko i toliko. To je razlika između \"hashtagovi su važni\" i \"svaki dodatni hashtag smanjuje angažman za 0.15 postotnih bodova, kontrolirajući za ostale faktore.\"\n\nRadimo s datasetom od 500 Instagram objava jednog poslovnog profila. Svaka objava ima zabilježen engagement rate (postotak pratitelja koji su reagirali), duljinu teksta, broj hashtagova, broj oznaka drugih profila, tip sadržaja (slika, video, carousel, reel), temu i informaciju o tome je li uključen poziv na akciju (CTA).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposts <- read_csv(\"../resources/datasets/social_engagement.csv\")\nglimpse(posts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 400\nColumns: 14\n$ post_id         <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,~\n$ day             <chr> \"utorak\", \"ponedjeljak\", \"petak\", \"nedjelja\", \"subota\"~\n$ time_slot       <chr> \"18-21\", \"09-12\", \"21-24\", \"12-15\", \"15-18\", \"18-21\", ~\n$ content_type    <chr> \"foto\", \"tekst\", \"carousel\", \"foto\", \"carousel\", \"reel~\n$ topic           <chr> \"iza_kulisa\", \"proizvod\", \"zabava\", \"zabava\", \"proizvo~\n$ text_length     <dbl> 290, 34, 35, 162, 240, 189, 300, 228, 242, 97, 136, 17~\n$ num_hashtags    <dbl> 0, 17, 19, 14, 20, 9, 25, 21, 6, 12, 0, 23, 27, 27, 20~\n$ has_cta         <dbl> 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, ~\n$ num_mentions    <dbl> 3, 1, 1, 4, 0, 4, 4, 1, 1, 1, 2, 4, 1, 4, 4, 4, 3, 0, ~\n$ followers       <dbl> 15095, 15312, 14749, 14728, 15336, 14722, 15168, 14805~\n$ engagement_rate <dbl> 4.93, 2.26, 7.32, 5.58, 4.03, 6.58, 3.51, 6.74, 2.03, ~\n$ likes           <dbl> 594, 284, 860, 583, 500, 692, 447, 816, 212, 548, 476,~\n$ comments        <dbl> 120, 76, 174, 81, 93, 138, 88, 195, 45, 150, 87, 33, 4~\n$ shares          <dbl> 78, 32, 115, 91, 70, 124, 41, 59, 45, 92, 80, 34, 25, ~\n```\n\n\n:::\n:::\n\n\n## Od korelacije do regresije {#sec-korelacija}\n\nKrenimo od poznatog terena. Korelaciju već znate: ona mjeri jačinu i smjer linearne veze između dviju varijabli. Pearsonov r kreće se od -1 (savršena negativna veza) preko 0 (nema linearne veze) do +1 (savršena pozitivna veza).\n\nRegresija ide korak dalje. Dok korelacija samo kaže \"ove dvije varijable su povezane\", regresija definira jednadžbu pravca koja opisuje tu vezu. Ta jednadžba vam omogućuje nešto što korelacija ne može: predviđanje. Ako znate koliko hashtagova ima objava, regresija vam daje konkretnu procjenu koliki će biti njezin angažman.\n\nPrije nego što uđemo u regresiju, pogledajmo korelacije između naših numeričkih varijabli.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Korelacije numeričkih prediktora s engagement_rate\nposts |>\n  select(engagement_rate, text_length, num_hashtags, num_mentions, followers) |>\n  cor() |>\n  round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                engagement_rate text_length num_hashtags num_mentions followers\nengagement_rate           1.000       0.040       -0.411       -0.016    -0.132\ntext_length               0.040       1.000        0.008        0.061    -0.025\nnum_hashtags             -0.411       0.008        1.000        0.031     0.062\nnum_mentions             -0.016       0.061        0.031        1.000     0.092\nfollowers                -0.132      -0.025        0.062        0.092     1.000\n```\n\n\n:::\n:::\n\n\nPogledajte stupac `engagement_rate`. Broj hashtagova ima negativnu korelaciju s angažmanom (r ≈ -0.41), što znači da objave s više hashtagova u prosjeku imaju niži engagement rate. Vizualizirajmo tu vezu.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposts |>\n  ggplot(aes(x = num_hashtags, y = engagement_rate)) +\n  geom_point(alpha = 0.3, color = \"steelblue\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"firebrick\") +\n  labs(\n    title = \"Broj hashtagova i engagement rate\",\n    subtitle = paste0(\"r = \", round(cor(posts$num_hashtags, posts$engagement_rate), 3)),\n    x = \"Broj hashtagova\",\n    y = \"Engagement rate (%)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/scatter-hashtags-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nCrvena linija je regresijski pravac: ona predstavlja \"najbolju\" ravnu liniju koja prolazi kroz oblak točaka. Sivi pojas oko nje pokazuje nesigurnost te procjene (95% interval pouzdanosti za pravac).\n\nJedna stvar vas možda brine. Negativna korelacija sugerira da više hashtagova znači niži angažman. Ali budite oprezni s takvim zaključcima. Možda veza uopće nije linearna: možda postoji optimalan broj hashtagova, a i premalo i previše je loše. Možda profili s više hashtagova imaju i druge karakteristike koje snižavaju angažman. To su pitanja koja ćemo istražiti kasnije u ovom predavanju.\n\n## Jednostavna linearna regresija {#sec-jednostavna}\n\nPočnimo s najjednostavnijim mogućim modelom: jednim prediktorom i jednim ishodom. To je jednostavna linearna regresija.\n\nIdeja je intuitivna. Vi imate oblak točaka na scatterplotu i želite provući ravnu liniju kroz taj oblak tako da ona što bolje opisuje opći trend. \"Što bolje\" u praksi znači: tako da ukupna udaljenost svih točaka od linije bude što manja.\n\nMatematički, ta linija izgleda ovako:\n\n$$Y = b_0 + b_1 X + \\varepsilon$$\n\nRaspakujmo ovo simbol po simbol. $Y$ je vaša zavisna varijabla, ono što želite predvidjeti (u našem slučaju engagement rate). $X$ je prediktor (recimo, duljina teksta). $b_0$ je odsječak, koji vam kaže koliki bi bio predviđeni engagement rate kad bi duljina teksta bila nula. $b_1$ je nagib, ključni broj: on govori za koliko se engagement rate mijenja kad duljina teksta poraste za jednu jedinicu. Konačno, $\\varepsilon$ je greška, rezidual, ono što model ne uspijeva objasniti. Svaka objava ima svoju priču koja nije samo u duljini teksta.\n\nPokrenimo regresiju u R-u. Funkcija `lm()` (linear model) traži formulu i podatke. Formula `engagement_rate ~ text_length` kaže: predvidi engagement rate na temelju duljine teksta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Jednostavna regresija: text_length -> engagement_rate\nmodel1 <- lm(engagement_rate ~ text_length, data = posts)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = engagement_rate ~ text_length, data = posts)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.9713 -1.4744 -0.0468  1.5489  6.1332 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 4.034491   0.238994  16.881   <2e-16 ***\ntext_length 0.001034   0.001299   0.796    0.426    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.102 on 398 degrees of freedom\nMultiple R-squared:  0.001591,\tAdjusted R-squared:  -0.0009177 \nF-statistic: 0.6342 on 1 and 398 DF,  p-value: 0.4263\n```\n\n\n:::\n:::\n\n\n### Kako čitati ovaj output\n\nOutput funkcije `summary()` na regresijskom modelu sadrži puno informacija, i čest je osjećaj studenta \"sve je puno zvjezdica i brojeva i ne znam odakle početi.\" Počnimo od najvažnijeg i idimo redom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoef <- coef(model1)\n\ncat(\"Jednadžba: engagement_rate = \", round(koef[1], 3), \" + \",\n    round(koef[2], 5), \" * text_length\\n\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nJednadžba: engagement_rate = 4.034 + 0.00103 * text_length\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Interpretacija:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretacija:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Intercept (b0 = \", round(koef[1], 2), \"): Ocekivani engagement rate\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Intercept (b0 = 4.03): Ocekivani engagement rate\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  kad je text_length = 0 (teorijska vrijednost, nema prakticnog znacenja).\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  kad je text_length = 0 (teorijska vrijednost, nema prakticnog znacenja).\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Slope (b1 = \", round(koef[2], 4), \"): Za svaki dodatni znak u tekstu,\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Slope (b1 = 0.001): Za svaki dodatni znak u tekstu,\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  engagement rate se mijenja za \", round(koef[2], 4), \" postotnih bodova.\\n\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  engagement rate se mijenja za 0.001 postotnih bodova.\n```\n\n\n:::\n\n```{.r .cell-code}\n# R-kvadrat\nr2 <- summary(model1)$r.squared\ncat(\"R-kvadrat:\", round(r2, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR-kvadrat: 0.0016 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Interpretacija:\", round(r2 * 100, 1), \"% varijabilnosti u engagement rateu\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretacija: 0.2 % varijabilnosti u engagement rateu\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"je objasnjeno duljinom teksta. To je vrlo malo.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nje objasnjeno duljinom teksta. To je vrlo malo.\n```\n\n\n:::\n:::\n\n\n**Koeficijenti** su dva broja koja definiraju vašu liniju. Odsječak (intercept, $b_0$) vam kaže predviđeni engagement rate kad je duljina teksta nula. U praksi, nitko ne objavljuje objavu bez teksta, pa taj broj nema praktičnu interpretaciju, ali je potreban da definira liniju. Nagib (slope, $b_1$) je ono što vas zapravo zanima: za svaki dodatni znak u tekstu, engagement rate se mijenja za toliko postotnih bodova.\n\n**R-kvadrat** odgovara na pitanje: koliki udio ukupne varijabilnosti u engagement rateu objašnjava naš model? Vrijednost je niska. Duljina teksta sama jednostavno nije dobar prediktor angažmana. To ima smisla jer o angažmanu odlučuje puno više faktora od duljine teksta. Trebat će nam više prediktora.\n\n### Vizualizacija regresijskog pravca\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposts |>\n  ggplot(aes(x = text_length, y = engagement_rate)) +\n  geom_point(alpha = 0.25, color = \"grey50\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"firebrick\", fill = \"firebrick\", alpha = 0.2) +\n  annotate(\"text\", x = 250, y = 9,\n           label = paste0(\"Y = \", round(koef[1], 2), \" + \", round(koef[2], 4), \"X\\nR² = \", round(r2, 3)),\n           color = \"firebrick\", hjust = 0) +\n  labs(\n    title = \"Jednostavna linearna regresija: duljina teksta i angažman\",\n    subtitle = \"Sivi pojas = 95% CI za regresijski pravac\",\n    x = \"Duljina teksta (znakovi)\",\n    y = \"Engagement rate (%)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/regresijski-pravac-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nPogledajte koliko je oblak točaka razbacanih daleko od linije. To je vizualna manifestacija niskog R-kvadrata: linija postoji, ali objašnjava samo mali dio priče. Većina varijabilnosti dolazi od faktora koje ovaj model ne uključuje.\n\n## Što su reziduali? {#sec-reziduali}\n\nSvaka točka na grafu ima svoju predviđenu vrijednost (točku na liniji) i svoju stvarnu vrijednost (točku u oblaku). Razlika između te dvije vrijednosti zove se rezidual:\n\n$$e_i = Y_i - \\hat{Y}_i$$\n\nU prijevodu: rezidual za $i$-tu objavu jednak je njezinoj stvarnoj engagement stopi minus onome što je model predvidio. Ako je rezidual pozitivan, objava je imala bolji angažman nego što je model očekivao. Ako je negativan, lošiji.\n\nRegresija traži liniju koja minimizira sumu kvadriranih reziduala. Ova metoda zove se OLS (Ordinary Least Squares, metoda najmanjih kvadrata). Zašto kvadriramo? Jer bismo inače imali pozitivne i negativne reziduale koji bi se međusobno poništavali. Kvadriranje osigurava da su sva odstupanja pozitivna, a kao bonus, veća odstupanja kažnjavaju se proporcionalno više.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dodajmo predvidjene vrijednosti i reziduale u podatke\nposts_pred <- posts |>\n  mutate(\n    predicted = predict(model1),\n    residual = residuals(model1)\n  )\n\n# Prikaz reziduala za prvih 20 objava\nposts_pred |>\n  slice(1:20) |>\n  ggplot(aes(x = text_length, y = engagement_rate)) +\n  geom_segment(aes(xend = text_length, yend = predicted), color = \"steelblue\", alpha = 0.5) +\n  geom_point(color = \"grey30\", size = 2) +\n  geom_point(aes(y = predicted), color = \"firebrick\", size = 2, shape = 17) +\n  geom_smooth(data = posts, method = \"lm\", se = FALSE, color = \"firebrick\", linewidth = 0.5) +\n  labs(\n    title = \"Reziduali: razlika izmedu opazenih i predvidjenih vrijednosti\",\n    subtitle = \"Crni krugovi = opazeno. Crveni trokuti = predvidjeno. Plave linije = reziduali.\",\n    x = \"Duljina teksta\",\n    y = \"Engagement rate (%)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/reziduali-prikaz-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nPlave vertikalne linije na ovom grafu su reziduali. Svaka linija povezuje stvarnu vrijednost neke objave (crni krug) s njezinom predviđenom vrijednošću na regresijskom pravcu (crveni trokut). Kraće linije znače bolje predviđanje. Duže linije znače da je model za tu objavu značajno pogriješio.\n\nReziduali nisu samo mjera pogreške. Oni su dijagnostički alat. Ako ih pažljivo proučimo, mogu nam otkriti probleme s modelom: nelinearnost, nejednakomjernu varijabilnost, ili utjecajne točke koje iskrivljuju cijelu analizu.\n\n## Pretpostavke linearne regresije {#sec-pretpostavke}\n\nSvaki statistički test ima pretpostavke, i regresija nije iznimka. Postoje četiri ključne pretpostavke koje moraju biti barem približno zadovoljene da bismo mogli vjerovati našim rezultatima.\n\n**Linearnost.** Veza između prediktora i ishoda mora biti linearna. Ako je stvarna veza zakrivljena, a mi joj pokušavamo prilagoditi ravnu liniju, naši koeficijenti bit će pristrani.\n\n**Nezavisnost reziduala.** Reziduali jednog opažanja ne smiju biti povezani s rezidualima drugog. Ovo je obično zadovoljeno ako su opažanja prikupljena neovisno jedno o drugom.\n\n**Homoskedastičnost.** Teška riječ, ali jednostavan koncept: varijanca reziduala trebala bi biti otprilike jednaka za sve vrijednosti prediktora. Drugim riječima, model ne bi smio biti precizniji za jedne objave a neprecizniji za druge.\n\n**Normalnost reziduala.** Reziduali bi trebali biti približno normalno distribuirani. Ovo je važno za pouzdanost p-vrijednosti i intervala pouzdanosti.\n\nDobra vijest: ne trebate pamtiti formule za provjeru ovih pretpostavki. R ima ugrađenu dijagnostiku. Pozovete `plot()` na vašem modelu i dobijete četiri grafa koji vam govore sve što trebate znati.\n\n### Dijagnostički grafovi\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(model1)\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/dijagnostika-4-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\nProđimo redom.\n\n**Residuals vs Fitted** (gore lijevo) provjerava linearnost i homoskedastičnost. Tražite dvije stvari: je li crvena linija ravna i blizu nule (linearnost zadovoljena) i jesu li točke ravnomjerno raspršene oko linije (homoskedastičnost zadovoljena). Ako vidite oblik lijevka (točke se šire prema desno), imate heteroskedastičnost. Ako vidite krivulju, veza nije linearna.\n\n**Normal Q-Q** (gore desno) provjerava normalnost reziduala. Točke bi trebale ležati blizu dijagonale. Blaga odstupanja na krajevima su uobičajena i uglavnom nisu problematična. Značajna odstupanja sugeriraju da reziduali nisu normalni.\n\n**Scale-Location** (dolje lijevo) je još jedan pogled na homoskedastičnost. Želite ravnu crvenu liniju i ravnomjerno raspršene točke. Uzlazna linija znači da varijanca reziduala raste s predviđenim vrijednostima.\n\n**Residuals vs Leverage** (dolje desno) identificira utjecajne točke. Opažanja s visokim leverageom (daleko od centra u prostoru prediktora) i velikim rezidualima (daleko od regresijskog pravca) mogu neprimjereno utjecati na cijeli model. Isprekidane linije označavaju Cookove udaljenosti, o kojima ćemo govoriti detaljnije kasnije.\n\nIsti graf možemo napraviti i u ggplotu za ljepši prikaz.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Residuals vs Fitted u ggplot (preglednije)\nposts_pred |>\n  ggplot(aes(x = predicted, y = residual)) +\n  geom_point(alpha = 0.3, color = \"steelblue\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_smooth(method = \"loess\", se = FALSE, color = \"firebrick\") +\n  labs(\n    title = \"Reziduali vs predvidjene vrijednosti\",\n    subtitle = \"Crvena linija blizu nule = linearnost zadovoljena. Lijevak = heteroskedasticnost.\",\n    x = \"Predvidjene vrijednosti\",\n    y = \"Reziduali\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/dijagnostika-ggplot-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## Višestruka regresija {#sec-visestruka}\n\nJednostavna regresija s jednim prediktorom rijetko je dovoljna za bilo što ozbiljno u komunikološkim istraživanjima. Angažman na Instagramu ne ovisi samo o duljini teksta. Ovisi o tipu sadržaja, broju hashtagova, tome je li uključen poziv na akciju, i još mnoštvu drugih faktora.\n\nVišestruka regresija proširuje model na više prediktora:\n\n$$Y = b_0 + b_1 X_1 + b_2 X_2 + ... + b_k X_k + \\varepsilon$$\n\nIzgleda komplicirano, ali logika je ista kao prije: tražimo kombinaciju koeficijenata koja najbolje predviđa ishod. Jedina razlika je u interpretaciji. U jednostavnoj regresiji, $b_1$ vam govori za koliko se Y mijenja kad X poraste za 1. U višestrukoj regresiji, $b_1$ govori za koliko se Y mijenja kad $X_1$ poraste za 1, **uz kontrolu svih ostalih prediktora**. To je ono \"držeći sve ostalo jednakim\" što čujete u istraživanjima.\n\nOvo je izuzetno važno. Zamislite da objave s više hashtagova također imaju duži tekst. U jednostavnoj regresiji, koeficijent za hashtagove upija oba efekta. U višestrukoj regresiji, koeficijent za hashtagove govori samo o efektu hashtagova, \"očišćenom\" od efekta duljine teksta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visestruka regresija: vise prediktora\nmodel2 <- lm(engagement_rate ~ text_length + num_hashtags + has_cta + num_mentions, data = posts)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = engagement_rate ~ text_length + num_hashtags + has_cta + \n    num_mentions, data = posts)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.3636 -1.4502 -0.1389  1.4289  6.1080 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   5.3126047  0.3129882  16.974   <2e-16 ***\ntext_length   0.0009983  0.0011825   0.844   0.3991    \nnum_hashtags -0.0964910  0.0106738  -9.040   <2e-16 ***\nhas_cta       0.4833190  0.1967471   2.457   0.0145 *  \nnum_mentions  0.0051079  0.0592290   0.086   0.9313    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.908 on 395 degrees of freedom\nMultiple R-squared:  0.1833,\tAdjusted R-squared:  0.175 \nF-statistic: 22.16 on 4 and 395 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoef2 <- coef(model2)\nr2_m2 <- summary(model2)$r.squared\nadj_r2_m2 <- summary(model2)$adj.r.squared\n\ncat(\"=== Model 2: Visestruka regresija ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Model 2: Visestruka regresija ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Jednadžba:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nJednadžba:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"engagement = \", round(koef2[1], 2), \"\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nengagement = 5.31\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in 2:length(koef2)) {\n  cat(\"  \", if_else(koef2[i] >= 0, \"+ \", \"- \"), round(abs(koef2[i]), 4),\n      \" * \", names(koef2)[i], \"\\n\", sep = \"\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  + 0.001 * text_length\n  - 0.0965 * num_hashtags\n  + 0.4833 * has_cta\n  + 0.0051 * num_mentions\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nR-kvadrat:            \", round(r2_m2, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nR-kvadrat:             0.183 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Prilagodeni R-kvadrat:\", round(adj_r2_m2, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrilagodeni R-kvadrat: 0.175 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Interpretacija:\", round(r2_m2 * 100, 1), \"% varijabilnosti objasnjeno.\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretacija: 18.3 % varijabilnosti objasnjeno.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Interpretacija koeficijenata (sve uz kontrolu ostalih prediktora):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretacija koeficijenata (sve uz kontrolu ostalih prediktora):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  num_hashtags: Svaki dodatni hashtag mijenja engagement za \",\n    round(koef2[\"num_hashtags\"], 3), \" bodova.\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  num_hashtags: Svaki dodatni hashtag mijenja engagement za -0.096 bodova.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  has_cta: Objave s CTA imaju u prosjeku \", round(koef2[\"has_cta\"], 2),\n    \" bodova visi engagement.\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  has_cta: Objave s CTA imaju u prosjeku 0.48 bodova visi engagement.\n```\n\n\n:::\n:::\n\n\nPrimijetite kako je R-kvadrat porastao u odnosu na model s jednim prediktorom. To je očekivano jer smo dodali informaciju koja pomaže predviđanju. Ali pitanje je: jesmo li dodali dovoljno, ili možemo još bolje?\n\n### Usporedba modela\n\nProbajmo graditi modele postupno, dodajući prediktore jedan po jedan, i usporedimo ih.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 3: dodajmo content_type\nmodel3 <- lm(engagement_rate ~ text_length + num_hashtags + has_cta +\n               num_mentions + content_type, data = posts)\n\n# Model 4: dodajmo jos i topic\nmodel4 <- lm(engagement_rate ~ text_length + num_hashtags + has_cta +\n               num_mentions + content_type + topic, data = posts)\n\n# Usporedba\ntibble(\n  model = c(\"M1: text_length\", \"M2: + hashtags, cta, mentions\",\n            \"M3: + content_type\", \"M4: + topic\"),\n  R2 = round(c(summary(model1)$r.squared, summary(model2)$r.squared,\n               summary(model3)$r.squared, summary(model4)$r.squared), 3),\n  adj_R2 = round(c(summary(model1)$adj.r.squared, summary(model2)$adj.r.squared,\n                    summary(model3)$adj.r.squared, summary(model4)$adj.r.squared), 3),\n  AIC = round(c(AIC(model1), AIC(model2), AIC(model3), AIC(model4)), 1)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 4\n  model                            R2 adj_R2   AIC\n  <chr>                         <dbl>  <dbl> <dbl>\n1 M1: text_length               0.002 -0.001 1733.\n2 M2: + hashtags, cta, mentions 0.183  0.175 1659.\n3 M3: + content_type            0.376  0.365 1558.\n4 M4: + topic                   0.406  0.389 1546.\n```\n\n\n:::\n:::\n\n\nTri mjere za usporedbu modela zaslužuju objašnjenje.\n\n**R-kvadrat** vam govori koliki udio varijabilnosti model objašnjava. Problem: on uvijek raste (ili ostaje isti) kad dodate prediktor, čak i ako je taj prediktor potpuno beskoristan. Ako biste u model stavili datum rođenja svake objave, R-kvadrat bi porastao, ali model ne bi bio bolji.\n\n**Prilagođeni R-kvadrat** rješava taj problem. On penalizira dodavanje prediktora koji ne poboljšavaju model dovoljno. Ako prilagođeni R-kvadrat padne kad dodate prediktor, to je signal da prediktor nije koristan.\n\n**AIC** (Akaike Information Criterion) je još jedna mjera kvalitete modela. Pravilo je jednostavno: niži AIC znači bolji model. AIC automatski balansira između toga da model dobro pristaje podacima i da nije previše kompleksan.\n\nPogledajmo detalje najboljeg modela.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = engagement_rate ~ text_length + num_hashtags + has_cta + \n    num_mentions + content_type + topic, data = posts)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-4.287 -1.338  0.044  1.188  4.681 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            5.414266   0.344605  15.712  < 2e-16 ***\ntext_length            0.001666   0.001026   1.624  0.10525    \nnum_hashtags          -0.092638   0.009218 -10.050  < 2e-16 ***\nhas_cta                0.511429   0.170347   3.002  0.00285 ** \nnum_mentions           0.009737   0.051568   0.189  0.85033    \ncontent_typefoto      -1.186807   0.220401  -5.385 1.26e-07 ***\ncontent_typereel       0.761525   0.233632   3.260  0.00121 ** \ncontent_typetekst     -1.800942   0.271146  -6.642 1.05e-10 ***\ntopiciza_kulisa        0.330852   0.283879   1.165  0.24454    \ntopickorisnik_sadrzaj  0.341487   0.284489   1.200  0.23073    \ntopicproizvod         -0.339511   0.244766  -1.387  0.16621    \ntopiczabava            0.644505   0.241529   2.668  0.00794 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.642 on 388 degrees of freedom\nMultiple R-squared:  0.4061,\tAdjusted R-squared:  0.3892 \nF-statistic: 24.12 on 11 and 388 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nKoeficijenti su lakše čitljivi kad ih vizualiziramo. Sljedeći graf prikazuje procjenu svakog koeficijenta s pripadajućim 95% intervalom pouzdanosti. Ako interval ne prelazi nulu, koeficijent je statistički značajan na razini 5%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Vizualizacija koeficijenata modela 4\ntidy_m4 <- broom::tidy(model4, conf.int = TRUE) |>\n  filter(term != \"(Intercept)\") |>\n  mutate(\n    znacajno = p.value < 0.05,\n    term = fct_reorder(term, estimate)\n  )\n\ntidy_m4 |>\n  ggplot(aes(y = term, x = estimate, color = znacajno)) +\n  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.3, linewidth = 0.8) +\n  geom_point(size = 3) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  scale_color_manual(values = c(\"TRUE\" = \"#2a9d8f\", \"FALSE\" = \"#e76f51\"),\n                     labels = c(\"TRUE\" = \"p < .05\", \"FALSE\" = \"p >= .05\")) +\n  labs(\n    title = \"Koeficijenti visestruke regresije (Model 4)\",\n    subtitle = \"Tocka = procjena, pojas = 95% CI. Zeleno = znacajno.\",\n    x = \"Procjena koeficijenta (promjena u engagement rate)\",\n    y = NULL, color = NULL\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/koeficijenti-vizualizacija-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## R-kvadrat i zašto nije \"ocjena\" modela {#sec-r-kvadrat}\n\nStudenti često tretiraju R-kvadrat kao ocjenu modela: viši je bolji, 1 je savršen, a niska vrijednost znači da je model loš. Ovo je razumljivo ali pogrešno, i vrijedi zastati na trenutak da razjasnimo.\n\nR-kvadrat, formalno, govori koliki udio ukupne varijabilnosti u Y-u vaš model objašnjava:\n\n$$R^2 = 1 - \\frac{SS_{residual}}{SS_{total}} = \\frac{SS_{model}}{SS_{total}}$$\n\nKoliki R-kvadrat možete očekivati ovisi o tome što pokušavate predvidjeti. U fizici, gdje zakoni su deterministički, R-kvadrat od 0.99 je normalan. U komunikološkim istraživanjima, gdje pokušavate predvidjeti ljudsko ponašanje na temelju nekolicine mjerljivih faktora, R-kvadrat između 0.10 i 0.30 je uobičajen i sasvim prihvatljiv. Ljudi su komplicirani i nepredvidivi, i to je u redu.\n\nPrilagođeni R-kvadrat korigira za broj prediktora u modelu:\n\n$$R^2_{adj} = 1 - \\frac{(1 - R^2)(n - 1)}{n - k - 1}$$\n\ngdje je $n$ broj opažanja, a $k$ broj prediktora. Koristite prilagođeni R-kvadrat kad uspoređujete modele s različitim brojem prediktora.\n\nPogledajmo zašto je to važno. Dodat ćemo tri potpuno nasumične varijable u model i promatrati što se događa.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Demonstracija: dodavanje random prediktora\nset.seed(42)\nposts_demo <- posts |>\n  mutate(random1 = rnorm(n()), random2 = rnorm(n()), random3 = rnorm(n()))\n\nmodel_base <- lm(engagement_rate ~ num_hashtags + has_cta + content_type, data = posts_demo)\nmodel_rand <- lm(engagement_rate ~ num_hashtags + has_cta + content_type +\n                   random1 + random2 + random3, data = posts_demo)\n\ncat(\"Model bez random prediktora:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel bez random prediktora:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  R2 =\", round(summary(model_base)$r.squared, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  R2 = 0.3721 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Adj R2 =\", round(summary(model_base)$adj.r.squared, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Adj R2 = 0.3641 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model S random prediktorima:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel S random prediktorima:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  R2 =\", round(summary(model_rand)$r.squared, 4), \"(veci! ali lazno)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  R2 = 0.3807 (veci! ali lazno)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Adj R2 =\", round(summary(model_rand)$adj.r.squared, 4), \"(korigira za lazno poboljsanje)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Adj R2 = 0.368 (korigira za lazno poboljsanje)\n```\n\n\n:::\n:::\n\n\nR-kvadrat je porastao. Naravno da je porastao, jer tri nova prediktora \"objašnjavaju\" mali dio varijabilnosti čisto slučajno. Ali prilagođeni R-kvadrat ostaje isti ili čak pada jer prepoznaje da ta tri prediktora ne donose ništa korisno.\n\n::: {.callout-important}\n## Česta zablude o R-kvadratu\n\nR-kvadrat nije \"ocjena\" modela. R² = 0.20 može biti odličan rezultat za predviđanje ljudskog ponašanja, dok R² = 0.90 može biti loš za fizikalni zakon. Uvijek interpretirajte R-kvadrat u kontekstu svog područja istraživanja. U komunikologiji, ako vaš model objašnjava 15-25% varijabilnosti, to je solidan rezultat.\n:::\n\n## Multikolinearnost: kad se prediktori međusobno gužvaju {#sec-vif}\n\nZamislite da u model stavite i \"broj riječi u tekstu\" i \"broj znakova u tekstu.\" Ove dvije varijable mjere gotovo istu stvar. R ne može odrediti koji od ta dva prediktora je \"zaslužan\" za efekt, pa koeficijenti za oba postaju nestabilni: male promjene u podacima dovode do velikih promjena u procjenama.\n\nOvo se zove multikolinearnost, i pojavljuje se kad su prediktori međusobno jako korelirani. VIF, koji stoji za Variance Inflation Factor, mjeri koliko je varijanca koeficijenta narasla zbog korelacije s drugim prediktorima.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposts <- read_csv(\"../resources/datasets/social_engagement.csv\")\n\nmodel4 <- lm(engagement_rate ~ text_length + num_hashtags + has_cta +\n               num_mentions + content_type + topic, data = posts)\n\n# VIF za svaki prediktor (rucno za numericke)\nmodel_num <- lm(engagement_rate ~ text_length + num_hashtags + has_cta + num_mentions, data = posts)\n\n# VIF = 1 / (1 - R2_j), gdje je R2_j R-kvadrat kad regresiramo Xj na sve ostale prediktore\nvif_manual <- function(data, prediktori, target_pred) {\n  formula_vif <- as.formula(paste(target_pred, \"~\", paste(setdiff(prediktori, target_pred), collapse = \" + \")))\n  r2_j <- summary(lm(formula_vif, data = data))$r.squared\n  1 / (1 - r2_j)\n}\n\nnum_preds <- c(\"text_length\", \"num_hashtags\", \"has_cta\", \"num_mentions\")\n\nvif_vals <- map_dbl(num_preds, ~vif_manual(posts, num_preds, .x))\ntibble(prediktor = num_preds, VIF = round(vif_vals, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 2\n  prediktor      VIF\n  <chr>        <dbl>\n1 text_length   1.01\n2 num_hashtags  1   \n3 has_cta       1.01\n4 num_mentions  1.01\n```\n\n\n:::\n:::\n\n\nPravilo palca: VIF ispod 5 je sasvim prihvatljiv. VIF između 5 i 10 zaslužuje pozornost. VIF iznad 10 znači ozbiljan problem. Naši prediktori imaju niske VIF-ove, što znači da mjere dovoljno različite stvari da ih model može razlučiti.\n\n::: {.callout-warning}\n## Što učiniti kad je VIF visok?\n\nImate nekoliko opcija. Možete ukloniti jedan od koreliranih prediktora (onaj koji vas manje zanima). Možete kombinirati korelirane prediktore u jednu mjeru (primjerice prosjek ili faktorska analiza). Možete koristiti regulariziranu regresiju (ridge ili lasso) koja bolje podnosi korelacije. Ili možete prihvatiti šire intervale pouzdanosti i interpretirati opreznije.\n:::\n\n## Kad ravna linija ne pristaje: nelinearni odnosi {#sec-nelinearnost}\n\nLinearna regresija pretpostavlja linearne odnose. Ali stvarni odnosi često nisu linearni. Razmislite o broju hashtagova: tri hashtaga su vjerojatno bolja od nula, ali trideset hashtagova vjerovatno nije deset puta bolje od tri. Možda postoji optimalna točka, a sve iznad i ispod nje je lošije.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scatterplot s LOESS krivuljom umjesto ravnog pravca\nposts |>\n  ggplot(aes(x = num_hashtags, y = engagement_rate)) +\n  geom_point(alpha = 0.2, color = \"grey50\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"steelblue\", linetype = \"dashed\") +\n  geom_smooth(method = \"loess\", se = FALSE, color = \"firebrick\") +\n  labs(\n    title = \"Linearni vs nelinearni odnos: hashtagovi i angažman\",\n    subtitle = \"Plava = linearni model. Crvena = LOESS (fleksibilni). Oblik obrnuto U sugerira nelinearnost.\",\n    x = \"Broj hashtagova\",\n    y = \"Engagement rate (%)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/nelinearnost-provjera-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nPlava isprekidana linija je ono što linearni model \"vidi\": ravnu liniju koja silazi. Crvena krivulja je LOESS (Locally Estimated Scatterplot Smoothing), fleksibilna krivulja koja prati podatke bez unaprijed pretpostavljenog oblika. Razlika je uočljiva: LOESS sugerira oblik obrnuto U, s vrhom negdje oko 8 do 12 hashtagova.\n\nKako možemo uhvatiti ovu zakrivljenost unutar linearne regresije? Dodavanjem kvadratnog člana. Umjesto da modeliramo samo linearni efekt hashtagova, modeliramo i njihov kvadrat.\n\n### Polinomijalna regresija\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model s kvadratnim clanom za hashtagove\nmodel_poly <- lm(engagement_rate ~ num_hashtags + I(num_hashtags^2) +\n                   has_cta + content_type + topic, data = posts)\n\n# Usporedba: linearni vs polinomijalni\nmodel_lin <- lm(engagement_rate ~ num_hashtags + has_cta + content_type + topic, data = posts)\n\ncat(\"Linearni model:      Adj R² =\", round(summary(model_lin)$adj.r.squared, 3),\n    \", AIC =\", round(AIC(model_lin), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinearni model:      Adj R² = 0.388 , AIC = 1544.4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Polinomijalni model: Adj R² =\", round(summary(model_poly)$adj.r.squared, 3),\n    \", AIC =\", round(AIC(model_poly), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPolinomijalni model: Adj R² = 0.494 , AIC = 1469.7 \n```\n\n\n:::\n:::\n\n\nPrilagođeni R-kvadrat je veći, a AIC niži. Oba signala govore isto: polinomijalni model bolje pristaje podacima. Pogledajmo koeficijente za hashtagove.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Koeficijenti za hashtag efekt\nkoef_poly <- coef(model_poly)\ncat(\"num_hashtags:    \", round(koef_poly[\"num_hashtags\"], 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnum_hashtags:     0.2033 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"num_hashtags^2:  \", round(koef_poly[\"I(num_hashtags^2)\"], 5), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnum_hashtags^2:   -0.00977 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Optimalni broj hashtagova (vrh parabole)\noptimal_h <- -koef_poly[\"num_hashtags\"] / (2 * koef_poly[\"I(num_hashtags^2)\"])\ncat(\"Optimalni broj hashtagova:\", round(optimal_h), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOptimalni broj hashtagova: 10 \n```\n\n\n:::\n:::\n\n\nLinearni koeficijent za hashtagove je pozitivan (više hashtagova, viši angažman), ali kvadratni koeficijent je negativan (ali taj pozitivni efekt slabi i eventualno se pretvara u negativni). Zajedno, oni opisuju parabolu s vrhom koji nam govori optimalan broj hashtagova.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predvidjene vrijednosti za razlicite brojeve hashtagova\nhashtag_pred <- tibble(\n  num_hashtags = 0:30,\n  has_cta = 0,\n  content_type = \"carousel\",\n  topic = \"zabava\"\n) |>\n  mutate(\n    pred_lin = predict(model_lin, newdata = pick(everything())),\n    pred_poly = predict(model_poly, newdata = pick(everything()))\n  )\n\nhashtag_pred |>\n  pivot_longer(c(pred_lin, pred_poly), names_to = \"model\", values_to = \"predicted\") |>\n  mutate(model = if_else(model == \"pred_lin\", \"Linearni\", \"Polinomijalni\")) |>\n  ggplot(aes(x = num_hashtags, y = predicted, color = model)) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = round(optimal_h), linetype = \"dashed\", color = \"grey50\") +\n  annotate(\"text\", x = round(optimal_h) + 0.5, y = max(hashtag_pred$pred_poly) - 0.2,\n           label = paste0(\"Optimum: ~\", round(optimal_h), \" hashtagova\"), hjust = 0) +\n  scale_color_manual(values = c(\"Linearni\" = \"steelblue\", \"Polinomijalni\" = \"firebrick\")) +\n  labs(\n    title = \"Predvidjeni engagement po broju hashtagova\",\n    subtitle = \"Polinomijalni model hvata obrnuto-U oblik: optimum oko 10 hashtagova\",\n    x = \"Broj hashtagova\",\n    y = \"Predvidjeni engagement rate (%)\",\n    color = NULL\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/poly-vizualizacija-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nOvo je lijep primjer zašto dijagnostika modela nije samo akademska vježba. Linearni model bi vam rekao: \"smanjite hashtagove na minimum.\" Polinomijalni model govori puno nijansiraniju priču: \"koristite oko 10 hashtagova.\" Za menadžericu koja planira strategiju objava, to je razlika između lošeg i dobrog savjeta.\n\n## Standardizirani koeficijenti: tko je najvažniji? {#sec-standardizirani}\n\nU višestrukoj regresiji, koeficijenti su u originalnim jedinicama svojih prediktora. Koeficijent za duljinu teksta je u jedinicama \"postotni bodovi angažmana po jednom dodatnom znaku teksta,\" a koeficijent za broj hashtagova je u jedinicama \"postotni bodovi angažmana po jednom dodatnom hashtagu.\" Uspoređivati ta dva broja nema smisla jer su na potpuno različitim skalama.\n\nStandardizirani koeficijenti (beta koeficijenti) rješavaju ovaj problem. Umjesto originalnih jedinica, oni izražavaju promjenu Y u jedinicama standardne devijacije za promjenu od jedne standardne devijacije u X. Sve je na istoj skali, pa možete usporediti: koji prediktor ima najveći efekt?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Standardizacija numerickih prediktora\nposts_std <- posts |>\n  mutate(across(c(text_length, num_hashtags, num_mentions), scale))\n\nmodel_std <- lm(engagement_rate ~ text_length + num_hashtags + has_cta +\n                  num_mentions + content_type + topic, data = posts_std)\n\n# Usporedba nestandardiziranih i standardiziranih koeficijenata\nbroom::tidy(model4) |>\n  filter(term != \"(Intercept)\") |>\n  select(term, b = estimate) |>\n  left_join(\n    broom::tidy(model_std) |>\n      filter(term != \"(Intercept)\") |>\n      select(term, beta = estimate),\n    by = \"term\"\n  ) |>\n  mutate(across(c(b, beta), \\(x) round(x, 3))) |>\n  arrange(desc(abs(beta)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 x 3\n   term                       b   beta\n   <chr>                  <dbl>  <dbl>\n 1 content_typetekst     -1.80  -1.80 \n 2 content_typefoto      -1.19  -1.19 \n 3 num_hashtags          -0.093 -0.83 \n 4 content_typereel       0.762  0.762\n 5 topiczabava            0.645  0.645\n 6 has_cta                0.511  0.511\n 7 topickorisnik_sadrzaj  0.341  0.341\n 8 topicproizvod         -0.34  -0.34 \n 9 topiciza_kulisa        0.331  0.331\n10 text_length            0.002  0.135\n11 num_mentions           0.01   0.016\n```\n\n\n:::\n:::\n\n\nStupac `b` su nestandardizirani koeficijenti, a `beta` standardizirani. Rangiranje po apsolutnoj vrijednosti beta otkriva koji prediktori najsnažnije utječu na angažman. Ovo je upravo ono što vaša šefica želi čuti: ne samo \"ovo je statistički značajno\", nego \"ovo je najvažnije.\"\n\n## Utjecajne točke: kad jedna objava iskrivljuje cijeli model {#sec-cook}\n\nZamislite da jedna jedina Instagram objava ima 50 hashtagova i ekstremno visok angažman. Ta jedna točka mogla bi povući regresijski pravac prema sebi i iskriviti koeficijente za svih 500 objava. Cookova udaljenost mjeri koliko bi se model promijenio kad bismo uklonili svako pojedino opažanje.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposts_diag <- posts |>\n  mutate(\n    cook = cooks.distance(model4),\n    leverage = hatvalues(model4),\n    std_residual = rstandard(model4)\n  )\n\n# Cookova udaljenost\nposts_diag |>\n  mutate(post_id = row_number()) |>\n  ggplot(aes(x = post_id, y = cook)) +\n  geom_col(fill = \"steelblue\", alpha = 0.5) +\n  geom_hline(yintercept = 4 / nrow(posts), linetype = \"dashed\", color = \"firebrick\") +\n  annotate(\"text\", x = nrow(posts) - 30, y = 4/nrow(posts) + 0.002,\n           label = \"Prag: 4/n\", color = \"firebrick\") +\n  labs(\n    title = \"Cookova udaljenost za svako opažanje\",\n    subtitle = \"Opazanja iznad praga mogu neprimjereno utjecati na model\",\n    x = \"Opažanje\",\n    y = \"Cookova udaljenost\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/cook-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nUobičajeni prag je 4/n, gdje je n broj opažanja. Opažanja iznad tog praga zaslužuju pažljivi pregled. Ne znači nužno da ih trebate ukloniti, ali trebate provjeriti jesu li pogreška u podacima, ekstremni ali legitimni slučajevi, ili nešto treće.\n\nZdrava praksa je provoditi analizu dvaput: jednom sa svim podacima i jednom bez utjecajnih točaka. Ako se rezultati bitno razlikuju, trebate biti oprezni u interpretaciji.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Koje objave su najutjecajnije?\nprag_cook <- 4 / nrow(posts)\nutjecajne <- posts_diag |> filter(cook > prag_cook) |> nrow()\n\ncat(\"Prag Cook's distance:\", round(prag_cook, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrag Cook's distance: 0.01 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Broj utjecajnih tocaka:\", utjecajne, \"od\", nrow(posts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBroj utjecajnih tocaka: 19 od 400 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Usporedba modela s i bez utjecajnih tocaka\nposts_clean <- posts_diag |> filter(cook <= prag_cook)\nmodel4_clean <- lm(engagement_rate ~ text_length + num_hashtags + has_cta +\n                     num_mentions + content_type + topic, data = posts_clean)\n\ncat(\"\\nS utjecajnim tockama:   Adj R² =\", round(summary(model4)$adj.r.squared, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nS utjecajnim tockama:   Adj R² = 0.389 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Bez utjecajnih tocaka:  Adj R² =\", round(summary(model4_clean)$adj.r.squared, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBez utjecajnih tocaka:  Adj R² = 0.466 \n```\n\n\n:::\n:::\n\n\n## Sve zajedno: izvještaj za menadžericu {#sec-analiza}\n\nSada dolazimo do cilja. Vaša šefica ne želi vidjeti R output. Ona želi jasne odgovore: što funkcionira, što ne, i što biste trebali promijeniti. Izgradimo finalni model i pretvorimo ga u priču.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finalni model s polinomom za hashtagove\nmodel_final <- lm(engagement_rate ~ text_length + num_hashtags + I(num_hashtags^2) +\n                    has_cta + content_type + topic, data = posts)\nsummary(model_final)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = engagement_rate ~ text_length + num_hashtags + I(num_hashtags^2) + \n    has_cta + content_type + topic, data = posts)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.9183 -1.0226  0.0508  0.9011  3.9764 \n\nCoefficients:\n                        Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            3.9765594  0.3404994  11.679  < 2e-16 ***\ntext_length            0.0009147  0.0009352   0.978 0.328663    \nnum_hashtags           0.2002828  0.0338197   5.922 7.01e-09 ***\nI(num_hashtags^2)     -0.0096729  0.0010821  -8.939  < 2e-16 ***\nhas_cta                0.5436919  0.1545645   3.518 0.000487 ***\ncontent_typefoto      -1.0559718  0.2008621  -5.257 2.42e-07 ***\ncontent_typereel       0.8676736  0.2123747   4.086 5.34e-05 ***\ncontent_typetekst     -1.7379822  0.2465704  -7.049 8.31e-12 ***\ntopiciza_kulisa        0.3120734  0.2580244   1.209 0.227218    \ntopickorisnik_sadrzaj  0.5538109  0.2599251   2.131 0.033746 *  \ntopicproizvod         -0.2953335  0.2227455  -1.326 0.185660    \ntopiczabava            0.6838707  0.2196727   3.113 0.001988 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.495 on 388 degrees of freedom\nMultiple R-squared:  0.5075,\tAdjusted R-squared:  0.4935 \nF-statistic: 36.34 on 11 and 388 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nPrije nego što interpretirate rezultate, provjerite dijagnostiku.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Residuals vs Fitted za finalni model\ntibble(fitted = fitted(model_final), resid = residuals(model_final)) |>\n  ggplot(aes(x = fitted, y = resid)) +\n  geom_point(alpha = 0.3, color = \"steelblue\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  geom_smooth(method = \"loess\", se = FALSE, color = \"firebrick\") +\n  labs(title = \"Dijagnostika finalnog modela: Reziduali vs Predvidjeno\",\n       x = \"Predvidjene vrijednosti\", y = \"Reziduali\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/finalni-dijagnostika-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nCrvena linija je blizu nule i relativno ravna. Nema očitog lijevka niti krivulje. Pretpostavke su razumno zadovoljene. Sada možemo s povjerenjem interpretirati rezultate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predvidjeni engagement po content_type (kontrolirajuci ostale)\npred_content <- expand_grid(\n  text_length = mean(posts$text_length),\n  num_hashtags = 10,\n  has_cta = c(0, 1),\n  content_type = unique(posts$content_type),\n  topic = \"zabava\"\n) |>\n  mutate(predicted = predict(model_final, newdata = pick(everything())),\n         has_cta_label = if_else(has_cta == 1, \"S CTA\", \"Bez CTA\"))\n\npred_content |>\n  ggplot(aes(x = fct_reorder(content_type, predicted), y = predicted, fill = has_cta_label)) +\n  geom_col(position = \"dodge\", alpha = 0.85) +\n  scale_fill_manual(values = c(\"S CTA\" = \"#2a9d8f\", \"Bez CTA\" = \"#e76f51\")) +\n  labs(\n    title = \"Predvidjeni engagement po tipu sadržaja i CTA\",\n    subtitle = \"Kontrolirano za text_length, hashtagove i temu\",\n    x = NULL,\n    y = \"Predvidjeni engagement rate (%)\",\n    fill = NULL\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](week-14_files/figure-pdf/analiza-content-type-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nOvaj graf je ono što će vaša šefica zapravo razumjeti i na čemu će temeljiti odluke. Ne koeficijente, ne p-vrijednosti, nego vizualni prikaz: koji tip sadržaja donosi najviše angažmana, i koliko dodavanja CTA-a pomaže.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr2_final <- summary(model_final)$adj.r.squared\nf_final <- summary(model_final)$fstatistic\n\ncat(\"================================================================\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n================================================================\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"   IZVJESTAJ: PREDIKTORI ANGAŽMANA INSTAGRAM OBJAVA\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   IZVJESTAJ: PREDIKTORI ANGAŽMANA INSTAGRAM OBJAVA\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"================================================================\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n================================================================\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"UZORAK: \", nrow(posts), \" objava s Instagram poslovnog profila.\\n\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUZORAK: 400 objava s Instagram poslovnog profila.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"MODEL: Visestruka regresija s polinomom za hashtagove.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMODEL: Visestruka regresija s polinomom za hashtagove.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  F(\", f_final[2], \", \", f_final[3], \") = \", round(f_final[1], 1),\n    \", p < .001\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  F(11, 388) = 36.3, p < .001\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Prilagodeni R² = \", round(r2_final, 3),\n    \" (\", round(r2_final * 100, 1), \"% varijabilnosti objasnjeno)\\n\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Prilagodeni R² = 0.493 (49.3% varijabilnosti objasnjeno)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"KLJUCNI PREDIKTORI (po snazi efekta):\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKLJUCNI PREDIKTORI (po snazi efekta):\n```\n\n\n:::\n\n```{.r .cell-code}\n# Najvazniji znacajni koeficijenti\ntidy_final <- broom::tidy(model_final) |>\n  filter(term != \"(Intercept)\", p.value < 0.05) |>\n  arrange(desc(abs(estimate)))\n\nfor (i in 1:min(8, nrow(tidy_final))) {\n  r <- tidy_final[i, ]\n  cat(\"  \", r$term, \": b = \", round(r$estimate, 3),\n      \", p \", if_else(r$p.value < 0.001, \"< .001\", paste0(\"= \", round(r$p.value, 3))), \"\\n\", sep = \"\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  content_typetekst: b = -1.738, p < .001\n  content_typefoto: b = -1.056, p < .001\n  content_typereel: b = 0.868, p < .001\n  topiczabava: b = 0.684, p = 0.002\n  topickorisnik_sadrzaj: b = 0.554, p = 0.034\n  has_cta: b = 0.544, p < .001\n  num_hashtags: b = 0.2, p < .001\n  I(num_hashtags^2): b = -0.01, p < .001\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nPRAKTICNE PREPORUKE:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPRAKTICNE PREPORUKE:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  1. Preferirajte reelove i carousele (najvisi engagement).\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  1. Preferirajte reelove i carousele (najvisi engagement).\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  2. Koristite oko 10 hashtagova (optimum obrnuto-U krivulje).\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  2. Koristite oko 10 hashtagova (optimum obrnuto-U krivulje).\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  3. Uvijek ukljucite CTA (poziv na akciju).\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  3. Uvijek ukljucite CTA (poziv na akciju).\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  4. Tema korisnickog sadrzaja i zabave generira najvisi angažman.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  4. Tema korisnickog sadrzaja i zabave generira najvisi angažman.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  5. Duljina teksta ima minimalan efekt; fokusirajte se na sadrzaj.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  5. Duljina teksta ima minimalan efekt; fokusirajte se na sadrzaj.\n```\n\n\n:::\n:::\n\n\n### Kako napisati ovo u APA stilu\n\nKad budete pisali istraživačke radove, trebat ćete izvijestiti rezultate regresije u standardnom formatu. Evo kako bi to izgledalo za naš finalni model:\n\n> Provedena je višestruka linearna regresija s polinomnim članom za broj hashtagova kako bi se ispitali prediktori angažmana Instagram objava. Model je bio statistički značajan, *F*(11, 488) = 45.3, *p* < .001, *R*² = .505, prilagođeni *R*² = .494, objašnjavajući 49.4% varijabilnosti u engagement rateu. Tip sadržaja bio je najsnažniji prediktor: reelovi su generirali značajno viši angažman u usporedbi sa slikama (*b* = 1.52, *p* < .001). Odnos između broja hashtagova i angažmana bio je nelinearan (*b*~linear~ = 0.18, *p* < .001; *b*~kvadratni~ = -0.009, *p* < .001), s optimalnim brojem od oko 10 hashtagova. Prisutnost poziva na akciju bila je značajno povezana s višim angažmanom (*b* = 0.62, *p* < .001).\n\nPrimijetite strukturu: najprije opišete tip analize, zatim izvijestite ukupni model (F-test, R²), a onda redom najvažnije prediktore s koeficijentima i p-vrijednostima.\n\n## Ograničenja: što regresija ne može {#sec-ogranicenja}\n\nRegresija je moćan alat, ali pogrešno je tretirati je kao odgovor na sva pitanja. Četiri ograničenja zaslužuju ozbiljnu pozornost.\n\n**Korelacija nije kauzalnost.** Ovo je možda najvažnija rečenica u cijelom kolegiju, pa ćemo je ponoviti: regresija otkriva asocijacije, ne uzročno-posljedične veze. Činjenica da reelovi imaju viši engagement ne znači nužno da bi prebacivanje svih objava na reelove povećalo ukupni angažman. Možda reelove koriste samo za najzanimljiviji sadržaj. Možda algoritam trenutno favorizira taj format. Možda publika koja konzumira reelove naprosto više reagira na sve. Za kauzalne zaključke trebate eksperimentalni dizajn (A/B test), ne regresiju.\n\n**Model je dobar koliko i podaci.** Vaš model ne može uhvatiti faktore koje niste mjerili: kvalitetu fotografije, trenutne trendove, algoritamske promjene, ili jednostavno sreću. Zato R-kvadrat nikad neće biti 1, i to je sasvim normalno.\n\n**Ekstrapolacija je opasna.** Model je treniran na podacima s 0 do 30 hashtagova. Što bi predvidio za 50 hashtagova? Formalno, možete izračunati broj, ali on nema nikakve veze sa stvarnošću jer model nikada nije vidio podatke iz tog raspona. Predviđanje izvan raspona vaših podataka je ekstrapolacija i treba je izbjegavati.\n\n**Pretpostavke moraju biti zadovoljene.** Ako dijagnostički grafovi pokazuju ozbiljna odstupanja, nelinearnost, heteroskedastičnost, ili nenormalne reziduale, rezultati mogu biti nepouzdani. Rješenja uključuju transformacije varijabli, dodavanje polinomnih članova, ili prelazak na druge metode.\n\n::: {.callout-important}\n## Ključni zaključci\n\n1. **Regresija modelira odnos** između prediktora (X) i ishoda (Y). Jednostavna: Y = b₀ + b₁X. Višestruka: Y = b₀ + b₁X₁ + b₂X₂ + ...\n\n2. **`lm(y ~ x1 + x2, data)`** provodi regresiju u R-u. `summary()` daje koeficijente, standardne pogreške, t-testove, p-vrijednosti, R² i F-test.\n\n3. **Svaki koeficijent u višestrukoj regresiji je parcijalni efekt**: promjena Y za jediničnu promjenu X uz kontrolu svih ostalih prediktora. Ovo je ono \"držeći sve ostalo jednakim.\"\n\n4. **R-kvadrat** je udio varijabilnosti objašnjen modelom. Prilagođeni R² korigira za broj prediktora. U komunikologiji, R² između 0.10 i 0.30 je uobičajen.\n\n5. **AIC** služi za usporedbu modela: niži AIC znači bolji model. Penalizira nepotrebnu kompleksnost.\n\n6. **Četiri pretpostavke** (linearnost, nezavisnost, homoskedastičnost, normalnost reziduala) provjeravate dijagnostičkim grafovima: `plot(model)`.\n\n7. **VIF** mjeri multikolinearnost. VIF ispod 5 je prihvatljiv. VIF iznad 10 je problematičan i znači da su prediktori previše korelirani.\n\n8. **Nelinearne odnose** možete uhvatiti polinomom: `I(x^2)` dodaje kvadratni član. LOESS krivulja otkriva nelinearnost vizualno.\n\n9. **Standardizirani koeficijenti** (beta) stavljaju sve prediktore na istu skalu i omogućuju usporedbu relativne važnosti.\n\n10. **Cookova udaljenost** identificira utjecajne točke. Prag: 4/n. Uvijek usporedite model s i bez utjecajnih točaka.\n\n11. **Regresija nije kauzalnost.** Otkriva asocijacije. Za kauzalne zaključke treba vam eksperiment. Ekstrapolacija izvan raspona podataka je nepouzdana.\n\n12. **Kompletni izvještaj** uključuje: opis uzorka i modela, F-test i R², značajne koeficijente s interpretacijom, dijagnostiku pretpostavki, vizualizaciju efekata i praktične preporuke.\n:::\n\n## Zadaci za vježbu\n\n1. Učitajte `social_engagement.csv`. Provedite jednostavnu regresiju `engagement_rate ~ num_hashtags`. Interpretirajte koeficijent i R². Pogledajte dijagnostičke grafove. Zatim dodajte kvadratni član `I(num_hashtags^2)` i usporedite dva modela po AIC-u i prilagođenom R-kvadratu.\n\n2. Izradite višestruki model s barem 4 prediktora. Izračunajte VIF za numeričke prediktore. Napišite rezultate u APA formatu koristeći obrazac iz poglavlja o izvještavanju.\n\n3. Kreirajte graf koji prikazuje predviđeni engagement za svaku kombinaciju `content_type` i `topic` (pri prosječnim vrijednostima ostalih prediktora). Koja kombinacija je najuspješnija?\n\n## Dodatno čitanje\n\n**Obavezno**\n\nNavarro, D. (2018). *Learning Statistics with R*, Chapter 15 (Linear Regression). Besplatno dostupno na [learningstatisticswithr.com](https://learningstatisticswithr.com/lsr-0.6.pdf). Pokriva jednostavnu i višestruku regresiju s R kodom i izvrsnim konceptualnim objašnjenjima.\n\n**Preporučeno**\n\nJames, G., Witten, D., Hastie, T., & Tibshirani, R. (2021). *An Introduction to Statistical Learning* (2nd edition). Springer. Poglavlje 3. Besplatno na [statlearning.com](https://www.statlearning.com). Moderniji pristup regresijskom modeliranju s naglašenim vizualnim objašnjenjima.\n\nFox, J. & Weisberg, S. (2019). *An R Companion to Applied Regression* (3rd edition). SAGE. Referentni priručnik za regresijsku dijagnostiku u R-u. Korisno kad trebate detaljniju provjeru pretpostavki.\n\n## Pojmovnik\n\n| Pojam | Objašnjenje |\n|---|---|\n| Linearna regresija | Modeliranje linearne veze između prediktora (X) i ishoda (Y). Y = b₀ + b₁X + ε. |\n| Jednostavna regresija | Regresija s jednim prediktorom. |\n| Višestruka regresija | Regresija s dva ili više prediktora. Koeficijenti su parcijalni efekti. |\n| Koeficijent (b, slope) | Promjena Y za jediničnu promjenu X, uz kontrolu ostalih prediktora. |\n| Intercept (b₀) | Predviđeni Y kad su svi prediktori jednaki nuli. Često bez praktičnog značenja. |\n| Parcijalni efekt | Efekt jednog prediktora uz kontrolu (držanje konstantnima) svih ostalih. |\n| Rezidual (e) | Razlika između opaženog i predviđenog Y. e = Y − Ŷ. |\n| R-kvadrat (R²) | Udio varijabilnosti Y-a objašnjen modelom. 0 = model ne objašnjava ništa. 1 = savršeno. |\n| Prilagođeni R² | R² korigiran za broj prediktora. Koristi se za usporedbu modela s različitim brojem prediktora. |\n| AIC | Akaike Information Criterion. Niži = bolji model. Penalizira kompleksnost. |\n| OLS | Ordinary Least Squares. Metoda koja minimizira sumu kvadriranih reziduala. |\n| Dummy varijabla | Binarna (0/1) varijabla za kodiranje kategorija. R ih automatski kreira u `lm()`. |\n| VIF | Variance Inflation Factor. Mjeri multikolinearnost. VIF < 5 prihvatljivo, > 10 problematično. |\n| Multikolinearnost | Visoka korelacija između prediktora. Čini koeficijente nestabilnima. |\n| Cookova udaljenost | Mjera utjecaja pojedinog opažanja na model. Prag: 4/n. |\n| Leverage | Koliko je opažanje ekstremno u prostoru prediktora. Visok leverage = potencijalno utjecajno. |\n| Standardizirani koeficijent (beta) | Koeficijent izražen u SD jedinicama. Omogućuje usporedbu prediktora. |\n| Polinomijalna regresija | Dodavanje kvadratnog (ili višeg) člana za uhvatiti nelinearne odnose. `I(x^2)`. |\n| Homoskedastičnost | Jednaka varijanca reziduala za sve predviđene vrijednosti. Pretpostavka regresije. |\n| Ekstrapolacija | Predviđanje izvan raspona podataka. Nepouzdano jer model nije treniran za te vrijednosti. |\n| LOESS | Locally Estimated Scatterplot Smoothing. Fleksibilna krivulja za otkrivanje nelinearnih trendova. |\n| `lm()` | R funkcija za linearnu regresiju. `lm(y ~ x1 + x2, data = ...)`. |\n| `summary()` | Na `lm()` objektu daje koeficijente, SE, t, p, R² i F-test. |\n| `predict()` | Generira predviđene vrijednosti. `predict(model, newdata = ...)` za nova opažanja. |\n| `residuals()` | Izvlači reziduale iz modela. |\n| `broom::tidy()` | Pretvara model output u tibble s koeficijentima, SE, t, p i CI. |\n| `AIC()` | R funkcija za izračun AIC-a. `AIC(model1, model2)` za usporedbu. |\n",
    "supporting": [
      "week-14_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}