{
  "hash": "cc7f9cfcf6911547387311323a219334",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tjedan 10: Testiranje hipoteza\"\nsubtitle: \"Kako donijeti odluku na temelju podataka\"\ndate: 2025-04-26\ncategories: [testiranje hipoteza, p-vrijednost, t-test, greške tipa I i II, veličina učinka]\ndraft: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n::: {.callout-note}\n## Ishodi učenja\n\nNakon ovog predavanja moći ćete\n\n1. Formulirati nultu i alternativnu hipotezu za istraživačko pitanje.\n2. Objasniti logiku testiranja hipoteza kroz analogiju sa suđenjem.\n3. Izračunati i interpretirati testnu statistiku i p-vrijednost.\n4. Provesti jednosmjerni i dvosmjerni t-test u R-u pomoću `t.test()`.\n5. Objasniti razliku između greške tipa I i greške tipa II.\n6. Izračunati i interpretirati Cohenov d kao mjeru veličine učinka.\n7. Objasniti koncept statističke snage i faktore koji na nju utječu.\n8. Kritički ocijeniti statističku značajnost u kontekstu praktične važnosti.\n:::\n\n## Motivacija: A/B test na Instagramu\n\nRadite kao analitičar u redakciji medijske kuće. Urednica vas pita: \"Imamo li dokaz da carousel objave generiraju veći angažman od običnih slika?\" Zadnjih nekoliko mjeseci objavljujete oba formata i sada imate podatke.\n\nProsjek angažmana za carousel je 10.1%. Za obične slike je 7.5%. Razlika postoji. Ali je li to prava razlika ili samo posljedica slučajnosti? Možda bismo, da ponovimo eksperiment, dobili obrnuti rezultat?\n\nOvo je temeljno pitanje testiranja hipoteza: je li opažena razlika dovoljno velika da isključimo slučajnost kao objašnjenje?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nig <- read_csv(\"../resources/datasets/instagram_ab_test.csv\")\nglimpse(ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 500\nColumns: 11\n$ post_id         <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,…\n$ format          <chr> \"carousel\", \"carousel\", \"carousel\", \"carousel\", \"carou…\n$ topic           <chr> \"sport\", \"tech\", \"sport\", \"vijesti\", \"kultura\", \"kultu…\n$ time_of_day     <chr> \"poslijepodne\", \"jutro\", \"večer\", \"poslijepodne\", \"pod…\n$ has_cta         <lgl> TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, TRU…\n$ reach           <dbl> 803, 1028, 4570, 1915, 4539, 3620, 3058, 2818, 4432, 2…\n$ likes           <dbl> 48, 62, 200, 87, 428, 151, 61, 132, 212, 159, 210, 65,…\n$ comments        <dbl> 14, 10, 94, 21, 47, 61, 27, 32, 108, 26, 42, 4, 30, 21…\n$ shares          <dbl> 7, 8, 22, 25, 45, 50, 21, 27, 4, 14, 26, 5, 12, 14, 6,…\n$ saves           <dbl> 16, 23, 49, 27, 67, 38, 30, 56, 84, 51, 28, 3, 12, 26,…\n$ engagement_rate <dbl> 0.1059, 0.1002, 0.0799, 0.0836, 0.1293, 0.0829, 0.0455…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nig |>\n  group_by(format) |>\n  summarise(\n    n = n(),\n    M_engagement = round(mean(engagement_rate) * 100, 2),\n    SD_engagement = round(sd(engagement_rate) * 100, 2),\n    M_likes = round(mean(likes), 1),\n    M_comments = round(mean(comments), 1),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  format           n M_engagement SD_engagement M_likes M_comments\n  <chr>        <int>        <dbl>         <dbl>   <dbl>      <dbl>\n1 carousel       236         10.1          2.11    180.       35.7\n2 single_image   264          7.5          1.77    149.       24.4\n```\n\n\n:::\n:::\n\n\nCarousel objave imaju viši angažman u prosjeku. Ali svaka grupa ima i vlastitu varijabilnost. Pitanje je: kolika je šansa da bismo vidjeli ovakvu ili veću razliku i da carousel zapravo NIJE bolji?\n\n---\n\n## Logika testiranja hipoteza {#sec-logika}\n\nTestiranje hipoteza slijedi logiku koja je slična suđenju u kaznenom pravu.\n\nNa sudu, optuženik je nevin dok se ne dokaže krivnja. Ne trebate dokazati nevinost. Trebate dokazati krivnju izvan razumne sumnje. Ako nema dovoljno dokaza, presuda je \"nedokazano\" (ne \"nevin\").\n\nU statistici, početna pretpostavka je da nema učinka (nema razlike, nema veze). Ovu pretpostavku zovemo **nulta hipoteza** (H₀). Istraživač pokušava prikupiti dovoljno dokaza da odbaci nultu hipotezu u korist **alternativne hipoteze** (H₁) koja tvrdi da učinak postoji.\n\nZa naš Instagram primjer:\n\n**H₀**: Nema razlike u angažmanu između carousel i single image formata. Svaka opažena razlika je posljedica slučajnosti.\n\n**H₁**: Postoji razlika u angažmanu između dva formata. Opažena razlika odražava stvarnu razliku u populaciji.\n\nMatematički:\n\n$$H_0: \\mu_{carousel} = \\mu_{single}$$\n$$H_1: \\mu_{carousel} \\neq \\mu_{single}$$\n\n::: {.callout-important}\n## Važna napomena\n\nNulta hipoteza uvijek sadrži znak jednakosti (= ili ≤ ili ≥). Alternativna hipoteza sadrži znak nejednakosti (≠ ili > ili <). Nikad obrnuto. Testiramo nultu hipotezu i tražimo dokaze protiv nje.\n:::\n\n---\n\n## Od hipoteze do odluke: korak po korak {#sec-koraci}\n\nCijeli postupak testiranja hipoteza ima pet koraka.\n\n**Korak 1**: Postavite hipoteze (H₀ i H₁).\n\n**Korak 2**: Odaberite razinu značajnosti (α). To je prag ispod kojeg ćete odbaciti H₀. Konvencija je α = 0.05 (5%).\n\n**Korak 3**: Izračunajte testnu statistiku iz podataka.\n\n**Korak 4**: Izračunajte p-vrijednost (vjerojatnost dobivanja ovakve ili ekstremnije testne statistike pod pretpostavkom da je H₀ istinita).\n\n**Korak 5**: Donesite odluku. Ako je p < α, odbacite H₀. Ako je p ≥ α, ne možete odbaciti H₀.\n\nKrenimo korak po korak na jednostavnijem primjeru prije nego se vratimo na Instagram podatke.\n\n---\n\n## Jednouzorački t-test {#sec-one-sample}\n\nPočnimo s najjednostavnijim slučajem: imamo jedan uzorak i želimo testirati je li prosjek jednak nekoj zadanoj vrijednosti.\n\nSituacija: medijska kuća tvrdi da njihovi korisnici provode prosječno 3 minute čitajući članak. Vi ste skeptični i mislite da je stvarno vrijeme čitanja drugačije. Provedete mjerenje na uzorku članaka.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Simulirani podaci: stvarno prosječno vrijeme je 2.6 minuta\nvrijeme_citanja <- tibble(\n  clanak_id = 1:45,\n  minuta = round(rnorm(45, mean = 2.6, sd = 0.9), 1)\n)\n\n# Opisna statistika\nvrijeme_citanja |>\n  summarise(\n    n = n(),\n    M = round(mean(minuta), 2),\n    SD = round(sd(minuta), 2),\n    SE = round(sd(minuta) / sqrt(n()), 3)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      n     M    SD    SE\n  <int> <dbl> <dbl> <dbl>\n1    45  2.54  1.06 0.159\n```\n\n\n:::\n:::\n\n\nProsjek uzorka je ispod 3 minute. Ali je li dovoljno daleko od 3 da možemo odbaciti tvrdnju medijske kuće?\n\n### Testna statistika\n\nTestna statistika za jednouzorački t-test je:\n\n$$t = \\frac{\\bar{x} - \\mu_0}{SE} = \\frac{\\bar{x} - \\mu_0}{s / \\sqrt{n}}$$\n\nOvo mjeri koliko je prosjek uzorka udaljen od pretpostavljene vrijednosti, u jedinicama standardne pogreške.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_bar <- mean(vrijeme_citanja$minuta)\nmu_0 <- 3  # tvrdnja medijske kuće\ns <- sd(vrijeme_citanja$minuta)\nn <- nrow(vrijeme_citanja)\nse <- s / sqrt(n)\n\nt_stat <- (x_bar - mu_0) / se\n\ncat(\"x̄ =\", round(x_bar, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nx̄ = 2.54 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"μ₀ =\", mu_0, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nμ₀ = 3 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SE =\", round(se, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE = 0.159 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t =\", round(t_stat, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt = -2.911 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"df =\", n - 1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndf = 44 \n```\n\n\n:::\n:::\n\n\nTestna statistika t je negativna jer je prosjek uzorka manji od pretpostavljene vrijednosti. Apsolutna vrijednost |t| govori koliko standardnih pogrešaka je prosjek udaljen od μ₀. Što veći |t|, to jači dokaz protiv H₀.\n\n### P-vrijednost\n\n**P-vrijednost** je vjerojatnost dobivanja testne statistike jednake ili ekstremnije od opažene, pod pretpostavkom da je H₀ istinita. To nije vjerojatnost da je H₀ istinita. To nije vjerojatnost da smo pogriješili. To je vjerojatnost podataka (ili ekstremnijih) pod H₀.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dvosmjerni test: gledamo obje strane\np_value <- 2 * pt(abs(t_stat), df = n - 1, lower.tail = FALSE)\n\nx_vals <- seq(-5, 5, length.out = 300)\n\nt_data <- tibble(x = x_vals, density = dt(x_vals, df = n - 1))\n\nggplot(t_data, aes(x = x, y = density)) +\n  geom_line(linewidth = 1) +\n  geom_area(data = t_data |> filter(x <= -abs(t_stat)),\n            fill = \"firebrick\", alpha = 0.4) +\n  geom_area(data = t_data |> filter(x >= abs(t_stat)),\n            fill = \"firebrick\", alpha = 0.4) +\n  geom_vline(xintercept = c(-abs(t_stat), abs(t_stat)), \n             color = \"firebrick\", linetype = \"dashed\") +\n  annotate(\"text\", x = t_stat - 0.3, y = 0.05, \n           label = paste(\"t =\", round(t_stat, 2)), color = \"firebrick\", hjust = 1) +\n  labs(\n    title = \"P-vrijednost je crveno osjenčano područje\",\n    subtitle = paste0(\"Dvosmjerni test. p = \", round(p_value, 4), \n                      \". Ako je p < 0.05, odbacujemo H₀.\"),\n    x = \"t-vrijednost\",\n    y = \"Gustoća\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/p-vrijednost-vizualizacija-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"t-statistika:\", round(t_stat, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-statistika: -2.911 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P-vrijednost (dvosmjerni):\", round(p_value, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP-vrijednost (dvosmjerni): 0.0056 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"α = 0.05\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nα = 0.05\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Odluka:\", if_else(p_value < 0.05, \"Odbacujemo H₀\", \"Ne možemo odbaciti H₀\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOdluka: Odbacujemo H₀ \n```\n\n\n:::\n:::\n\n\n### `t.test()` radi sve automatski\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(vrijeme_citanja$minuta, mu = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  vrijeme_citanja$minuta\nt = -2.9114, df = 44, p-value = 0.005629\nalternative hypothesis: true mean is not equal to 3\n95 percent confidence interval:\n 2.217817 2.857739\nsample estimates:\nmean of x \n 2.537778 \n```\n\n\n:::\n:::\n\n\nFunkcija `t.test()` daje sve potrebne informacije: testnu statistiku, stupnjeve slobode, p-vrijednost, interval pouzdanosti i prosjek uzorka. P-vrijednost je ispod 0.05, što znači da imamo dovoljno dokaza da odbacimo tvrdnju medijske kuće da je prosječno vrijeme čitanja 3 minute.\n\n::: {.callout-tip}\n## Veza između CI i testiranja hipoteza\n\nPogledajte 95% CI iz gornjeg rezultata. Ne sadrži vrijednost 3. Ovo nije slučajnost: odbacivanje H₀ na razini α = 0.05 je ekvivalentno tome da 95% CI ne sadrži testiranu vrijednost μ₀. Ovo su dva načina gledanja na isti problem.\n:::\n\n---\n\n## Dvosmjerni vs jednosmjerni test {#sec-smjerovi}\n\nU prethodnom primjeru koristili smo **dvosmjerni test** (two-tailed): testirali smo je li prosjek različit od 3, u bilo kojem smjeru. Hipoteze su bile H₀: μ = 3 vs H₁: μ ≠ 3.\n\nPonekad unaprijed znamo smjer. Ako Instagram tim očekuje da su carousel objave BOLJE (ne samo različite), možemo koristiti **jednosmjerni test** (one-tailed): H₀: μ_carousel ≤ μ_single vs H₁: μ_carousel > μ_single.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Jednosmjerni: je li prosjek MANJI od 3?\nt.test(vrijeme_citanja$minuta, mu = 3, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  vrijeme_citanja$minuta\nt = -2.9114, df = 44, p-value = 0.002814\nalternative hypothesis: true mean is less than 3\n95 percent confidence interval:\n     -Inf 2.804532\nsample estimates:\nmean of x \n 2.537778 \n```\n\n\n:::\n:::\n\n\nP-vrijednost jednosmjernog testa je točno pola dvosmjernog (kad je smjer u skladu s podacima). Jednosmjerni test je \"osjetljiviji\" u tom smjeru, ali potpuno slijep za razliku u suprotnom smjeru.\n\n::: {.callout-warning}\n## Upozorenje\n\nJednosmjerni test koristite SAMO ako ste smjer hipoteze odredili PRIJE nego ste pogledali podatke. Ako pogledate podatke, vidite da je prosjek manji od 3 i onda odlučite testirati \"je li manji\", to je pristranost istraživača. Kad ste u sumnji, koristite dvosmjerni test. Većina publiciranih istraživanja koristi dvosmjerne testove.\n:::\n\n---\n\n## Dvouzorački t-test: Instagram A/B test {#sec-two-sample}\n\nSada se vraćamo na naš motivacijski primjer. Želimo testirati razlikuje li se angažman između carousel i single image objava. Ovo zahtijeva **dvouzorački t-test** (two-sample t-test) jer uspoređujemo prosjeke dviju nezavisnih skupina.\n\n$$H_0: \\mu_{carousel} = \\mu_{single}$$\n$$H_1: \\mu_{carousel} \\neq \\mu_{single}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nig |>\n  ggplot(aes(x = engagement_rate * 100, fill = format)) +\n  geom_density(alpha = 0.5) +\n  geom_vline(data = ig |> group_by(format) |> summarise(M = mean(engagement_rate) * 100),\n             aes(xintercept = M, color = format), linewidth = 1, linetype = \"dashed\") +\n  scale_fill_manual(values = c(\"carousel\" = \"#2a9d8f\", \"single_image\" = \"#e76f51\")) +\n  scale_color_manual(values = c(\"carousel\" = \"#2a9d8f\", \"single_image\" = \"#e76f51\")) +\n  labs(\n    title = \"Distribucija angažmana po formatu objave\",\n    subtitle = \"Isprekidane linije = prosjeci. Distribucije se preklapaju ali su centri različiti.\",\n    x = \"Engagement rate (%)\",\n    y = \"Gustoća\",\n    fill = \"Format\", color = \"Format\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/two-sample-vizualizacija-1.png){width=768}\n:::\n:::\n\n\nDistribucije se preklapaju, ali carousel objave su pomaknute udesno. Testna statistika za dvouzorački t-test mjeri razliku prosjeka u jedinicama zajedničke standardne pogreške:\n\n$$t = \\frac{\\bar{x}_1 - \\bar{x}_2}{SE_{razlika}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncarousel <- ig |> filter(format == \"carousel\") |> pull(engagement_rate)\nsingle <- ig |> filter(format == \"single_image\") |> pull(engagement_rate)\n\nrezultat <- t.test(carousel, single)\nrezultat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  carousel and single\nt = 14.942, df = 461.55, p-value < 2.2e-16\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n 0.02276184 0.02965581\nsample estimates:\n mean of x  mean of y \n0.10117966 0.07497083 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Razlika prosjeka:\", round((mean(carousel) - mean(single)) * 100, 2), \"postotnih bodova\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRazlika prosjeka: 2.62 postotnih bodova\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t-statistika:\", round(rezultat$statistic, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-statistika: 14.94 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P-vrijednost:\", format(rezultat$p.value, scientific = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP-vrijednost: 1.856828e-41 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI za razliku: [\", round(rezultat$conf.int[1] * 100, 2), \",\", \n    round(rezultat$conf.int[2] * 100, 2), \"] postotnih bodova\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI za razliku: [ 2.28 , 2.97 ] postotnih bodova\n```\n\n\n:::\n:::\n\n\nP-vrijednost je iznimno mala (mnogo manja od 0.05). Imamo snažne dokaze da se angažman razlikuje između dva formata. Carousel objave imaju statistički značajno viši angažman.\n\n### Welchov t-test\n\nR po defaultu koristi **Welchov t-test** koji ne pretpostavlja jednake varijance u dvjema skupinama. Ovo je gotovo uvijek bolja opcija od klasičnog Studentovog t-testa (koji pretpostavlja jednake varijance). Welchov test je robusniji i gubi malo snage čak i kad su varijance jednake.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Welchov (default)\nwelch <- t.test(carousel, single, var.equal = FALSE)\n\n# Studentov (pretpostavlja jednake varijance)\nstudent <- t.test(carousel, single, var.equal = TRUE)\n\ntibble(\n  test = c(\"Welch (default)\", \"Student (var.equal=TRUE)\"),\n  t = round(c(welch$statistic, student$statistic), 3),\n  df = round(c(welch$parameter, student$parameter), 1),\n  p = format(c(welch$p.value, student$p.value), scientific = TRUE, digits = 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  test                         t    df p       \n  <chr>                    <dbl> <dbl> <chr>   \n1 Welch (default)           14.9  462. 1.86e-41\n2 Student (var.equal=TRUE)  15.1  498  1.27e-42\n```\n\n\n:::\n:::\n\n\nRezultati su vrlo slični u ovom slučaju. Ali Welchov test ima nerunde stupnjeve slobode (jer ih prilagođava za razliku u varijancama). Koristite Welchov test kao default jer ne zahtijeva dodatnu pretpostavku.\n\n---\n\n## Simulacija: što znači p-vrijednost? {#sec-simulacija-p}\n\nMnogi studenti (i istraživači) krivo razumiju p-vrijednost. Simulacija pomaže izgraditi ispravnu intuiciju.\n\nPretpostavimo da H₀ JEST istinita: carousel i single image imaju identičan angažman. Ako mnogo puta uzorkujemo i testiramo, koliko ćemo često dobiti p < 0.05?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Simulacija: H₀ je ISTINITA (isti prosjek za obje grupe)\nsim_p <- map_dbl(1:10000, \\(i) {\n  grupa_a <- rnorm(100, mean = 0.08, sd = 0.02)\n  grupa_b <- rnorm(100, mean = 0.08, sd = 0.02)  # ISTI prosjek!\n  t.test(grupa_a, grupa_b)$p.value\n})\n\ncat(\"H₀ je ISTINITA. Od 10 000 testova:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nH₀ je ISTINITA. Od 10 000 testova:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p < 0.05:\", sum(sim_p < 0.05), \"(\", round(mean(sim_p < 0.05) * 100, 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np < 0.05: 497 ( 5 %)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p < 0.01:\", sum(sim_p < 0.01), \"(\", round(mean(sim_p < 0.01) * 100, 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np < 0.01: 79 ( 0.8 %)\n```\n\n\n:::\n\n```{.r .cell-code}\ntibble(p = sim_p) |>\n  ggplot(aes(x = p)) +\n  geom_histogram(fill = \"steelblue\", color = \"white\", bins = 50) +\n  geom_vline(xintercept = 0.05, color = \"firebrick\", linewidth = 1, linetype = \"dashed\") +\n  annotate(\"text\", x = 0.06, y = 400, label = \"α = 0.05\", color = \"firebrick\", hjust = 0) +\n  labs(\n    title = \"Distribucija p-vrijednosti kad je H₀ ISTINITA\",\n    subtitle = \"P-vrijednosti su uniformno raspoređene. ~5% pada ispod 0.05.\",\n    x = \"P-vrijednost\",\n    y = \"Frekvencija\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/simulacija-h0-istinita-1.png){width=768}\n:::\n:::\n\n\nKad je H₀ istinita, p-vrijednosti su uniformno raspoređene između 0 i 1. Točno 5% pada ispod 0.05 (po definiciji α). Ovo znači da ćemo u 5% slučajeva pogrešno odbaciti H₀ čak i kad je istinita. Ovo je **greška tipa I** (false positive, lažno pozitivni rezultat).\n\n### Kad je H₁ istinita\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Simulacija: H₁ je ISTINITA (razlika postoji)\nsim_p_h1 <- map_dbl(1:10000, \\(i) {\n  grupa_a <- rnorm(100, mean = 0.10, sd = 0.02)\n  grupa_b <- rnorm(100, mean = 0.08, sd = 0.02)  # RAZLIČIT prosjek\n  t.test(grupa_a, grupa_b)$p.value\n})\n\ncat(\"H₁ je ISTINITA (razlika = 0.02). Od 10 000 testova:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nH₁ je ISTINITA (razlika = 0.02). Od 10 000 testova:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p < 0.05:\", sum(sim_p_h1 < 0.05), \"(\", round(mean(sim_p_h1 < 0.05) * 100, 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np < 0.05: 10000 ( 100 %)\n```\n\n\n:::\n\n```{.r .cell-code}\ntibble(p = sim_p_h1) |>\n  ggplot(aes(x = p)) +\n  geom_histogram(fill = \"#2a9d8f\", color = \"white\", bins = 50) +\n  geom_vline(xintercept = 0.05, color = \"firebrick\", linewidth = 1, linetype = \"dashed\") +\n  labs(\n    title = \"Distribucija p-vrijednosti kad je H₁ ISTINITA\",\n    subtitle = \"Većina p-vrijednosti je blizu nule. Test je imao snagu detektirati razliku.\",\n    x = \"P-vrijednost\",\n    y = \"Frekvencija\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/simulacija-h1-istinita-1.png){width=768}\n:::\n:::\n\n\nKad razlika stvarno postoji, p-vrijednosti su koncentrirane blizu nule. Većina testova uspješno detektira razliku (p < 0.05). Ali ne svi. Postotak testova koji uspješno detektiraju pravu razliku naziva se **statistička snaga** (power). Testovi koji ne detektiraju pravu razliku (p ≥ 0.05 iako razlika postoji) čine **grešku tipa II** (false negative, lažno negativni rezultat).\n\n---\n\n## Greška tipa I i greška tipa II {#sec-greske}\n\nPostoje četiri moguća ishoda testiranja hipoteza, ovisno o tome je li H₀ stvarno istinita i kakvu smo odluku donijeli.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntribble(\n  ~` `, ~`H₀ je istinita`, ~`H₀ je lažna`,\n  \"Ne odbacujemo H₀\", \"✅ Ispravna odluka (1 - α)\", \"❌ Greška tipa II (β)\",\n  \"Odbacujemo H₀\", \"❌ Greška tipa I (α)\", \"✅ Ispravna odluka (snaga = 1 - β)\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  ` `              `H₀ je istinita`           `H₀ je lažna`                     \n  <chr>            <chr>                      <chr>                             \n1 Ne odbacujemo H₀ ✅ Ispravna odluka (1 - α) ❌ Greška tipa II (β)             \n2 Odbacujemo H₀    ❌ Greška tipa I (α)       ✅ Ispravna odluka (snaga = 1 - β)\n```\n\n\n:::\n:::\n\n\n**Greška tipa I** (α): Odbacimo H₀ iako je istinita. Zaključimo da razlika postoji kad je zapravo nema. Kontroliramo je postavljanjem α (obično 0.05). Analogija sa suđenjem: osuditi nevinu osobu.\n\n**Greška tipa II** (β): Ne odbacimo H₀ iako je lažna. Propustimo pravu razliku. Ovisi o veličini uzorka, veličini učinka i α. Analogija sa suđenjem: osloboditi krivca.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- seq(-4, 8, length.out = 500)\nh0 <- dnorm(x, mean = 0, sd = 1)\nh1 <- dnorm(x, mean = 3, sd = 1)\n\ncrit <- qnorm(0.975)\n\nerror_data <- tibble(x = x, H0 = h0, H1 = h1)\n\nggplot(error_data, aes(x = x)) +\n  # H0 distribucija\n  geom_line(aes(y = H0), color = \"steelblue\", linewidth = 1) +\n  geom_area(data = error_data |> filter(x >= crit), aes(y = H0),\n            fill = \"firebrick\", alpha = 0.3) +\n  # H1 distribucija\n  geom_line(aes(y = H1), color = \"#2a9d8f\", linewidth = 1) +\n  geom_area(data = error_data |> filter(x < crit), aes(y = H1),\n            fill = \"#e9c46a\", alpha = 0.3) +\n  # Kritična vrijednost\n  geom_vline(xintercept = crit, color = \"grey30\", linewidth = 0.8, linetype = \"dashed\") +\n  annotate(\"text\", x = 0, y = 0.42, label = \"H₀ distribucija\", color = \"steelblue\", fontface = \"bold\") +\n  annotate(\"text\", x = 3, y = 0.42, label = \"H₁ distribucija\", color = \"#2a9d8f\", fontface = \"bold\") +\n  annotate(\"text\", x = 2.8, y = 0.12, label = \"Greška\\ntipa I (α)\", color = \"firebrick\") +\n  annotate(\"text\", x = 0.5, y = 0.06, label = \"Greška\\ntipa II (β)\", color = \"#c77f00\") +\n  annotate(\"text\", x = crit, y = -0.02, label = \"Kritična\\nvrijednost\", hjust = 0.5) +\n  labs(\n    title = \"Vizualizacija grešaka tipa I i tipa II\",\n    subtitle = \"Crveno = lažno pozitivno. Žuto = lažno negativno. Ne možemo smanjiti oboje istovremeno.\",\n    x = \"Testna statistika\",\n    y = \"Gustoća\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/greske-vizualizacija-1.png){width=960}\n:::\n:::\n\n\nOvaj graf pokazuje ključan kompromis. Ako pomaknemo kritičnu vrijednost udesno (strožiji α), smanjujemo crveno područje (manje lažno pozitivnih) ali povećavamo žuto područje (više lažno negativnih). Jedini način da smanjimo oboje istovremeno je povećati uzorak (što razdvaja dvije distribucije) ili imati veći učinak.\n\n::: {.callout-important}\n## Važna napomena\n\n\"Ne možemo odbaciti H₀\" nije isto što i \"H₀ je istinita.\" Odsutnost dokaza nije dokaz odsutnosti. Možda razlika postoji ali je naš uzorak premalen da je detektira. Zato nikad ne kažemo \"prihvaćamo H₀\" nego \"ne možemo odbaciti H₀ na temelju dostupnih podataka.\"\n:::\n\n---\n\n## P-vrijednost: što jest, a što nije {#sec-p-vrijednost}\n\nP-vrijednost je jedan od najčešće korištenih ali i najčešće pogrešno interpretiranih koncepata u statistici. Razjasnimo.\n\n**P-vrijednost JEST**: Vjerojatnost dobivanja testne statistike jednake ili ekstremnije od opažene, pod pretpostavkom da je H₀ istinita. Drugim riječima: koliko bi bili iznenađeni ovakvim podacima kad H₀ ne bi bila istinita?\n\n**P-vrijednost NIJE**:\n\nP-vrijednost NIJE vjerojatnost da je H₀ istinita. Ne možemo reći \"postoji samo 3% šanse da nema razlike.\" P-vrijednost ne govori ništa o vjerojatnosti hipoteza.\n\nP-vrijednost NIJE vjerojatnost da smo pogriješili. Mala p-vrijednost znači da su podaci neobični pod H₀. Ne znači da smo sigurno u pravu.\n\nP-vrijednost NIJE mjera veličine učinka. p = 0.001 ne znači da je učinak velik. Velik uzorak može proizvesti malu p-vrijednost za trivijalno malu razliku.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Mali uzorak, velik učinak\nmali_uzorak <- t.test(rnorm(20, 10.5, 2), mu = 10)\n\n# Velik uzorak, sićušan učinak\nvelik_uzorak <- t.test(rnorm(10000, 10.02, 2), mu = 10)\n\ntibble(\n  scenarij = c(\"Mali uzorak (n=20), velik učinak\", \"Velik uzorak (n=10000), sićušan učinak\"),\n  n = c(20, 10000),\n  razlika = c(\"0.5 bodova\", \"0.02 boda\"),\n  p_vrijednost = c(round(mali_uzorak$p.value, 4), round(velik_uzorak$p.value, 4)),\n  znacajno = c(mali_uzorak$p.value < 0.05, velik_uzorak$p.value < 0.05)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  scenarij                                   n razlika    p_vrijednost znacajno\n  <chr>                                  <dbl> <chr>             <dbl> <lgl>   \n1 Mali uzorak (n=20), velik učinak          20 0.5 bodova        0.149 FALSE   \n2 Velik uzorak (n=10000), sićušan učinak 10000 0.02 boda         0.843 FALSE   \n```\n\n\n:::\n:::\n\n\nS 10 000 opažanja, razlika od 0.02 boda (praktički beznačajna) je statistički značajna. S 20 opažanja, razlika od 0.5 bodova (potencijalno važna) nije statistički značajna. Ovo pokazuje zašto p-vrijednost sama nije dovoljna. Uvijek trebamo i mjeru veličine učinka.\n\n---\n\n\n::: {.callout-note}\n## Podsjetnik\n\nU prvom dijelu naučili smo logiku testiranja hipoteza, formuliranje H₀ i H₁, jednouzorački i dvouzorački t-test, p-vrijednost i greške tipa I i II. U ovom dijelu prelazimo na pitanje koje je jednako važno kao statistička značajnost: koliko je učinak zapravo velik?\n:::\n\n## Veličina učinka: Cohenov d {#sec-cohen-d}\n\nP-vrijednost odgovara na pitanje \"postoji li učinak?\" ali ne govori koliko je učinak velik. Za to nam treba mjera **veličine učinka** (effect size).\n\nNajčešća mjera za razliku dvaju prosjeka je **Cohenov d**, koji izražava razliku u jedinicama zajedničke standardne devijacije:\n\n$$d = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_{pooled}}$$\n\ngdje je $s_{pooled}$ zajednička (pooled) standardna devijacija dviju grupa.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nig <- read_csv(\"../resources/datasets/instagram_ab_test.csv\")\n\ncarousel <- ig |> filter(format == \"carousel\") |> pull(engagement_rate)\nsingle <- ig |> filter(format == \"single_image\") |> pull(engagement_rate)\n\n# Ručni izračun\nn1 <- length(carousel)\nn2 <- length(single)\ns_pooled <- sqrt(((n1 - 1) * sd(carousel)^2 + (n2 - 1) * sd(single)^2) / (n1 + n2 - 2))\nd <- (mean(carousel) - mean(single)) / s_pooled\n\ncat(\"Razlika prosjeka:\", round((mean(carousel) - mean(single)) * 100, 2), \"postotnih bodova\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRazlika prosjeka: 2.62 postotnih bodova\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Pooled SD:\", round(s_pooled * 100, 2), \"postotnih bodova\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPooled SD: 1.94 postotnih bodova\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Cohenov d:\", round(d, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohenov d: 1.351 \n```\n\n\n:::\n:::\n\n\n### Interpretacija Cohenovog d\n\nCohen (1988) je predložio smjernice za interpretaciju:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntribble(\n  ~d, ~interpretacija, ~primjer,\n  \"0.2\", \"Mali učinak\", \"Jedva primjetna razlika u praksi\",\n  \"0.5\", \"Srednji učinak\", \"Razlika vidljiva prostim okom\",\n  \"0.8\", \"Veliki učinak\", \"Razlika očita i praktično važna\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  d     interpretacija primjer                         \n  <chr> <chr>          <chr>                           \n1 0.2   Mali učinak    Jedva primjetna razlika u praksi\n2 0.5   Srednji učinak Razlika vidljiva prostim okom   \n3 0.8   Veliki učinak  Razlika očita i praktično važna \n```\n\n\n:::\n:::\n\n\nNaš d = 1.35 je velik učinak. Carousel objave generiraju značajno viši angažman, i to u praktično važnoj mjeri. Ovo je informacija koju p-vrijednost sama ne daje.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Vizualizacija: što znači d = 0.2, 0.5, 0.8, 1.3\nd_values <- c(0.2, 0.5, 0.8, round(d, 2))\nd_labels <- c(\"d = 0.2 (mali)\", \"d = 0.5 (srednji)\", \"d = 0.8 (veliki)\", \n              paste0(\"d = \", round(d, 2), \" (naši podaci)\"))\n\nx <- seq(-4, 6, length.out = 300)\n\nd_viz <- map_df(seq_along(d_values), \\(i) {\n  tibble(\n    panel = d_labels[i],\n    x = x,\n    Grupa_A = dnorm(x, 0, 1),\n    Grupa_B = dnorm(x, d_values[i], 1)\n  ) |>\n    pivot_longer(c(Grupa_A, Grupa_B), names_to = \"grupa\", values_to = \"gustoca\")\n}) |>\n  mutate(panel = factor(panel, levels = d_labels))\n\nd_viz |>\n  ggplot(aes(x = x, y = gustoca, fill = grupa)) +\n  geom_area(alpha = 0.4, position = \"identity\") +\n  facet_wrap(~panel, ncol = 2) +\n  scale_fill_manual(values = c(\"Grupa_A\" = \"steelblue\", \"Grupa_B\" = \"#2a9d8f\"),\n                    labels = c(\"Grupa A\", \"Grupa B\")) +\n  labs(\n    title = \"Što znači Cohenov d?\",\n    subtitle = \"Veći d = manje preklapanja između distribucija = očitija razlika\",\n    x = \"Vrijednost\", y = \"Gustoća\", fill = NULL\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/cohen-d-vizualizacija-1.png){width=960}\n:::\n:::\n\n\nS d = 0.2, distribucije se gotovo potpuno preklapaju i razliku je teško primijetiti. S d = 0.8, razdvajanje je očito. Naš d ≈ 1.3 pokazuje vrlo jasno razdvajanje: carousel i single image su očigledno različite kategorije po angažmanu.\n\n::: {.callout-tip}\n## Praktični savjet\n\nUvijek izvještavajte veličinu učinka uz p-vrijednost. Umjesto \"razlika je statistički značajna (p < 0.001)\", napišite \"carousel objave imaju značajno viši angažman od single image objava (razlika = 2.6 postotnih bodova, d = 1.34, p < 0.001).\" Ovo daje čitatelju informaciju i o postojanju i o veličini razlike.\n:::\n\n---\n\n## Statistička snaga {#sec-snaga}\n\n**Statistička snaga** (power) je vjerojatnost da test odbaci H₀ kad je H₁ istinita. Drugim riječima: koliko je vjerojatno da ćemo detektirati pravu razliku ako ona postoji?\n\nSnaga ovisi o četiri faktora: veličini učinka (veći učinak je lakše detektirati), veličini uzorka (više podataka daje veću snagu), razini značajnosti α (veći α daje veću snagu ali više lažno pozitivnih), i varijabilnosti podataka (manja varijabilnost daje veću snagu).\n\nKonvencija je da snaga treba biti barem 0.80 (80%). Ovo znači da ako razlika postoji, želimo je detektirati barem u 8 od 10 pokušaja.\n\n### Analiza snage: koliki uzorak trebam?\n\nNajčešća primjena analize snage je planiranje istraživanja: koliki uzorak mi treba da detektiram očekivanu veličinu učinka s 80% snagom?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# power.t.test() za dvouzorački test\n# Koliki uzorak trebam za srednji učinak (d = 0.5)?\npower.t.test(\n  delta = 0.5,       # očekivana razlika u SD jedinicama (Cohenov d)\n  sd = 1,            # standardizirano na 1\n  sig.level = 0.05,  # α\n  power = 0.80,      # željena snaga\n  type = \"two.sample\",\n  alternative = \"two.sided\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 63.76576\n          delta = 0.5\n             sd = 1\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\nZa detektiranje srednjeg učinka (d = 0.5) s 80% snagom potrebno je otprilike 64 ispitanika po grupi (ukupno 128). Pogledajmo kako se potreban uzorak mijenja s veličinom učinka.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_values <- c(0.2, 0.3, 0.5, 0.8, 1.0, 1.3)\n\npower_tablica <- map_df(d_values, \\(d_val) {\n  rez <- power.t.test(delta = d_val, sd = 1, sig.level = 0.05, power = 0.80,\n                      type = \"two.sample\", alternative = \"two.sided\")\n  tibble(\n    cohenov_d = d_val,\n    n_po_grupi = ceiling(rez$n),\n    ukupno_n = ceiling(rez$n) * 2\n  )\n})\n\npower_tablica\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  cohenov_d n_po_grupi ukupno_n\n      <dbl>      <dbl>    <dbl>\n1       0.2        394      788\n2       0.3        176      352\n3       0.5         64      128\n4       0.8         26       52\n5       1           17       34\n6       1.3         11       22\n```\n\n\n:::\n:::\n\n\nZa mali učinak (d = 0.2) trebate čak 394 ispitanika po grupi. Za veliki učinak (d = 0.8) trebate samo 26 po grupi. Ovo je razlog zašto je planiranje unaprijed ključno: morate imati realistična očekivanja o veličini učinka da biste znali koliko podataka trebate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Krivulja snage: kako snaga raste s veličinom uzorka\nn_range <- seq(10, 300, by = 5)\n\npower_curves <- map_df(c(0.2, 0.5, 0.8), \\(d_val) {\n  map_df(n_range, \\(n_val) {\n    p <- power.t.test(n = n_val, delta = d_val, sd = 1, sig.level = 0.05,\n                      type = \"two.sample\", alternative = \"two.sided\")$power\n    tibble(n = n_val, power = p, d = paste(\"d =\", d_val))\n  })\n})\n\npower_curves |>\n  ggplot(aes(x = n, y = power, color = d)) +\n  geom_line(linewidth = 1.2) +\n  geom_hline(yintercept = 0.80, linetype = \"dashed\", color = \"grey50\") +\n  annotate(\"text\", x = 290, y = 0.82, label = \"Snaga = 0.80\", color = \"grey50\", hjust = 1) +\n  scale_y_continuous(labels = scales::label_percent(), limits = c(0, 1)) +\n  scale_color_manual(values = c(\"d = 0.2\" = \"#e76f51\", \"d = 0.5\" = \"#e9c46a\", \"d = 0.8\" = \"#2a9d8f\")) +\n  labs(\n    title = \"Krivulje snage za dvouzorački t-test\",\n    subtitle = \"Veći učinak ili veći uzorak = veća snaga detektiranja razlike\",\n    x = \"Veličina uzorka (po grupi)\",\n    y = \"Statistička snaga\",\n    color = NULL\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/power-krivulja-1.png){width=864}\n:::\n:::\n\n\nZa mali učinak (d = 0.2, crvena), snaga sporo raste i ni s n = 300 po grupi ne dostiže 100%. Za veliki učinak (d = 0.8, zelena), snaga brzo raste i s n = 30 po grupi je već blizu 80%.\n\n### Kolika je snaga našeg Instagram testa?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Kolika je snaga našeg testa s d ≈ 1.34 i n ≈ 250 po grupi?\npower_ig <- power.t.test(\n  n = min(n1, n2),\n  delta = d,\n  sd = 1,\n  sig.level = 0.05,\n  type = \"two.sample\",\n  alternative = \"two.sided\"\n)\n\ncat(\"Snaga našeg testa:\", round(power_ig$power, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSnaga našeg testa: 1 \n```\n\n\n:::\n:::\n\n\nSnaga je gotovo 1.0 (100%). S ovakvom veličinom učinka i ovako velikim uzorkom, gotovo nema šanse da bismo propustili ovu razliku. Test je bio više nego adekvatno snažan. U praksi, mogli smo detektirati ovu razliku s mnogo manje podataka.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Koliki minimalni uzorak bi bio dovoljan?\nmin_n <- power.t.test(\n  delta = d,\n  sd = 1,\n  sig.level = 0.05,\n  power = 0.80,\n  type = \"two.sample\"\n)\n\ncat(\"Minimalni n po grupi za 80% snagu:\", ceiling(min_n$n), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMinimalni n po grupi za 80% snagu: 10 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mi smo imali:\", min(n1, n2), \"po grupi\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMi smo imali: 236 po grupi\n```\n\n\n:::\n:::\n\n\n---\n\n## Upareni t-test {#sec-paired}\n\nDosad smo uspoređivali dvije **nezavisne** skupine (carousel vs single image su različite objave). Ali ponekad mjerimo istu jedinicu u dva uvjeta. Na primjer: angažman istih pratitelja prije i poslije redizajna profila, ili rating istih članaka od strane dva različita urednika.\n\nKad su opažanja u parovima, koristimo **upareni t-test** (paired t-test). Umjesto da uspoređujemo dva prosjeka, računamo razliku za svaki par i testiramo je li prosjek razlika različit od nule.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Simulacija: 30 članaka, svaki ocjenjen od 2 urednika\nurednicki_rating <- tibble(\n  clanak_id = 1:30,\n  urednik_A = round(rnorm(30, mean = 6.5, sd = 1.2), 1),\n  urednik_B = round(urednik_A + rnorm(30, mean = 0.5, sd = 0.8), 1)\n)\n\n# Urednik B ocjenjuje sustavno više\nurednicki_rating <- urednicki_rating |>\n  mutate(razlika = urednik_B - urednik_A)\n\nurednicki_rating |>\n  summarise(\n    M_A = round(mean(urednik_A), 2),\n    M_B = round(mean(urednik_B), 2),\n    M_razlika = round(mean(razlika), 2),\n    SD_razlika = round(sd(razlika), 2)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n    M_A   M_B M_razlika SD_razlika\n  <dbl> <dbl>     <dbl>      <dbl>\n1  6.59  6.99      0.41       0.84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Upareni t-test\nt.test(urednicki_rating$urednik_B, urednicki_rating$urednik_A, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  urednicki_rating$urednik_B and urednicki_rating$urednik_A\nt = 2.648, df = 29, p-value = 0.01296\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.09257456 0.72075877\nsample estimates:\nmean difference \n      0.4066667 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Usporedba: upareni vs nepareni test na istim podacima\npaired_p <- t.test(urednicki_rating$urednik_B, urednicki_rating$urednik_A, paired = TRUE)$p.value\nunpaired_p <- t.test(urednicki_rating$urednik_B, urednicki_rating$urednik_A, paired = FALSE)$p.value\n\ncat(\"Upareni test p-vrijednost:  \", round(paired_p, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUpareni test p-vrijednost:   0.01296 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Nepareni test p-vrijednost: \", round(unpaired_p, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNepareni test p-vrijednost:  0.30785 \n```\n\n\n:::\n:::\n\n\nUpareni test je osjetljiviji (manja p-vrijednost) jer uklanja varijabilnost između parova. Neki članci su općenito bolji, neki lošiji. Kad to kontroliramo (parenjem), preostaje samo varijabilnost u razlici između dva urednika, što je puno manja.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurednicki_rating |>\n  ggplot() +\n  geom_segment(aes(x = urednik_A, xend = urednik_B, y = clanak_id, yend = clanak_id),\n               color = \"grey70\", linewidth = 0.5) +\n  geom_point(aes(x = urednik_A, y = clanak_id), color = \"steelblue\", size = 2) +\n  geom_point(aes(x = urednik_B, y = clanak_id), color = \"#e76f51\", size = 2) +\n  annotate(\"text\", x = 3.5, y = 31, label = \"Urednik A\", color = \"steelblue\", fontface = \"bold\") +\n  annotate(\"text\", x = 10, y = 31, label = \"Urednik B\", color = \"#e76f51\", fontface = \"bold\") +\n  labs(\n    title = \"Uredničke ocjene istih članaka\",\n    subtitle = \"Svaka linija je jedan članak. Urednik B sustavno ocjenjuje više.\",\n    x = \"Ocjena (1-10)\",\n    y = \"Članak ID\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/paired-vizualizacija-1.png){width=864}\n:::\n:::\n\n\n::: {.callout-important}\n## Kada koristiti koji test?\n\n**Nepareni (nezavisni) t-test**: Dvije različite skupine ispitanika. Primjeri: muškarci vs žene, kontrolna vs eksperimentalna grupa, carousel vs single image.\n\n**Upareni t-test**: Ista jedinica mjerena dva puta. Primjeri: prije i poslije intervencije, isti sadržaj na dva kanala, isti ispitanik u dva uvjeta. Ključno pitanje: možete li smisleno spariti opažanja? Ako da, koristite upareni test.\n:::\n\n---\n\n## Statistička vs praktična značajnost {#sec-prakticna}\n\nStatistička značajnost (p < 0.05) govori da razlika vjerojatno nije slučajnost. Ali ne govori je li razlika dovoljno velika da je važna u praksi. Ovo razlikovanje je ključno za donošenje odluka.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Scenarij 1: Statistički značajno ali praktički beznačajno\n# Novi dizajn naslovnice povećava CTR s 2.00% na 2.05%\nn_velik <- 50000\nctr_stari <- rbinom(n_velik, 1, 0.0200)\nctr_novi <- rbinom(n_velik, 1, 0.0205)\n\ntest1 <- t.test(ctr_novi, ctr_stari)\n\ncat(\"=== Scenarij 1: Velik uzorak, sićušna razlika ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Scenarij 1: Velik uzorak, sićušna razlika ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Razlika CTR:\", round((mean(ctr_novi) - mean(ctr_stari)) * 100, 3), \"postotnih bodova\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRazlika CTR: -0.014 postotnih bodova\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P-vrijednost:\", round(test1$p.value, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP-vrijednost: 0.8762 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Statistički značajno:\", test1$p.value < 0.05, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStatistički značajno: FALSE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Isplati li se redizajn? Vjerojatno ne.\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIsplati li se redizajn? Vjerojatno ne.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Scenarij 2: Statistički neznačajno ali potencijalno praktički važno\n# Novi format povećava CTR s 2.0% na 3.5% ali mali uzorak\nn_mali <- 80\nctr_stari2 <- rbinom(n_mali, 1, 0.020)\nctr_novi2 <- rbinom(n_mali, 1, 0.035)\n\ntest2 <- t.test(ctr_novi2, ctr_stari2)\n\ncat(\"=== Scenarij 2: Mali uzorak, veća razlika ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Scenarij 2: Mali uzorak, veća razlika ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Razlika CTR:\", round((mean(ctr_novi2) - mean(ctr_stari2)) * 100, 2), \"postotnih bodova\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRazlika CTR: 0 postotnih bodova\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P-vrijednost:\", round(test2$p.value, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP-vrijednost: 1 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Statistički značajno:\", test2$p.value < 0.05, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStatistički značajno: FALSE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Zaslužuje li daljnje istraživanje? Vjerojatno da.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nZaslužuje li daljnje istraživanje? Vjerojatno da.\n```\n\n\n:::\n:::\n\n\nDonošenje odluka na temelju samo p-vrijednosti je nepotpuno. Morate uzeti u obzir veličinu učinka, praktične posljedice (trošak redizajna vs dobitak od povećanog CTR-a), interval pouzdanosti (koliki raspon razlika je konzistentan s podacima) i kontekst (kolika je razlika \"dovoljno velika\" u vašoj industriji).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntribble(\n  ~` `, ~`Praktički važno`, ~`Praktički nevažno`,\n  \"Statistički značajno (p < 0.05)\", \"✅ Djeluj! Razlika postoji i važna je.\", \"⚠️ Razlika postoji ali je premala da bi se isplatila.\",\n  \"Statistički neznačajno (p ≥ 0.05)\", \"🔍 Možda nemaš dovoljno podataka. Povećaj uzorak.\", \"✅ Nema učinka i to je u redu.\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  ` `                               `Praktički važno`        `Praktički nevažno`\n  <chr>                             <chr>                    <chr>              \n1 Statistički značajno (p < 0.05)   \"✅ Djeluj! Razlika post… ⚠️ Razlika postoji …\n2 Statistički neznačajno (p ≥ 0.05) \"\\U0001f50d Možda nemaš… ✅ Nema učinka i to…\n```\n\n\n:::\n:::\n\n\n---\n\n## Potpuna analiza: Instagram A/B test izvještaj {#sec-analiza}\n\nSpojimo sve u koherentan izvještaj za urednicu. Slijedimo strukturu: opisna statistika, vizualizacija, statistički test, veličina učinka, podanalize, zaključak s preporukom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Korak 1: Opisna statistika po formatu\nig |>\n  group_by(format) |>\n  summarise(\n    n = n(),\n    M_engagement = round(mean(engagement_rate) * 100, 2),\n    SD_engagement = round(sd(engagement_rate) * 100, 2),\n    M_likes = round(mean(likes), 0),\n    M_comments = round(mean(comments), 0),\n    M_shares = round(mean(shares), 0),\n    M_saves = round(mean(saves), 0),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 8\n  format        n M_engagement SD_engagement M_likes M_comments M_shares M_saves\n  <chr>     <int>        <dbl>         <dbl>   <dbl>      <dbl>    <dbl>   <dbl>\n1 carousel    236         10.1          2.11     180         36       25      42\n2 single_i…   264          7.5          1.77     149         24       20      30\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nig |>\n  ggplot(aes(x = format, y = engagement_rate * 100, fill = format)) +\n  geom_boxplot(alpha = 0.7, outlier.shape = NA) +\n  geom_jitter(width = 0.15, alpha = 0.15, size = 1) +\n  scale_fill_manual(values = c(\"carousel\" = \"#2a9d8f\", \"single_image\" = \"#e76f51\")) +\n  labs(\n    title = \"Engagement rate po formatu objave\",\n    subtitle = \"Carousel objave imaju vidljivo viši angažman\",\n    x = NULL,\n    y = \"Engagement rate (%)\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/analiza-boxplot-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Korak 2: Statistički test\ntest_ig <- t.test(carousel, single)\n\n# Korak 3: Veličina učinka\ns_pooled <- sqrt(((n1 - 1) * sd(carousel)^2 + (n2 - 1) * sd(single)^2) / (n1 + n2 - 2))\nd_ig <- (mean(carousel) - mean(single)) / s_pooled\n\ncat(\"=== REZULTAT DVOUZORAČKOG T-TESTA ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== REZULTAT DVOUZORAČKOG T-TESTA ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t(\", round(test_ig$parameter, 1), \") = \", round(test_ig$statistic, 2), \"\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt(461.6) = 14.94\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p < 0.001\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np < 0.001\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Razlika prosjeka: \", round((mean(carousel) - mean(single)) * 100, 2), \" postotnih bodova\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRazlika prosjeka: 2.62 postotnih bodova\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI za razliku: [\", round(test_ig$conf.int[1] * 100, 2), \", \", \n    round(test_ig$conf.int[2] * 100, 2), \"] postotnih bodova\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI za razliku: [2.28, 2.97] postotnih bodova\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Cohenov d:\", round(d_ig, 2), \"(veliki učinak)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohenov d: 1.35 (veliki učinak)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Korak 4: Je li prednost carousela konzistentna po temama?\nig |>\n  group_by(topic, format) |>\n  summarise(M = mean(engagement_rate) * 100, .groups = \"drop\") |>\n  ggplot(aes(x = fct_reorder(topic, M, .fun = max), y = M, fill = format)) +\n  geom_col(position = \"dodge\", alpha = 0.8) +\n  scale_fill_manual(values = c(\"carousel\" = \"#2a9d8f\", \"single_image\" = \"#e76f51\")) +\n  labs(\n    title = \"Engagement rate po temi i formatu\",\n    subtitle = \"Carousel prednost je konzistentna preko svih tema\",\n    x = NULL,\n    y = \"Prosječni engagement rate (%)\",\n    fill = \"Format\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/analiza-po-temi-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Statistički testovi po temi\nig |>\n  group_by(topic) |>\n  summarise(\n    n_carousel = sum(format == \"carousel\"),\n    n_single = sum(format == \"single_image\"),\n    M_carousel = round(mean(engagement_rate[format == \"carousel\"]) * 100, 2),\n    M_single = round(mean(engagement_rate[format == \"single_image\"]) * 100, 2),\n    razlika = round(M_carousel - M_single, 2),\n    p = round(t.test(\n      engagement_rate[format == \"carousel\"],\n      engagement_rate[format == \"single_image\"]\n    )$p.value, 4),\n    znacajno = p < 0.05,\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 8\n  topic     n_carousel n_single M_carousel M_single razlika     p znacajno\n  <chr>          <int>    <int>      <dbl>    <dbl>   <dbl> <dbl> <lgl>   \n1 kultura           35       49       9.66     7.64    2.02     0 TRUE    \n2 lifestyle         61       68      10.6      8.04    2.56     0 TRUE    \n3 sport             46       53      11        7.42    3.58     0 TRUE    \n4 tech              25       22      10.0      6.93    3.09     0 TRUE    \n5 vijesti           69       72       9.37     7.12    2.25     0 TRUE    \n```\n\n\n:::\n:::\n\n\nPrednost carousela je statistički značajna za sve teme. Učinak je konzistentan, što pojačava naše povjerenje u zaključak.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Korak 5: Utjecaj CTA na komentare\nig |>\n  group_by(format, has_cta) |>\n  summarise(M_comments = mean(comments), .groups = \"drop\") |>\n  mutate(has_cta = if_else(has_cta, \"S pozivom na akciju\", \"Bez poziva na akciju\")) |>\n  ggplot(aes(x = format, y = M_comments, fill = has_cta)) +\n  geom_col(position = \"dodge\", alpha = 0.8) +\n  scale_fill_manual(values = c(\"S pozivom na akciju\" = \"#264653\", \"Bez poziva na akciju\" = \"#a8dadc\")) +\n  labs(\n    title = \"Prosječan broj komentara: format × poziv na akciju\",\n    subtitle = \"CTA povećava komentare, osobito kod carousel objava\",\n    x = NULL,\n    y = \"Prosječan broj komentara\",\n    fill = NULL\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/analiza-cta-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Korak 6: Engagement po dobu dana\nig |>\n  mutate(time_of_day = factor(time_of_day, levels = c(\"jutro\", \"podne\", \"poslijepodne\", \"večer\"))) |>\n  group_by(time_of_day, format) |>\n  summarise(\n    M = mean(engagement_rate) * 100,\n    SE = sd(engagement_rate) / sqrt(n()) * 100,\n    .groups = \"drop\"\n  ) |>\n  ggplot(aes(x = time_of_day, y = M, color = format, group = format)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = M - 1.96 * SE, ymax = M + 1.96 * SE), width = 0.15) +\n  scale_color_manual(values = c(\"carousel\" = \"#2a9d8f\", \"single_image\" = \"#e76f51\")) +\n  labs(\n    title = \"Engagement rate po dobu dana s intervalima pouzdanosti\",\n    subtitle = \"Carousel prednost prisutna u svim terminima. Poslijepodne je optimalno za oba formata.\",\n    x = NULL,\n    y = \"Engagement rate (%)\",\n    color = \"Format\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](week-10_files/figure-html/analiza-vrijeme-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Korak 7: Izvještaj za urednicu\ncat(\"════════════════════════════════════════════════════════\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n════════════════════════════════════════════════════════\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"   IZVJEŠTAJ: A/B TEST FORMATA INSTAGRAM OBJAVA\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   IZVJEŠTAJ: A/B TEST FORMATA INSTAGRAM OBJAVA\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"════════════════════════════════════════════════════════\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n════════════════════════════════════════════════════════\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"UZORAK: \", nrow(ig), \" objava (\", n1, \" carousel, \", n2, \" single image)\\n\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUZORAK: 500 objava (236 carousel, 264 single image)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"GLAVNI NALAZ:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGLAVNI NALAZ:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Carousel objave generiraju statistički značajno viši angažman\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCarousel objave generiraju statistički značajno viši angažman\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"od single image objava.\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nod single image objava.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"BROJKE:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBROJKE:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Carousel engagement:    \", round(mean(carousel) * 100, 2), \"% (SD = \", \n    round(sd(carousel) * 100, 2), \"%)\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Carousel engagement:    10.12% (SD = 2.11%)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Single image engagement:\", round(mean(single) * 100, 2), \"% (SD = \", \n    round(sd(single) * 100, 2), \"%)\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Single image engagement:7.5% (SD = 1.77%)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Razlika: \", round((mean(carousel) - mean(single)) * 100, 2), \n    \" postotnih bodova\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Razlika: 2.62 postotnih bodova\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  95% CI:  [\", round(test_ig$conf.int[1] * 100, 2), \", \", \n    round(test_ig$conf.int[2] * 100, 2), \"] postotnih bodova\\n\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  95% CI:  [2.28, 2.97] postotnih bodova\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"STATISTIKA:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSTATISTIKA:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  t(\", round(test_ig$parameter, 1), \") = \", round(test_ig$statistic, 2), \n    \", p < 0.001\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  t(461.6) = 14.94, p < 0.001\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Cohenov d = \", round(d_ig, 2), \" (veliki učinak)\\n\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Cohenov d = 1.35 (veliki učinak)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"DODACI:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDODACI:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  * Prednost je konzistentna preko svih tema i svih doba dana.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  * Prednost je konzistentna preko svih tema i svih doba dana.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  * Poziv na akciju dodatno pojačava komentare (+15%).\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  * Poziv na akciju dodatno pojačava komentare (+15%).\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  * Poslijepodne je optimalno vrijeme za objavu oba formata.\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  * Poslijepodne je optimalno vrijeme za objavu oba formata.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"PREPORUKA:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPREPORUKA:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Prebacite što veći udio objava na carousel format,\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Prebacite što veći udio objava na carousel format,\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  osobito za lifestyle i sportski sadržaj koji i inače\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  osobito za lifestyle i sportski sadržaj koji i inače\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  generiraju najviši angažman. Kombinirajte s pozivom\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  generiraju najviši angažman. Kombinirajte s pozivom\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  na akciju za maksimalne komentare.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  na akciju za maksimalne komentare.\n```\n\n\n:::\n:::\n\n\n---\n\n## Još o p-vrijednostima: ASA izjava i višestruko testiranje {#sec-asa}\n\nAmerička statistička asocijacija (ASA) je 2016. izdala izjavu o p-vrijednostima. Šest principa vrijedi ponoviti.\n\nP-vrijednosti mogu pokazati koliko su podaci nekompatibilni sa specificiranim statističkim modelom. P-vrijednosti ne mjere vjerojatnost da je hipoteza istinita niti vjerojatnost da su podaci proizvedeni samo slučajnošću. Znanstveni zaključci i poslovne odluke ne bi se trebali temeljiti samo na tome prelazi li p-vrijednost specifičan prag. Ispravno zaključivanje zahtijeva puno izvještavanje i transparentnost. P-vrijednost ne mjeri veličinu učinka niti važnost rezultata. Sama p-vrijednost ne pruža dobru mjeru dokaza za model ili hipotezu.\n\n### Višestruko testiranje\n\nKad provodimo mnogo testova istovremeno, povećava se šansa da barem jedan bude lažno pozitivan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulacija: 20 testova, SVI pod H₀ (nema pravih razlika)\nset.seed(42)\n\nsim_20_testova <- map_df(1:20, \\(i) {\n  a <- rnorm(50, mean = 5, sd = 2)\n  b <- rnorm(50, mean = 5, sd = 2)  # isti prosjek!\n  test <- t.test(a, b)\n  tibble(test_broj = i, p = round(test$p.value, 4), znacajno = test$p.value < 0.05)\n})\n\ncat(\"Od 20 testova (svi H₀ istiniti):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOd 20 testova (svi H₀ istiniti):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Statistički značajnih:\", sum(sim_20_testova$znacajno), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStatistički značajnih: 1 \n```\n\n\n:::\n\n```{.r .cell-code}\nsim_20_testova |> filter(znacajno)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  test_broj      p znacajno\n      <int>  <dbl> <lgl>   \n1         9 0.0377 TRUE    \n```\n\n\n:::\n:::\n\n\nČak i kad nijedan učinak ne postoji, jedan ili više testova može biti \"statistički značajan.\" Ovo je problem višestrukog testiranja. Postoje korekcije (Bonferronijeva: podijelite α s brojem testova), ali svjesnost o problemu je prvi korak.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bonferronijeva korekcija\nsim_20_testova |>\n  mutate(\n    p_korigirana = p.adjust(p, method = \"bonferroni\"),\n    znacajno_korigirano = p_korigirana < 0.05\n  ) |>\n  filter(znacajno | znacajno_korigirano) |>\n  select(test_broj, p, znacajno, p_korigirana, znacajno_korigirano)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  test_broj      p znacajno p_korigirana znacajno_korigirano\n      <int>  <dbl> <lgl>           <dbl> <lgl>              \n1         9 0.0377 TRUE            0.754 FALSE              \n```\n\n\n:::\n:::\n\n\nNakon Bonferronijeve korekcije, nijedan test nije značajan. Korekcija je konzervativna (mnogo lažno negativnih), ali štiti od lažno pozitivnih kad provodimo mnogo testova.\n\n::: {.callout-warning}\n## Upozorenje\n\nAko u istraživanju testirate mnogo varijabli i izvijestite samo one koje su značajne, to se zove **p-hacking** ili **cherry-picking**. Rezultati dobiveni na taj način nisu pouzdani jer ne uzimaju u obzir višestruko testiranje. Uvijek izvijestite koliko ste testova proveli, ne samo one koji su dali p < 0.05.\n:::\n\n---\n\n## Pregled svih t-testova {#sec-pregled}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntribble(\n  ~test, ~situacija, ~R_kod, ~primjer,\n  \"Jednouzorački\", \"Jedan uzorak vs poznata vrijednost\", \"t.test(x, mu = 5)\", \"Je li prosječno vrijeme čitanja = 3 min?\",\n  \"Dvouzorački (nezavisni)\", \"Dvije nezavisne skupine\", \"t.test(x, y)\", \"Carousel vs single image engagement\",\n  \"Upareni\", \"Iste jedinice, dva mjerenja\", \"t.test(x, y, paired = TRUE)\", \"Ocjene istih članaka od 2 urednika\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  test                    situacija                          R_kod       primjer\n  <chr>                   <chr>                              <chr>       <chr>  \n1 Jednouzorački           Jedan uzorak vs poznata vrijednost t.test(x, … Je li …\n2 Dvouzorački (nezavisni) Dvije nezavisne skupine            t.test(x, … Carous…\n3 Upareni                 Iste jedinice, dva mjerenja        t.test(x, … Ocjene…\n```\n\n\n:::\n:::\n\n\nSva tri testa imaju istu logiku (testiramo H₀, računamo t, gledamo p). Razlikuju se u formulaciji H₀ i načinu izračuna SE. R funkcija `t.test()` pokriva sva tri slučaja.\n\n---\n\n::: {.callout-important}\n## Ključni zaključci\n\n1. Testiranje hipoteza postavlja nultu hipotezu (H₀: nema učinka) i traži dokaze protiv nje. Ako su podaci dovoljno neobični pod H₀ (p < α), odbacujemo H₀.\n\n2. Testna statistika mjeri koliko su podaci neobični pod H₀. Za t-test: t = razlika / SE. Veći |t| = jači dokaz protiv H₀.\n\n3. P-vrijednost je vjerojatnost podataka (ili ekstremnijih) pod H₀. NIJE vjerojatnost da je H₀ istinita. NIJE mjera veličine učinka.\n\n4. `t.test()` pokriva jednouzorački (mu = vrijednost), dvouzorački (dva vektora) i upareni test (paired = TRUE). Welchov test (default) ne pretpostavlja jednake varijance.\n\n5. Greška tipa I (α) je lažno pozitivni rezultat. Greška tipa II (β) je propuštena prava razlika. Snaga = 1 − β trebala bi biti barem 0.80.\n\n6. Cohenov d izražava razliku u SD jedinicama: d = 0.2 mali, d = 0.5 srednji, d = 0.8 veliki učinak. Uvijek ga izvijestite uz p-vrijednost.\n\n7. `power.t.test()` računa potrebnu veličinu uzorka za zadanu snagu, učinak i α. Planirajte istraživanje PRIJE prikupljanja podataka.\n\n8. Upareni t-test je osjetljiviji od nezavisnog jer kontrolira varijabilnost između parova. Koristite ga kad iste jedinice mjerite dva puta.\n\n9. Statistička značajnost (p < 0.05) ne znači praktičnu važnost. Velik uzorak može detektirati trivijalne razlike. Mali uzorak može propustiti važne razlike.\n\n10. Višestruko testiranje inflacionira grešku tipa I. Ako provodite mnogo testova, koristite korekciju (Bonferroni, BH) ili barem transparentno izvijestite koliko ste testova proveli.\n\n11. Kompletni izvještaj uključuje opisnu statistiku, vizualizaciju, testnu statistiku s p-vrijednošću, veličinu učinka (d) s interpretacijom, interval pouzdanosti za razliku i praktičnu preporuku.\n\n12. Odsutnost statistički značajnog rezultata (p ≥ 0.05) ne znači da učinak ne postoji. Možda uzorak nije bio dovoljno velik. Zato nikad ne kažemo \"prihvaćamo H₀.\"\n:::\n\n---\n\n## Zadaci za pripremu\n\n1. Učitajte `instagram_ab_test.csv`. Testirajte razlikuje li se prosječan broj `saves` između carousel i single image objava. Izračunajte Cohenov d i interpretirajte ga.\n\n2. Odredite minimalnu veličinu uzorka po grupi potrebnu za detektiranje srednjeg učinka (d = 0.5) s 90% snagom na razini α = 0.01.\n\n3. Simulirajte 1000 t-testova gdje su oba uzorka iz iste distribucije (H₀ istinita). Koliki postotak p-vrijednosti je ispod 0.05? Nacrtajte histogram p-vrijednosti i usporedite s uniformnom distribucijom.\n\n---\n\n## Dodatno čitanje\n\n**Obavezno**\n\nNavarro, D. (2018). *Learning Statistics with R*, Chapter 11 (Hypothesis Testing). Besplatno dostupno na [learningstatisticswithr.com](https://learningstatisticswithr.com/lsr-0.6.pdf). Pokriva logiku testiranja hipoteza, t-test i p-vrijednost s R kodom.\n\n**Preporučeno**\n\nDiez, D., Çetinkaya-Rundel, M., & Barr, C. (2019). *OpenIntro Statistics* (4th edition), Chapter 7. Besplatno dostupno na [openintro.org/book/os](https://www.openintro.org/book/os/). Jasne vizualizacije logike testiranja.\n\nWasserstein, R. L., & Lazar, N. A. (2016). The ASA Statement on p-Values: Context, Process, and Purpose. *The American Statistician*, 70(2), 129-133. Službena izjava o pravilnoj upotrebi i interpretaciji p-vrijednosti.\n\nCohen, J. (1992). A Power Primer. *Psychological Bulletin*, 112(1), 155-159. Klasičan kratki pregled veličina učinka i analize snage.\n\n---\n\n## Pojmovnik\n\n| Pojam | Objašnjenje |\n|---|---|\n| Nulta hipoteza (H₀) | Početna pretpostavka da nema učinka ili razlike. Sadrži znak jednakosti. |\n| Alternativna hipoteza (H₁) | Tvrdnja da učinak ili razlika postoji. Sadrži znak nejednakosti. |\n| Testna statistika | Broj koji mjeri koliko su podaci neobični pod H₀. Za t-test: t = razlika / SE. |\n| P-vrijednost | Vjerojatnost podataka (ili ekstremnijih) pod pretpostavkom da je H₀ istinita. |\n| Razina značajnosti (α) | Prag za odbacivanje H₀. Obično 0.05. Kontrolira grešku tipa I. |\n| Greška tipa I | Odbacimo H₀ kad je istinita. Lažno pozitivni rezultat. Vjerojatnost = α. |\n| Greška tipa II | Ne odbacimo H₀ kad je lažna. Propušteni pravi učinak. Vjerojatnost = β. |\n| Statistička snaga | Vjerojatnost detektiranja pravog učinka. Snaga = 1 − β. Cilj ≥ 0.80. |\n| Cohenov d | Standardizirana mjera veličine učinka: razlika prosjeka / pooled SD. d = 0.2 mali, 0.5 srednji, 0.8 veliki. |\n| Pooled SD | Zajednička standardna devijacija dviju grupa, ponderirana njihovim veličinama. |\n| Jednouzorački t-test | Usporedba jednog prosjeka s poznatom vrijednošću. `t.test(x, mu = ...)`. |\n| Dvouzorački t-test | Usporedba prosjeka dviju nezavisnih skupina. `t.test(x, y)`. |\n| Welchov t-test | Default u R-u. Ne pretpostavlja jednake varijance. Robusniji od Studentovog. |\n| Upareni t-test | Usporedba parova (iste jedinice, dva mjerenja). `t.test(x, y, paired = TRUE)`. |\n| Dvosmjerni test | H₁: μ₁ ≠ μ₂. Testira razliku u oba smjera. Default u R-u. |\n| Jednosmjerni test | H₁: μ₁ > μ₂ ili μ₁ < μ₂. Osjetljiviji u jednom smjeru ali slijep za drugi. |\n| Višestruko testiranje | Provođenje mnogo testova istovremeno. Inflacionira grešku tipa I. |\n| Bonferronijeva korekcija | Dijeljenje α s brojem testova. Konzervativna ali jednostavna korekcija. |\n| P-hacking | Selektivno izvještavanje značajnih rezultata iz mnogo provedenih testova. Neprihvatljiva praksa. |\n| `power.t.test()` | R funkcija za analizu snage: izračun potrebnog n, snage ili detektabilnog učinka. |\n| `p.adjust()` | R funkcija za korekciju p-vrijednosti za višestruko testiranje (Bonferroni, BH, itd.). |\n",
    "supporting": [
      "week-10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}