{
  "hash": "8aac97511c9c6bf4a1ab59d3abfedff2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tjedan 4: Deskriptivna statistika\"\nsubtitle: \"Kako brojkama opisati ono što podaci govore\"\ndate: 2025-03-15\ncategories: [deskriptivna statistika, centralna tendencija, varijabilnost, korelacija]\ndraft: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(scales)\n```\n:::\n\n\n::: {.callout-note}\n## Ishodi učenja\n\nNakon ovog predavanja moći ćete\n\n1. Objasniti razliku između mjera centralne tendencije (aritmetička sredina, skraćena sredina, medijan, mod) i odabrati odgovarajuću mjeru za različite tipove podataka.\n2. Izračunati i interpretirati mjere varijabilnosti (raspon, prosječno apsolutno odstupanje, varijanca, standardna devijacija, interkvartilni raspon) te objasniti zašto varijanca dijeli s $N-1$, a ne s $N$.\n3. Prepoznati asimetriju i zaobljenost distribucije te objasniti zašto su te karakteristike važne za izbor statističkih metoda.\n4. Generirati cjeloviti sažetak varijable koristeći `summarise()` i `across()`.\n5. Koristiti `group_by()` i `summarise()` za izračunavanje deskriptivnih statistika po grupama.\n6. Izračunati i interpretirati standardne rezultate (z-scores) te objasniti zašto su korisni za usporedbu varijabli na različitim skalama.\n7. Izračunati i interpretirati Pearsonov i Spearmanov koeficijent korelacije te razumjeti njihova ograničenja.\n8. Prepoznati različite tipove nedostajućih vrijednosti i primijeniti odgovarajuće strategije za rad s njima.\n:::\n\n## Zašto su brojke same po sebi beskorisne\n\nZamislite da ste upravo završili veliko istraživanje o korištenju TikToka u Hrvatskoj. Proveli ste anketu na 300 ispitanika, prikupili podatke o tome koliko minuta dnevno svaka osoba provodi na platformi i sada sjedite pred ogromnom tablicom punom brojki. Vaš urednik ili klijent vas pita jednostavno pitanje: koliko ljudi zapravo koriste TikTok i koliko vremena tamo provode?\n\nMogli biste im poslati cijelu tablicu. Svih 300 redova. Ali to nitko neće čitati i, što je još važnije, nitko iz toga neće izvući nikakav zaključak. Ljudski mozak jednostavno nije dizajniran da iz stotina pojedinačnih brojki spontano prepozna obrasce. Upravo zato postoji deskriptivna statistika. Njezin posao je uzeti gomilu podataka i pretvoriti je u nekoliko smislenih brojki koje opisuju što se u podacima zapravo događa.\n\nTo zvuči jednostavno, i donekle jest, ali postoji jedna zamka o kojoj treba voditi računa od samog početka. **Svaki put kad sažmete podatke u jednu ili dvije brojke, nešto izgubite.** Aritmetička sredina od 65 minuta dnevno na TikToku zvuči informativno, ali skriva činjenicu da neki ljudi provode 140 minuta, a neki samo 7. Ta informacija o raspršenosti podataka jednako je važna kao i ta jedna prosječna vrijednost, a ponekad je i važnija. Upravo zato u deskriptivnoj statistici nikad ne gledamo samo jednu mjeru. Trebamo barem dvije stvari: nešto što nam govori gdje se podaci nalaze (mjere centralne tendencije) i nešto što nam govori koliko su raspršeni (mjere varijabilnosti).\n\nNavarro u svojoj knjizi koristi zgodni paralelizam: zamislite da vam netko opisuje grupu ljudi riječima. Reći će vam nešto o prosječnoj osobi u grupi (to je centralna tendencija), ali će vam reći i koliko su ljudi u grupi slični jedni drugima ili se pak drastično razlikuju (to je varijabilnost). Trebate obje informacije da biste stvorili mentalnu sliku o čemu se radi. Upravo to ćemo naučiti danas.\n\nKrenimo od podataka.\n\n---\n\n## Naši podaci: anketa o korištenju TikToka\n\nTijekom ovog predavanja koristit ćemo simulirani dataset koji sadrži podatke iz ankete o korištenju TikToka. Anketa je provedena na 300 ispitanika različitih dobnih skupina, a prikupljene su informacije o dnevnom vremenu korištenja, broju pogledanih videozapisa tjedno, aktivnosti na platformi i povjerenju u sadržaj koji tamo pronalaze.\n\nUčitajmo podatke i pogledajmo s čime radimo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok <- read_csv(\"../resources/datasets/tiktok_usage.csv\")\nglimpse(tiktok)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 300\nColumns: 11\n$ respondent_id         <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1…\n$ age                   <dbl> 19, 22, 20, 35, 28, 41, 19, 24, 31, 45, 21, 23, …\n$ age_group             <chr> \"18-24\", \"18-24\", \"18-24\", \"25-34\", \"25-34\", \"35…\n$ gender                <chr> \"female\", \"male\", \"female\", \"male\", \"female\", \"m…\n$ daily_minutes         <dbl> 95, 78, 112, 45, 62, 22, 130, 88, 55, 18, 105, 7…\n$ weekly_videos_watched <dbl> 320, 250, 410, 140, 200, 70, 480, 290, 175, 55, …\n$ likes_given           <dbl> 45, 30, 60, 15, 25, 8, 70, 35, 20, 5, 50, 28, 10…\n$ comments_posted       <dbl> 3, 1, 5, 2, 3, 0, 8, 2, 1, 0, 4, 1, 1, 2, 0, 10,…\n$ follows_creators      <dbl> 12, 8, 15, 5, 9, 3, 20, 10, 7, 2, 14, 7, 4, 8, 1…\n$ trust_score           <dbl> 6, 5, 7, 4, 5, 3, 8, 6, 4, 3, 7, 5, 3, 5, 2, 8, …\n$ education             <chr> \"student\", \"student\", \"student\", \"employed\", \"em…\n```\n\n\n:::\n:::\n\n\nImamo 300 redova i 11 stupaca. Svaki red predstavlja jednog ispitanika. Varijabla `daily_minutes` bilježi koliko minuta dnevno osoba koristi TikTok, `age_group` svrstava ispitanike u dobne skupine, `trust_score` mjeri povjerenje u TikTok sadržaj na skali od 1 do 10, a `weekly_videos_watched` bilježi otprilike koliko videozapisa tjedno pogledaju.\n\nPogledajmo prvih desetak redova da stvorimo osjećaj za podatke.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  select(respondent_id, age, age_group, daily_minutes, trust_score) |>\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n   respondent_id   age age_group daily_minutes trust_score\n           <dbl> <dbl> <chr>             <dbl>       <dbl>\n 1             1    19 18-24                95           6\n 2             2    22 18-24                78           5\n 3             3    20 18-24               112           7\n 4             4    35 25-34                45           4\n 5             5    28 25-34                62           5\n 6             6    41 35-44                22           3\n 7             7    19 18-24               130           8\n 8             8    24 18-24                88           6\n 9             9    31 25-34                55           4\n10            10    45 35-44                18           3\n```\n\n\n:::\n:::\n\n\nNa prvi pogled vidimo da mlađi ispitanici provode više vremena na TikToku od starijih. Ali koliko više? I koliko se ispitanici unutar iste dobne skupine razlikuju međusobno? Na ta pitanja odgovaraju deskriptivne statistike.\n\n---\n\n## Mjere centralne tendencije {#sec-centralna-tendencija}\n\nKad netko kaže da želi znati koliko ljudi koriste TikTok, zapravo pita za neku vrstu tipične ili prosječne vrijednosti. U statistici to zovemo **mjerom centralne tendencije** jer tražimo središte oko kojeg se podaci grupiraju. Ideja je intuitvna, ali čim pokušate biti precizni, stvari postaju kompliciranije nego što biste očekivali. Postoji više načina da definirate središte skupa podataka, i ne daju svi iste rezultate. U ovom poglavlju obradit ćemo četiri mjere: aritmetičku sredinu, skraćenu sredinu, medijan i mod.\n\n### Aritmetička sredina\n\nAritmetička sredina je ono što većina ljudi misli kad kaže prosjek. Zbrojite sve vrijednosti i podijelite s brojem opažanja. Formula je jednostavna\n\n$$\n\\bar{X} = \\frac{1}{N} \\sum_{i=1}^{N} X_i\n$$\n\ngdje je $N$ broj opažanja, a $X_i$ svaka pojedinačna vrijednost. Matematička notacija može izgledati zastrašujuće ako je vidite prvi put, ali ideja je stvarno banalna. Zbrojite sve, podijelite s ukupnim brojem. To je to.\n\nU R u to izračunavamo funkcijom `mean()`. Izračunajmo prosječno dnevno korištenje TikToka u cijelom uzorku.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    prosjek_minuta = mean(daily_minutes),\n    n = n()\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  prosjek_minuta     n\n           <dbl> <int>\n1           56.9   300\n```\n\n\n:::\n:::\n\n\nProsječni ispitanik u našem uzorku provodi otprilike 55 minuta dnevno na TikToku. Ali koliko je ta informacija korisna sama za sebe? Zamislite da pišete članak i u njemu navedete samo taj broj. Čitatelj bi mogao pomisliti da većina ljudi provodi oko sat vremena dnevno na TikToku, što je potpuno pogrešan zaključak jer ta sredina skriva enormnu razliku između dobnih skupina.\n\nAritmetička sredina ima jednu veliku prednost i jednu veliku manu. Prednost je da koristi svaku vrijednost u podacima, pa je u tom smislu najinformativnija mjera. U statistici se kaže da je sredina **dovoljni statistik** (sufficient statistic) za normalnu distribuciju, što znači da sadrži svu informaciju o centralnoj tendenciji koju podaci nude. To zvuči apstraktno, ali praktična implikacija je važna: ako su vaši podaci normalno distribuirani, aritmetička sredina je definitivno pravi izbor.\n\nMana je da je **osjetljiva na ekstremne vrijednosti** (outliers). Ako u vašem uzorku postoji jedna osoba koja koristi TikTok 8 sati dnevno (480 minuta), ta jedna osoba će pomaknuti prosjek za cijeli uzorak prema gore. To je razlog zašto prosječna plaća u nekoj zemlji može biti znatno viša od plaće koju prima većina zaposlenih. Nekolicina ljudi s ekstremno visokim primanjima vuče prosjek prema gore.\n\nEvo konkretnog primjera koji pokazuje koliko jedna ekstremna vrijednost može utjecati na sredinu. Zamislite da imate pet korisnika koji TikTok koriste 20, 25, 30, 35 i 40 minuta dnevno. Prosjek je 30 minuta. Sada zamislite da šesti korisnik provodi 480 minuta (8 sati!) dnevno. Prosjek skače na 105 minuta, što nikako ne opisuje tipičnog korisnika u toj grupi.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbez_outliera <- c(20, 25, 30, 35, 40)\ns_outlierom <- c(20, 25, 30, 35, 40, 480)\n\ntibble(\n  skup = c(\"Bez ekstremne vrijednosti\", \"S ekstremnom vrijednošću\"),\n  prosjek = c(mean(bez_outliera), mean(s_outlierom)),\n  medijan = c(median(bez_outliera), median(s_outlierom))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  skup                      prosjek medijan\n  <chr>                       <dbl>   <dbl>\n1 Bez ekstremne vrijednosti      30    30  \n2 S ekstremnom vrijednošću      105    32.5\n```\n\n\n:::\n:::\n\n\nPrimijetite kako prosjek skoči sa 30 na 105, dok medijan ostaje stabilan. Na ovo ćemo se vratiti za trenutak.\n\n::: {.callout-tip}\n## Praktični savjet\n\nKad u medijskim izvještajima vidite izraz prosječna vrijednost bez dodatnog konteksta, uvijek se zapitajte postoje li u tim podacima ekstremne vrijednosti. Ako postoje, aritmetička sredina može biti zavaravajuća. Upravo zato odgovorni novinari uz prosjek uvijek navode i medijan, ili barem napomenu o rasponu podataka. Kad čitate da je prosječna plaća u Hrvatskoj, recimo, 1400 eura, zapitajte se koliki je medijan. Razlika vam govori koliko su plaće neravnomjerno raspodijeljene.\n:::\n\n### Skraćena sredina (trimmed mean) {#sec-skracena-sredina}\n\nPostoji kompromis između aritmetičke sredine (koja koristi sve podatke, ali je osjetljiva na outliere) i medijana (koji je robustan, ali ignorira većinu podataka). Taj kompromis zove se **skraćena sredina** (trimmed mean). Ideja je jednostavna: prije nego izračunamo prosjek, izbacimo određeni postotak najmanjih i najvećih vrijednosti. Najčešće se koristi 5% skraćivanje, što znači da izbacimo 5% najmanjih i 5% najvećih vrijednosti, pa izračunamo prosjek preostalih 90%.\n\nU R u je to trivijalno jer funkcija `mean()` već ima argument `trim` koji prima proporciju (ne postotak!) koja se skraćuje sa svake strane.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    prosjek = mean(daily_minutes),\n    skracena_5 = mean(daily_minutes, trim = 0.05),\n    skracena_10 = mean(daily_minutes, trim = 0.10),\n    medijan = median(daily_minutes)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  prosjek skracena_5 skracena_10 medijan\n    <dbl>      <dbl>       <dbl>   <dbl>\n1    56.9       55.4        54.2      50\n```\n\n\n:::\n:::\n\n\nVidimo da se skraćena sredina nalazi negdje između pune aritmetičke sredine i medijana. Što više skraćujemo, to se rezultat više približava medijanu. Zapravo, ako postavimo `trim = 0.5`, dobili bismo upravo medijan, jer bismo izbacili sve osim srednje vrijednosti.\n\nSkraćena sredina je osobito korisna kad znate da vaši podaci imaju neke ekstremne vrijednosti, ali ne želite ih potpuno ignorirati. U praksi, 5% ili 10% skraćivanje obično dobro funkcionira. Navarro u knjizi napominje da se skraćena sredina pojavljuje iznenađujuće rijetko u objavljenim istraživanjima, što je šteta, jer je u mnogim situacijama bolji izbor od obične sredine.\n\n### Medijan {#sec-medijan}\n\nMedijan je vrijednost koja dijeli podatke na pola. Kad sve vrijednosti poredamo od najmanje do najveće, medijan je ona koja se nalazi točno na sredini. Ako imamo neparan broj opažanja, medijan je srednje opažanje. Ako imamo paran broj, uzimamo prosjek dvaju srednjih opažanja.\n\nOva definicija zvuči jednostavno, ali skriva nešto dublje. Medijan je zapravo odgovor na pitanje koje se razlikuje od pitanja na koje odgovara sredina. Aritmetička sredina minimizira zbroj kvadriranih odstupanja od sebe same. To zvuči apstraktno, ali praktično znači da sredina daje veliku težinu velikim odstupanjima. Medijan, s druge strane, minimizira zbroj **apsolutnih** odstupanja. To znači da medijan tretira sva odstupanja jednako, neovisno o tome koliko su velika. Zato je robustan.\n\nKljučna razlika u odnosu na aritmetičku sredinu jest da medijan **ne ovisi o ekstremnim vrijednostima**. Ako jedna osoba koristi TikTok 480 umjesto 140 minuta dnevno, medijan se neće promijeniti ni za minutu jer ta osoba i dalje ostaje na istom kraju poretka. Vidjeli smo to u primjeru iznad. Zato kažemo da je medijan **robusna** mjera centralne tendencije.\n\nIzračunajmo medijan za naše podatke, zajedno sa sredinom, kako bismo ih mogli usporediti.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    prosjek = mean(daily_minutes),\n    medijan = median(daily_minutes),\n    razlika = mean(daily_minutes) - median(daily_minutes)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  prosjek medijan razlika\n    <dbl>   <dbl>   <dbl>\n1    56.9      50    6.85\n```\n\n\n:::\n:::\n\n\nVidimo da su prosjek i medijan različiti. Kad je prosjek veći od medijana, to je signal da distribucija ima rep prema desno, odnosno da postoje neke veće vrijednosti koje vuku prosjek prema gore. U našem slučaju ta razlika postoji jer imamo velik broj mladih ispitanika koji koriste TikTok znatno više od ostalih, pa distribucija ukupnog uzorka ima pozitivnu asimetriju.\n\nOdnos između sredine i medijana zapravo je brz dijagnostički alat za oblik distribucije. Ako je sredina otprilike jednaka medijanu, distribucija je vjerojatno prilično simetrična. Ako je sredina znatno veća od medijana, distribucija je pozitivno asimetrična (rep prema desno). Ako je sredina znatno manja od medijana, distribucija je negativno asimetrična (rep prema lijevo). Ovo nije egzaktan test, ali u praksi je korisna brza provjera.\n\n### Mod {#sec-mod}\n\nMod je najjednostavnija mjera centralne tendencije. To je jednostavno vrijednost koja se najčešće pojavljuje u podacima. Za kontinuirane podatke (poput minuta korištenja) mod nije osobito koristan jer svaka vrijednost može biti jedinstvena. Ali za kategoričke podatke, mod je savršena mjera. Zapravo, mod je **jedina** smislena mjera centralne tendencije za kategoričke podatke jer ne možete izračunati prosjek ili medijan kategorija poput spola ili vrste medija.\n\nNa primjer, koji je najčešći tip korisnika u našem uzorku po dobi?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  count(age_group, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  age_group     n\n  <chr>     <int>\n1 18-24       102\n2 25-34        86\n3 35-44        62\n4 45+          50\n```\n\n\n:::\n:::\n\n\nModalna kategorija je 18 do 24 jer ta dobna skupina ima najviše ispitanika. To je logično jer su mladi ljudi dominantna publika TikToka, pa ih je u anketi bilo najlakše regrutirati.\n\nPogledajmo i mod za razinu obrazovanja i spol.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  count(education, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  education     n\n  <chr>     <int>\n1 employed    198\n2 student     102\n```\n\n\n:::\n\n```{.r .cell-code}\ntiktok |>\n  count(gender, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  gender     n\n  <chr>  <int>\n1 female   157\n2 male     143\n```\n\n\n:::\n:::\n\n\nJedna stvar koju vrijedi napomenuti o modu jest da distribucija može imati više modova. Kad distribucija ima dva vrha, kažemo da je **bimodalna**. To se u praksi događa kad su u uzorku pomiješane dvije različite populacije. Na primjer, ako bismo gledali distribuciju dnevnog korištenja TikToka za cijeli uzorak (bez razdvajanja po dobi), mogli bismo vidjeti dva vrha: jedan za mlade korisnike (oko 100 minuta) i jedan za starije (oko 15 minuta). To je signal da ukupna distribucija zapravo skriva dvije različite grupe, što je izuzetno korisna informacija.\n\n### Kada koristiti koju mjeru? {#sec-koja-mjera}\n\nOvo je pitanje na koje studenti često žele jednostavan odgovor, ali odgovor zapravo ovisi o kontekstu. Ipak, postoje neka korisna pravila koja se izvode iz matematičkih svojstava svake mjere.\n\nZa **numeričke podatke koji su približno simetrično distribuirani** (nemaju dugačke repove na jednoj strani), aritmetička sredina je sasvim dobra mjera. Ona koristi sve podatke i statistička teorija se u velikoj mjeri oslanja na nju. Ako nemate razloga za sumnju u ekstremne vrijednosti, koristite sredinu.\n\nZa **numeričke podatke s izrazitim ekstremnim vrijednostima** (poput prihoda, cijena nekretnina, broja pratitelja na društvenim mrežama ili broja dijeljenja objave), medijan je pouzdaniji izbor. Alternativno, možete koristiti skraćenu sredinu koja je kompromis između robusnosti i informativnosti.\n\nZa **kategoričke podatke**, mod je jedina smislena opcija jer ne možete izračunati prosjek spola ili vrste medija. To se čini očitim, ali iznenađujuće je koliko se često u izvještajima pokušavaju interpretirati prosjeci Likertove skale (na primjer, prosječan odgovor 3.7 na skali od 1 do 5) kao da su smisleni. Tehnički, Likertove skale su ordinalne varijable, i prosjek ordinalnih podataka je diskutabilan. U praksi se to ipak često radi, ali vrijedi biti svjestan ograničenja.\n\n::: {.callout-important}\n## Važna napomena\n\nNikada nemojte izvijestiti samo jednu mjeru centralne tendencije. Kad pišete izvještaj ili analizu, dobra praksa je navesti i prosjek i medijan za numeričke varijable. Ako su slični, distribucija je vjerojatno prilično simetrična. Ako se razlikuju, to je signal da se u podacima nešto zanimljivo događa i vrijedi istražiti dalje. U akademskim radovima iz komunikologije standardno se navode sredina i standardna devijacija za sve ključne varijable, obično u tablici deskriptivnih statistika.\n:::\n\n---\n\n## Mjere varijabilnosti {#sec-varijabilnost}\n\nZnati gdje se podaci nalaze je tek pola priče. Jednako je važno znati koliko su podaci raspršeni. Navarro u knjizi koristi lijep primjer: zamislite da vam kažem da je prosječna temperatura u dva grada jednaka, recimo 15°C. Na temelju te informacije mogli biste pomisliti da su ta dva grada klimatski slična. Ali zamislite da u jednom gradu temperatura nikad ne padne ispod 10°C niti naraste iznad 20°C, dok u drugom temperatura varira od minus 20°C zimi do plus 45°C ljeti. Očito, to su potpuno različiti gradovi unatoč istoj prosječnoj temperaturi. Razlika je u varijabilnosti.\n\nIsto vrijedi za medijske podatke. Zamislite dva medijska portala čiji članci u prosjeku dobivaju po 50 komentara. Na prvom portalu svaki članak dobiva između 45 i 55 komentara. Na drugom portalu neki članci dobiju 0, a poneki 200. Prosjek je isti, ali situacija je potpuno drugačija. Upravo to razlikuju mjere varijabilnosti.\n\n### Raspon {#sec-raspon}\n\nNajjednostavnija mjera varijabilnosti je raspon. To je razlika između najveće i najmanje vrijednosti u podacima. Izračunajmo raspon dnevnog korištenja TikToka.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    minimum = min(daily_minutes),\n    maksimum = max(daily_minutes),\n    raspon = max(daily_minutes) - min(daily_minutes)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  minimum maksimum raspon\n    <dbl>    <dbl>  <dbl>\n1       7      140    133\n```\n\n\n:::\n:::\n\n\nRaspon nam govori da se dnevno korištenje kreće od jedva desetak minuta do gotovo dva i pol sata, što je ogromna razlika. Međutim, raspon ima isti problem kao aritmetička sredina, samo s druge strane. Ovisi samo o dvije najekstremnije vrijednosti i potpuno ignorira sve ostale. Ako se u uzorku pojavi jedna osoba koja koristi TikTok 12 sati dnevno, raspon će eksplodirati, a svi ostali podaci ostaju isti. Raspon je koristan kao brzi orijentir, ali za ozbiljnu analizu trebamo nešto bolje.\n\n### Prosječno apsolutno odstupanje {#sec-aad}\n\nPrije nego prijeđemo na varijancu, vrijedi se nakratko zadržati na jednoj mjeri koja je konceptualno jednostavnija, a to je **prosječno apsolutno odstupanje** (average absolute deviation, AAD). Ideja je sljedeća: za svako opažanje izračunamo koliko se razlikuje od aritmetičke sredine (to je odstupanje ili devijacija), uzmemo apsolutnu vrijednost tog odstupanja (jer nas zanima veličina odstupanja, ne smjer), i izračunamo prosjek svih apsolutnih odstupanja.\n\n$$\n\\text{AAD} = \\frac{1}{N} \\sum_{i=1}^{N} |X_i - \\bar{X}|\n$$\n\nZašto ovo uopće spominjemo? Zato što je AAD puno intuitivniji od varijance. Kad kažete da je prosječno apsolutno odstupanje 30 minuta, to doslovno znači da se prosječni ispitanik razlikuje od sredine za oko 30 minuta. To je vrlo jednostavno za interpretirati.\n\nR nema ugrađenu funkciju za AAD, ali ga možemo lako izračunati.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    prosjek = mean(daily_minutes),\n    aad = mean(abs(daily_minutes - mean(daily_minutes)))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  prosjek   aad\n    <dbl> <dbl>\n1    56.9  33.0\n```\n\n\n:::\n:::\n\n\nProblem s AAD-om je da apsolutna vrijednost matematički nije ugodna za rad. Nije diferencijabilna u nuli, što otežava izvođenje formula u statistici. Zato su statističari davno odlučili koristiti kvadrate umjesto apsolutnih vrijednosti, i tako smo dobili varijancu. Ta odluka ima duboke posljedice za cijelu statistiku, ali za naše potrebe dovoljno je znati da varijanca postoji zato što su kvadrati matematički elegantniji od apsolutnih vrijednosti, čak i ako su manje intuitivni.\n\n### Varijanca {#sec-varijanca}\n\nVarijanca je sofisticiranija mjera raspršenosti. Ideja je sljedeća. Uzmemo svaku vrijednost u podacima i izračunamo koliko se razlikuje od aritmetičke sredine. To se zove **odstupanje** (deviation). Zatim ta odstupanja kvadriramo (jer bi se pozitivna i negativna inače poništila) i izračunamo njihov prosjek. Ili, točnije, gotovo prosjek.\n\nPogledajmo najprije formulu, pa ćemo razjasniti taj gotovo prosjek.\n\n$$\ns^2 = \\frac{1}{N-1} \\sum_{i=1}^{N} (X_i - \\bar{X})^2\n$$\n\n#### Zašto dijelimo s $N-1$? Besselova korekcija {#sec-bessel}\n\nPrimijetite da dijelimo s $N-1$, a ne s $N$. Ovo je jedan od onih detalja koji studente redovito zbunjuju, a vrijedi razumjeti zašto je tako. Dijeljenje s $N-1$ zove se **Besselova korekcija** i postoji iz razloga koji su vezani uz procjenu populacijskih parametara iz uzorka.\n\nEvo intuicije. Kad računamo varijancu uzorka, koristimo sredinu uzorka $\\bar{X}$ kao procjenu populacijske sredine $\\mu$. Ali sredina uzorka je izračunata iz istih podataka iz kojih računamo odstupanja. To stvara suptilni problem: odstupanja od sredine uzorka su sustavno manja nego što bi bila odstupanja od prave populacijske sredine, jer je sredina uzorka po definiciji najbliža moguća vrijednost tim konkretnim podacima. Dijeljenje s $N-1$ umjesto $N$ ispravlja tu pristranost i daje **nepristranu procjenu** populacijske varijance.\n\nAko vam ovo zvuči apstraktno, ne brinite previše. Za velike uzorke (N > 30) razlika između dijeljenja s $N$ i $N-1$ je minimalna. Ali za male uzorke može biti značajna, pa se konvencija $N-1$ koristi uvijek. R-ova funkcija `var()` automatski koristi $N-1$.\n\nNavarro u knjizi posvećuje dosta prostora objašnjavanju ovog koncepta i iskreno kaže da je to jedan od najtežih dijelova uvodnog kolegija statistike. Mi ćemo se na ovu temu detaljno vratiti kad budemo govorili o uzorcima i populacijama u kasnijim tjednima. Za sada je dovoljno zapamtiti da `var()` u R u radi ono što treba.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    varijanca = var(daily_minutes)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  varijanca\n      <dbl>\n1     1487.\n```\n\n\n:::\n:::\n\n\nProblem s varijancom je što je teško interpretirati. Mjerna jedinica varijance je kvadrat izvorne mjerne jedinice, dakle u našem slučaju minute na kvadrat. Što to uopće znači, minute na kvadrat? Ništa intuitivno. Zato postoji standardna devijacija.\n\n#### Ručno izračunavanje varijance korak po korak\n\nKorisno je barem jednom vidjeti kako se varijanca računa ručno, korak po korak, čak i ako to u praksi nikad nećemo raditi. Ovo pomaže izgraditi intuiciju.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Uzmimo mali podskup podataka za demonstraciju\ndemo <- tiktok |>\n  slice(1:6) |>\n  select(respondent_id, daily_minutes)\n\ndemo |>\n  mutate(\n    sredina = mean(daily_minutes),\n    odstupanje = daily_minutes - mean(daily_minutes),\n    kvadrirano_odstupanje = odstupanje^2\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  respondent_id daily_minutes sredina odstupanje kvadrirano_odstupanje\n          <dbl>         <dbl>   <dbl>      <dbl>                 <dbl>\n1             1            95      69         26                   676\n2             2            78      69          9                    81\n3             3           112      69         43                  1849\n4             4            45      69        -24                   576\n5             5            62      69         -7                    49\n6             6            22      69        -47                  2209\n```\n\n\n:::\n:::\n\n\nVarijanca je zbroj svih kvadriranih odstupanja podijeljen s $N-1$. Vidimo da veća odstupanja (pozitivna ili negativna) imaju neproporcionalno velik utjecaj na varijancu jer se kvadriraju. To je upravo razlog zašto je varijanca (i standardna devijacija) osjetljiva na ekstremne vrijednosti.\n\n### Standardna devijacija {#sec-sd}\n\nStandardna devijacija je jednostavno korijen iz varijance.\n\n$$\ns = \\sqrt{s^2} = \\sqrt{\\frac{1}{N-1} \\sum_{i=1}^{N} (X_i - \\bar{X})^2}\n$$\n\nNjezina prednost je što je u istim mjernim jedinicama kao i izvorni podaci. Ako je standardna devijacija dnevnog korištenja TikToka 40 minuta, to znači da se ispitanici u prosjeku razlikuju od aritmetičke sredine za otprilike 40 minuta. To nije savršena interpretacija (prisjetite se, standardna devijacija koristi kvadrate, ne apsolutne vrijednosti, pa nije identična prosječnom apsolutnom odstupanju), ali je dovoljno dobra za intuitivno razumijevanje.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    prosjek = mean(daily_minutes),\n    sd = sd(daily_minutes),\n    medijan = median(daily_minutes),\n    aad = mean(abs(daily_minutes - mean(daily_minutes)))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  prosjek    sd medijan   aad\n    <dbl> <dbl>   <dbl> <dbl>\n1    56.9  38.6      50  33.0\n```\n\n\n:::\n:::\n\n\nPrimijetite da je standardna devijacija nešto veća od prosječnog apsolutnog odstupanja. To je uvijek tako, jer kvadriranje daje veću težinu velikim odstupanjima.\n\nStandardna devijacija je daleko najčešće korištena mjera varijabilnosti u znanosti, uključujući komunikologiju. Kad u akademskom radu vidite tablicu deskriptivnih statistika, gotovo uvijek će sadržavati sredinu (M) i standardnu devijaciju (SD) za svaku varijablu.\n\n#### Interpretacija standardne devijacije\n\nZa podatke koji su približno normalno distribuirani, vrijedi korisno pravilo palca:\n\nOtprilike 68% podataka nalazi se unutar jedne standardne devijacije od sredine. Otprilike 95% podataka nalazi se unutar dvije standardne devijacije. Otprilike 99.7% unutar tri standardne devijacije.\n\nOvo se ponekad naziva pravilo 68-95-99.7 ili empirijsko pravilo. Ako je sredina 55 i SD 40, onda se otprilike 68% ispitanika nalazi između 15 i 95 minuta. Naravno, ovo pravilo vrijedi samo za normalno distribuirane podatke, a naši podaci o TikToku sigurno nisu savršeno normalno distribuirani. Ali i tada, pravilo daje koristan okvirni uvid.\n\n### Interkvartilni raspon {#sec-iqr}\n\nBaš kao što medijan ima prednost nad aritmetičkom sredinom kod ekstremnih vrijednosti, tako i **interkvartilni raspon** (IQR) ima prednost nad standardnom devijacijom. Da bismo razumjeli IQR, moramo najprije razumjeti percentile i kvartile.\n\n#### Percentili i kvartili\n\n**Percentil** je vrijednost ispod koje se nalazi određeni postotak podataka. 25. percentil (ili prvi kvartil, Q1) je vrijednost ispod koje se nalazi 25% podataka. 50. percentil je medijan. 75. percentil (treći kvartil, Q3) je vrijednost ispod koje se nalazi 75% podataka.\n\nKvartili dijele podatke na četiri jednaka dijela, baš kao što medijan dijeli na dva.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    Q1 = quantile(daily_minutes, 0.25),\n    medijan = quantile(daily_minutes, 0.50),\n    Q3 = quantile(daily_minutes, 0.75),\n    IQR = IQR(daily_minutes)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n     Q1 medijan    Q3   IQR\n  <dbl>   <dbl> <dbl> <dbl>\n1    21      50    90    69\n```\n\n\n:::\n:::\n\n\nIQR je razlika između Q3 i Q1, dakle raspon unutar kojeg se nalaze srednjih 50% podataka. To je robusna mjera koja neće skočiti zbog jedne ekstremne vrijednosti.\n\nMožemo izračunati i detaljnije percentile.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npercentili <- c(0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95)\n\ntibble(\n  percentil = percentili * 100,\n  vrijednost = quantile(tiktok$daily_minutes, percentili)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  percentil vrijednost\n      <dbl>      <dbl>\n1         5       9.95\n2        10      11   \n3        25      21   \n4        50      50   \n5        75      90   \n6        90     114.  \n7        95     124.  \n```\n\n\n:::\n:::\n\n\nOva tablica nam daje bogatu sliku o distribuciji. Vidimo da 5% ispitanika koristi TikTok manje od pedesetak minuta (najniži percentil), a 5% koristi više od gornjeg percentila. Srednja polovica uzorka (od 25. do 75. percentila) pokriva raspon koji nam daje IQR.\n\n::: {.callout-tip}\n## Praktični savjet\n\nKad opisujete podatke u izvještaju ili radu, kombinirajte mjere centralne tendencije i varijabilnosti. Dobar opis bi glasio otprilike ovako: ispitanici u prosjeku koriste TikTok M minuta dnevno (SD = X), a medijan je Y minuta. Srednja polovica ispitanika provodi na platformi između Q1 i Q3 minuta dnevno (IQR = Z). Ova kombinacija sredine, SD, medijana i IQR daje čitatelju bogatu sliku podataka u samo dvije rečenice.\n:::\n\n### Koja mjera varijabilnosti? {#sec-koja-varijabilnost}\n\nIzbor mjere varijabilnosti prati istu logiku kao izbor mjere centralne tendencije. Ako ste izabrali sredinu, standardna devijacija je prirodan par jer obje koriste iste matematičke principe (kvadrate odstupanja). Ako ste izabrali medijan, IQR je prirodan par jer su obje robusne mjere.\n\nU praksi, u akademskim radovima gotovo uvijek vidite sredinu i SD. To je konvencija. Ali to ne znači da je to uvijek najbolji izbor. Za podatke koji su jako asimetrični (što je čest slučaj s medijskim metrikama poput broja dijeljenja, broja pratitelja, ili vremena na stranici), medijan i IQR su informativniji.\n\n---\n\n## Ukupni sažetak varijable {#sec-sazetak}\n\nU praksi, kad dobijete novi dataset, prva stvar koju želite napraviti je brzi pregled svih varijabli. Umjesto da za svaku varijablu posebno računate sredinu, SD, medijan i tako dalje, R nudi načine da to napravite odjednom.\n\nOsnovna funkcija `summary()` daje brzi pregled.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  select(daily_minutes, weekly_videos_watched, trust_score) |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n daily_minutes    weekly_videos_watched  trust_score   \n Min.   :  7.00   Min.   : 20.0         Min.   :2.000  \n 1st Qu.: 21.00   1st Qu.: 65.0         1st Qu.:3.000  \n Median : 50.00   Median :159.0         Median :4.000  \n Mean   : 56.85   Mean   :189.6         Mean   :4.497  \n 3rd Qu.: 90.00   3rd Qu.:300.0         3rd Qu.:6.000  \n Max.   :140.00   Max.   :500.0         Max.   :8.000  \n```\n\n\n:::\n:::\n\n\nFunkcija `summary()` za numeričke varijable automatski ispisuje minimum, prvi kvartil, medijan, sredinu, treći kvartil i maksimum. To je tzv. **five-number summary** (plus sredina), i daje solidan pregled distribucije.\n\nJoš moćniji pristup je koristiti `summarise()` s `across()` da izračunamo točno one statistike koje želimo, za sve numeričke varijable odjednom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    across(\n      where(is.numeric),\n      list(\n        prosjek = ~mean(.x, na.rm = TRUE),\n        sd = ~sd(.x, na.rm = TRUE),\n        medijan = ~median(.x, na.rm = TRUE)\n      ),\n      .names = \"{.col}_{.fn}\"\n    )\n  ) |>\n  pivot_longer(\n    everything(),\n    names_to = c(\"varijabla\", \"statistika\"),\n    names_sep = \"_(?=[^_]+$)\",\n    values_to = \"vrijednost\"\n  ) |>\n  pivot_wider(\n    names_from = statistika,\n    values_from = vrijednost\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  varijabla             prosjek     sd medijan\n  <chr>                   <dbl>  <dbl>   <dbl>\n1 respondent_id          150.    86.7     150.\n2 age                     32.1   10.6      30 \n3 daily_minutes           56.9   38.6      50 \n4 weekly_videos_watched  190.   139.      159 \n5 likes_given             23.5   20.2      17 \n6 comments_posted          1.91   2.23      1 \n7 follows_creators         7.08   5.39      6 \n8 trust_score              4.50   1.85      4 \n```\n\n\n:::\n:::\n\n\nOvaj kod izgleda komplicirano, ali radi nešto vrlo korisno: za svaku numeričku varijablu izračunava sredinu, SD i medijan, te rezultate prikazuje u čitljivoj tablici. Funkcija `across()` primjenjuje iste izračune na sve odabrane stupce, a `pivot_longer()` i `pivot_wider()` preoblikuju rezultat u preglednu formu. Ovo je obrazac koji ćete koristiti iznova i iznova, pa ga vrijedi zapamtiti (ili još bolje, spremiti u skriptu za ponovnu upotrebu).\n\n---\n\n## Deskriptivne statistike po grupama {#sec-po-grupama}\n\nUkupne statistike su korisne, ali prava snaga deskriptivne analize dolazi do izražaja kad podatke razbijemo po grupama. U komunikologiji nas gotovo uvijek zanima usporedba: koriste li žene i muškarci TikTok jednako? Razlikuju li se dobne skupine? Ovisi li povjerenje u sadržaj o intenzitetu korištenja?\n\nTidyverse čini ovu vrstu analize izuzetno elegantnom. Kombinacija `group_by()` i `summarise()` je jedan od najmoćnijih alata koje ćete naučiti u ovom kolegiju. Logika je jednostavna: `group_by()` podijeli podatke u grupe, a `summarise()` izračuna statistike za svaku grupu zasebno. U pozadini, R ponavlja identičan izračun za svaki podskup podataka i rezultate slaže u jednu tablicu.\n\nPogledajmo kako se korištenje TikToka razlikuje po dobnim skupinama.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  group_by(age_group) |>\n  summarise(\n    n = n(),\n    prosjek = mean(daily_minutes),\n    sd = sd(daily_minutes),\n    medijan = median(daily_minutes),\n    min = min(daily_minutes),\n    max = max(daily_minutes),\n    .groups = \"drop\"\n  ) |>\n  arrange(desc(prosjek))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  age_group     n prosjek    sd medijan   min   max\n  <chr>     <int>   <dbl> <dbl>   <dbl> <dbl> <dbl>\n1 18-24       102   104.  17.1    104      72   140\n2 25-34        86    52.6  7.78    52.5    40    68\n3 35-44        62    22.3  2.70    22      18    30\n4 45+          50    10.7  2.17    11       7    15\n```\n\n\n:::\n:::\n\n\nOvdje se jasno vidi ono što smo slutili iz sirovih podataka. Najmlađa skupina (18 do 24 godine) koristi TikTok u prosjeku preko 100 minuta dnevno, dok najstarija skupina (45+) provodi na platformi tek desetak minuta. Razlika je dramatična.\n\nPrimijetite i nešto važno: standardna devijacija unutar svake grupe je znatno manja nego u ukupnom uzorku. To je zato što smo grupiranjem uklonili najveći izvor varijabilnosti, a to je upravo dob. Ova tehnika grupiranja ključna je za razumijevanje podataka. Kad god vidite veliku standardnu devijaciju u ukupnom uzorku, prvo što biste trebali učiniti jest pogledati postoji li neka grupna varijabla koja objašnjava tu varijabilnost. U našem slučaju, dob objašnjava najveći dio razlika u korištenju TikToka.\n\nMožemo ići i korak dalje te kombinirati dva kriterija grupiranja. Pogledajmo korištenje po dobnoj skupini i spolu.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  group_by(age_group, gender) |>\n  summarise(\n    n = n(),\n    prosjek = round(mean(daily_minutes), 1),\n    sd = round(sd(daily_minutes), 1),\n    .groups = \"drop\"\n  ) |>\n  arrange(age_group, gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  age_group gender     n prosjek    sd\n  <chr>     <chr>  <int>   <dbl> <dbl>\n1 18-24     female    58   117.   11.1\n2 18-24     male      44    87.6   6  \n3 25-34     female    45    54.8   8.8\n4 25-34     male      41    50.1   5.7\n5 35-44     female    30    21.8   2.4\n6 35-44     male      32    22.8   2.9\n7 45+       female    24    10.7   2.2\n8 45+       male      26    10.8   2.2\n```\n\n\n:::\n:::\n\n\nVidimo da unutar svake dobne skupine žene u prosjeku koriste TikTok nešto više nego muškarci. Ta razlika je konzistentna kroz sve dobne skupine, ali je relativno mala u usporedbi s razlikom između samih dobnih skupina. To je upravo ona vrsta uvida koju dobivate kad pravilno razbijete podatke po relevantnim kategorijama.\n\n::: {.callout-important}\n## Važna napomena\n\nArgument `.groups = \"drop\"` na kraju `summarise()` poziva služi tome da R ukloni grupiranje nakon izračuna. Bez njega, rezultirajući tibble bi ostao grupiran po `age_group` (jer je `summarise()` automatski uklonio samo zadnju razinu grupiranja, a `gender` je zadnja). To može uzrokovati neočekivano ponašanje u kasnijim operacijama. Dobra praksa je uvijek eksplicitno navesti ovaj argument kad koristite više od jedne grupirajuće varijable.\n:::\n\nPogledajmo i deskriptivne statistike za varijablu povjerenja u sadržaj (trust_score) po dobnim skupinama.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  group_by(age_group) |>\n  summarise(\n    n = n(),\n    prosjek_trust = round(mean(trust_score), 1),\n    sd_trust = round(sd(trust_score), 1),\n    medijan_trust = median(trust_score),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  age_group     n prosjek_trust sd_trust medijan_trust\n  <chr>     <int>         <dbl>    <dbl>         <dbl>\n1 18-24       102           6.7      0.8             7\n2 25-34        86           4.5      0.5             4\n3 35-44        62           3        0               3\n4 45+          50           2        0               2\n```\n\n\n:::\n:::\n\n\nZanimljivo je da povjerenje u sadržaj prati sličan obrazac kao i korištenje: mladi korisnici imaju veće povjerenje u TikTok sadržaj. Čini se da što više vremena netko provodi na platformi, to više vjeruje sadržaju koji tamo pronalazi. Ovo bi moglo biti zanimljivo za daljnje istraživanje, ali budite oprezni s uzročno-posljedičnim zaključcima. Korelacija nije uzročnost, a do tog pojma stižemo uskoro.\n\n---\n\n## Oblik distribucije: asimetrija i zaobljenost {#sec-oblik-distribucije}\n\nOsim centralne tendencije i varijabilnosti, treća važna karakteristika podataka je **oblik distribucije**. Dva najvažnija aspekta oblika su asimetrija (skewness) i zaobljenost (kurtosis).\n\n### Asimetrija (skewness) {#sec-asimetrija}\n\nDistribucija je **simetrična** kad lijeva i desna strana izgledaju kao zrcalna slika. Normalna distribucija (ona poznata zvonolika krivulja) je savršeno simetrična. U praksi, savršena simetrija je rijetka.\n\nKad distribucija ima dugačak rep prema desno (više ekstremno visokih vrijednosti), kažemo da je **pozitivno asimetrična** (right-skewed ili positively skewed). Kad ima dugačak rep prema lijevo, kažemo da je **negativno asimetrična** (left-skewed ili negatively skewed).\n\nMatematička definicija asimetrije koristi treći standardizirani moment\n\n$$\n\\text{skewness} = \\frac{1}{N} \\sum_{i=1}^{N} \\left( \\frac{X_i - \\bar{X}}{s} \\right)^3\n$$\n\nPrimijetite da je eksponent 3, a ne 2 kao kod varijance. Budući da kubiranje čuva predznak (negativan broj na treću ostaje negativan), ovaj izraz je pozitivan kad distribucija ima rep prema desno (jer veliki pozitivni residuali dominiraju) i negativan kad ima rep prema lijevo.\n\nU komunikologiji se pozitivna asimetrija pojavljuje vrlo često. Broj pratitelja na društvenim mrežama, broj dijeljenja objave, prihod od oglašavanja, vrijeme provedeno na web stranici, broj komentara na članku, sve su to varijable koje tipično imaju pozitivnu asimetriju. Većina vrijednosti je relativno mala, ali postoji dugačak rep velikih vrijednosti. To je gotovo univerzalna karakteristika metrika angažmana u digitalnim medijima i vrijedi je zapamtiti kao opće pravilo.\n\nJednostavan način da provjerite asimetriju jest usporedba aritmetičke sredine i medijana. Ako je sredina veća od medijana, distribucija je vjerojatno pozitivno asimetrična. Ako je medijan veći, negativno asimetrična.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    across(\n      c(daily_minutes, weekly_videos_watched, likes_given, comments_posted),\n      list(\n        prosjek = ~mean(.x),\n        medijan = ~median(.x),\n        razlika = ~mean(.x) - median(.x)\n      ),\n      .names = \"{.col}_{.fn}\"\n    )\n  ) |>\n  pivot_longer(\n    everything(),\n    names_to = c(\"varijabla\", \"statistika\"),\n    names_sep = \"_(?=[^_]+$)\",\n    values_to = \"vrijednost\"\n  ) |>\n  pivot_wider(names_from = statistika, values_from = vrijednost)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  varijabla             prosjek medijan razlika\n  <chr>                   <dbl>   <dbl>   <dbl>\n1 daily_minutes           56.9       50   6.85 \n2 weekly_videos_watched  190.       159  30.6  \n3 likes_given             23.5       17   6.54 \n4 comments_posted          1.91       1   0.913\n```\n\n\n:::\n:::\n\n\nPozitivna razlika između prosjeka i medijana za sve varijable potvrđuje da su distribucije pozitivno asimetrične. To je očekivano jer u uzorku postoji skupina mladih korisnika koji imaju izrazito visoke vrijednosti na svim metrikama korištenja.\n\n### Zaobljenost (kurtosis) {#sec-zaobljenost}\n\nZaobljenost opisuje koliko su repovi distribucije teški u usporedbi s normalnom distribucijom. Koristi četvrti standardizirani moment\n\n$$\n\\text{kurtosis} = \\frac{1}{N} \\sum_{i=1}^{N} \\left( \\frac{X_i - \\bar{X}}{s} \\right)^4\n$$\n\nZa normalnu distribuciju, kurtosis iznosi 3. Zato se često koristi **višak zaobljenosti** (excess kurtosis) koji oduzima 3, pa normalna distribucija ima excess kurtosis jednak 0.\n\nDistribucija s velikom zaobljenošću (leptokurtic, excess kurtosis > 0) ima teže repove i oštriji vrh od normalne. To znači da ima više ekstremnih vrijednosti nego što bismo očekivali. Distribucija s malom zaobljenošću (platykurtic, excess kurtosis < 0) ima lakše repove i zaobljeniji vrh.\n\nZa svakodnevni rad u komunikologiji, zaobljenost je manje važna od asimetrije. Ipak, vrijedi ju poznavati jer se pojavljuje u izvještajima statističkog softvera i u akademskim radovima. Najvažnija praktična implikacija je da distribucija s velikom zaobljenošću ima više ekstremnih vrijednosti nego što bismo očekivali od normalne distribucije, što može utjecati na rezultate statističkih testova koji pretpostavljaju normalnost.\n\n::: {.callout-tip}\n## Praktični savjet\n\nAsimetrija i zaobljenost postaju osobito važne kad počnemo raditi inferencijsku statistiku (t-testove, ANOVA-u, regresiju) jer mnogi od tih testova pretpostavljaju normalnost distribucije. U tom kontekstu, asimetrija i zaobljenost služe kao dijagnostički alati za provjeru pretpostavki. O tome ćemo detaljno govoriti u kasnijim tjednima.\n:::\n\n---\n\n## Standardni rezultati (z-scores) {#sec-z-scores}\n\nPonekad trebamo usporediti vrijednosti na potpuno različitim skalama. Na primjer, kako usporediti nekoga tko provodi 120 minuta dnevno na TikToku s nekim tko ima trust_score 8? To su različite varijable s različitim mjernim jedinicama i različitim rasponima. Standardni rezultati (z-scores) rješavaju taj problem.\n\nStandardni rezultat nam govori koliko se standardnih devijacija neka vrijednost nalazi iznad ili ispod aritmetičke sredine. Formula je\n\n$$\nz_i = \\frac{X_i - \\bar{X}}{s}\n$$\n\nAko je z-score jednak 0, ta vrijednost je jednaka prosjeku. Ako je 1, ta vrijednost je jednu standardnu devijaciju iznad prosjeka. Ako je minus 2, ta je vrijednost dvije standardne devijacije ispod prosjeka.\n\nZ-scores su korisni iz još jednog razloga. Kad pretvorite varijablu u z-scores, rezultirajuća varijabla uvijek ima sredinu 0 i standardnu devijaciju 1. To se zove **standardizacija** i često se koristi u naprednim statističkim metodama.\n\nIzračunajmo z-score za dnevno korištenje TikToka. Možemo to napraviti ručno (koristeći formulu) ili pomoću ugrađene funkcije `scale()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  mutate(\n    z_rucno = (daily_minutes - mean(daily_minutes)) / sd(daily_minutes),\n    z_scale = as.numeric(scale(daily_minutes))\n  ) |>\n  select(respondent_id, age_group, daily_minutes, z_rucno, z_scale) |>\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n   respondent_id age_group daily_minutes z_rucno z_scale\n           <dbl> <chr>             <dbl>   <dbl>   <dbl>\n 1             1 18-24                95  0.989   0.989 \n 2             2 18-24                78  0.548   0.548 \n 3             3 18-24               112  1.43    1.43  \n 4             4 25-34                45 -0.307  -0.307 \n 5             5 25-34                62  0.133   0.133 \n 6             6 35-44                22 -0.904  -0.904 \n 7             7 18-24               130  1.90    1.90  \n 8             8 18-24                88  0.808   0.808 \n 9             9 25-34                55 -0.0481 -0.0481\n10            10 35-44                18 -1.01   -1.01  \n```\n\n\n:::\n:::\n\n\nObje metode daju identične rezultate. Funkcija `scale()` vraća matricu, pa koristimo `as.numeric()` da pretvorimo rezultat u obični numerički vektor.\n\nSada vidimo da osoba s 95 minuta dnevno ima pozitivan z-score (iznad prosjeka), dok osoba s 22 minute ima negativan z-score (ispod prosjeka). Osoba čiji je z-score oko 2 nalazi se dvije standardne devijacije iznad prosjeka, što je prilično ekstremna vrijednost.\n\n> Z-scores su poput zajedničkog jezika za različite varijable. Svaki put kad pretvorite podatke u z-scores, omogućujete usporedbu jabuka i naranči.\n\nPogledajmo kako z-scores izgledaju kad ih izračunamo unutar svake dobne skupine (što je ponekad smislenije nego ukupni z-score).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  group_by(age_group) |>\n  mutate(\n    z_unutar_grupe = as.numeric(scale(daily_minutes))\n  ) |>\n  ungroup() |>\n  select(respondent_id, age_group, daily_minutes, z_unutar_grupe) |>\n  head(12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n   respondent_id age_group daily_minutes z_unutar_grupe\n           <dbl> <chr>             <dbl>          <dbl>\n 1             1 18-24                95        -0.531 \n 2             2 18-24                78        -1.52  \n 3             3 18-24               112         0.463 \n 4             4 25-34                45        -0.972 \n 5             5 25-34                62         1.21  \n 6             6 35-44                22        -0.114 \n 7             7 18-24               130         1.52  \n 8             8 18-24                88        -0.940 \n 9             9 25-34                55         0.314 \n10            10 35-44                18        -1.60  \n11            11 18-24               105         0.0539\n12            12 18-24                72        -1.88  \n```\n\n\n:::\n:::\n\n\nSada z-score govori koliko se osoba razlikuje od prosjeka **svoje vlastite dobne skupine**, što je ponekad informativnije od ukupnog z-scorea. Na primjer, osoba od 19 godina koja koristi TikTok 95 minuta dnevno možda ima negativan z-score unutar skupine 18 do 24 (jer je ispod prosjeka te skupine), ali bi imala pozitivan z-score u ukupnom uzorku. Kontekst je važan.\n\n---\n\n## Korelacije {#sec-korelacije}\n\nDo sada smo opisivali jednu varijablu po jednu. Ali u istraživanjima nas često zanima **veza između dviju varijabli**. Postoji li povezanost između dobi ispitanika i vremena koje provode na TikToku? Jesu li ljudi koji više koriste platformu ujedno i oni koji joj više vjeruju?\n\n### Kovarijanca: temelj korelacije {#sec-kovarijanca}\n\nPrije nego uđemo u korelaciju, vrijedi razumjeti koncept koji stoji iza nje: **kovarijancu**. Kovarijanca mjeri u kojoj mjeri dvije varijable variraju zajedno. Ako su obje varijable iznadprosječne za istog ispitanika i ispodprosječne za istog ispitanika, one pozitivno kovariraju. Ako jedna tendira biti iznadprosječna kad je druga ispodprosječna, negativno kovariraju.\n\nFormula za kovarijancu je\n\n$$\n\\text{Cov}(X, Y) = \\frac{1}{N-1} \\sum_{i=1}^{N} (X_i - \\bar{X})(Y_i - \\bar{Y})\n$$\n\nPrimijetite sličnost s varijancom. Varijanca je zapravo kovarijanca varijable same sa sobom. Jedina razlika je da umjesto kvadriranja odstupanja jedne varijable, množimo odstupanja dviju različitih varijabli.\n\nProblem s kovarijancom je isti kao s varijancom: rezultat ovisi o mjernim jedinicama varijabli. Kovarijanca između dobi (u godinama) i korištenja TikToka (u minutama) bit će potpuno drugačija od kovarijance između dobi (u mjesecima) i korištenja TikToka (u satima), čak i ako je veza identična. Zato trebamo standardiziranu mjeru, a to je Pearsonov koeficijent korelacije.\n\n### Pearsonov koeficijent korelacije {#sec-pearson}\n\nNajčešća mjera linearne povezanosti dviju numeričkih varijabli je **Pearsonov koeficijent korelacije**, označen s $r$. To je zapravo standardizirana kovarijanca: kovarijancu podijelimo s produktom standardnih devijacija obiju varijabli.\n\n$$\nr_{XY} = \\frac{\\text{Cov}(X,Y)}{s_X \\cdot s_Y} = \\frac{1}{N-1} \\sum_{i=1}^{N} \\left( \\frac{X_i - \\bar{X}}{s_X} \\right) \\left( \\frac{Y_i - \\bar{Y}}{s_Y} \\right)\n$$\n\nAko prepoznajete z-scores u ovoj formuli, u pravu ste. Korelacija je zapravo prosjek umnožaka z-scores dviju varijabli. To je elegantna definicija jer pokazuje da korelacija zapravo mjeri u kojoj mjeri dvije varijable variraju zajedno, nakon što smo obje stavili na istu skalu.\n\nVrijednost korelacije kreće se od minus 1 do plus 1. Korelacija blizu plus 1 znači snažnu pozitivnu linearnu vezu (kad jedna varijabla raste, raste i druga). Korelacija blizu minus 1 znači snažnu negativnu linearnu vezu (kad jedna raste, druga pada). Korelacija blizu 0 znači da linearna veza ne postoji ili je vrlo slaba.\n\nIzračunajmo korelaciju između dobi i dnevnog korištenja.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    kovarijanca = cov(age, daily_minutes),\n    korelacija = cor(age, daily_minutes)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  kovarijanca korelacija\n        <dbl>      <dbl>\n1       -380.     -0.925\n```\n\n\n:::\n:::\n\n\nKorelacija je snažno negativna, što znači da stariji ispitanici koriste TikTok manje. Kovarijanca je negativna i velika, ali njezina apsolutna vrijednost nam ne govori ništa korisno bez konteksta jer ovisi o mjernim jedinicama. Korelacija od minus 0.9 (ili koliko god iznosi) odmah nam govori da je veza snažna.\n\n### Interpretacija korelacija {#sec-interpretacija-korelacija}\n\nJedna od najčešćih pitanja je koliko velika mora biti korelacija da bismo je smatrali značajnom ili važnom. Cohen (1988) je predložio sljedeće smjernice koje se još uvijek široko koriste.\n\nZa korelacije oko $|r| = 0.10$ kažemo da je veza **slaba** (small). Za korelacije oko $|r| = 0.30$ kažemo da je **umjerena** (medium). Za korelacije oko $|r| = 0.50$ ili više kažemo da je **snažna** (large).\n\nNo, Navarro s pravom upozorava da su ove smjernice samo grubi orijentiri i da ovise o kontekstu. U nekim područjima (na primjer, u predviđanju ponašanja) korelacija od 0.30 je zapravo prilično impresivna. U drugim (na primjer, u procjeni pouzdanosti testa) korelacija od 0.50 može biti nedovoljna. Kontekst je uvijek ključan.\n\nPogledajmo više korelacija odjednom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    r_dob_minute = cor(age, daily_minutes),\n    r_minute_trust = cor(daily_minutes, trust_score),\n    r_minute_videos = cor(daily_minutes, weekly_videos_watched),\n    r_dob_trust = cor(age, trust_score),\n    r_likes_comments = cor(likes_given, comments_posted)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  r_dob_minute r_minute_trust r_minute_videos r_dob_trust r_likes_comments\n         <dbl>          <dbl>           <dbl>       <dbl>            <dbl>\n1       -0.925          0.988           0.998      -0.935            0.965\n```\n\n\n:::\n:::\n\n\nKorelacija između dnevnog korištenja i povjerenja u sadržaj je pozitivna i prilično snažna. Ljudi koji više koriste TikTok ujedno iskazuju veće povjerenje u sadržaj koji tamo pronalaze. Korelacija između minuta i broja pogledanih videozapisa je gotovo savršena, što je logično jer su to dvije strane iste medalje. Korelacija između lajkova i komentara je umjereno pozitivna, što sugerira da aktivniji korisnici tendiraju biti aktivni na više načina.\n\n### Matrica korelacija {#sec-matrica-korelacija}\n\nKad imamo više numeričkih varijabli, korisno je izračunati korelacije između svih parova odjednom. To daje **matricu korelacija**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  select(age, daily_minutes, weekly_videos_watched, likes_given, \n         comments_posted, follows_creators, trust_score) |>\n  cor() |>\n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        age daily_minutes weekly_videos_watched likes_given\nage                    1.00         -0.92                 -0.90       -0.86\ndaily_minutes         -0.92          1.00                  1.00        0.98\nweekly_videos_watched -0.90          1.00                  1.00        0.99\nlikes_given           -0.86          0.98                  0.99        1.00\ncomments_posted       -0.77          0.93                  0.94        0.97\nfollows_creators      -0.87          0.98                  0.99        0.99\ntrust_score           -0.93          0.99                  0.98        0.96\n                      comments_posted follows_creators trust_score\nage                             -0.77            -0.87       -0.93\ndaily_minutes                    0.93             0.98        0.99\nweekly_videos_watched            0.94             0.99        0.98\nlikes_given                      0.97             0.99        0.96\ncomments_posted                  1.00             0.98        0.91\nfollows_creators                 0.98             1.00        0.97\ntrust_score                      0.91             0.97        1.00\n```\n\n\n:::\n:::\n\n\nMatrica korelacija je simetrična (korelacija između X i Y je jednaka korelaciji između Y i X) i na dijagonali su uvijek jedinice (svaka varijabla je savršeno korelirana sama sa sobom). Ovo su svojstva koja slijede direktno iz matematičke definicije korelacije.\n\n### Spearmanov koeficijent korelacije {#sec-spearman}\n\nPearsonov koeficijent mjeri linearnu vezu. Ali što ako veza između varijabli postoji, ali nije linearna? Na primjer, možda korištenje TikToka i povjerenje u sadržaj rastu zajedno, ali ne linearno nego u obliku krivulje. U tom slučaju Pearsonov r može podcijeniti snagu veze.\n\nZa takve situacije postoji **Spearmanov koeficijent korelacije** ($\\rho$ ili $r_s$). Spearmanova korelacija funkcionira tako da najprije pretvori podatke u rangove, a zatim izračuna Pearsonov koeficijent na rangovima. Budući da rangovi čuvaju redoslijed ali ne i udaljenosti, Spearmanova korelacija mjeri **monotonost** veze: koliko dosljedno jedna varijabla raste kad druga raste (ili pada), neovisno o tome je li veza linearna.\n\nU R u, Spearmanova korelacija se računa jednostavno dodavanjem argumenta `method = \"spearman\"` u funkciju `cor()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    pearson = cor(age, daily_minutes, method = \"pearson\"),\n    spearman = cor(age, daily_minutes, method = \"spearman\")\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  pearson spearman\n    <dbl>    <dbl>\n1  -0.925   -0.972\n```\n\n\n:::\n:::\n\n\nKad su Pearsonov i Spearmanov koeficijent slični, to sugerira da je veza približno linearna. Kad se razlikuju (osobito kad je Spearmanov veći od Pearsonovog), to sugerira da postoji monotona, ali nelinearna veza.\n\nSpearmanova korelacija ima i dodatnu prednost: manje je osjetljiva na ekstremne vrijednosti nego Pearsonova, jer radi s rangovima, a ne izvornim vrijednostima. Zato se ponekad koristi kao robusna alternativa Pearsonovom koeficijentu.\n\n::: {.callout-tip}\n## Praktični savjet\n\nKad radite s podacima za koje sumnjate da imaju nelinearnu vezu ili ekstremne vrijednosti, izračunajte i Pearsonov i Spearmanov koeficijent. Ako su slični, veza je vjerojatno linearna i bez problematičnih outliera. Ako se razlikuju, istražite dalje (najčešće pomoću scatterplota, o čemu ćemo govoriti sljedećeg tjedna).\n:::\n\n### Ograničenja korelacije {#sec-ogranicenja-korelacije}\n\nKorelacija je izuzetno korisna mjera, ali ima nekoliko važnih ograničenja koja morate poznavati. Navarro im u knjizi posvećuje značajan prostor, i to s dobrim razlogom.\n\n**Korelacija mjeri samo linearnu vezu.** Ako je veza između dviju varijabli zakrivljena (na primjer, performanse rastu s vježbom ali se onda stabiliziraju), Pearsonov r može biti nizak čak i kad je veza vrlo snažna. Čak i Spearmanov koeficijent zahtijeva monotonost. Ako je veza U-oblik (na primjer, zadovoljstvo je nisko i pri vrlo niskom i pri vrlo visokom radnom opterećenju), ni jedna korelacija neće to uhvatiti.\n\n**Korelacija nije uzročnost.** Ovo je toliko važno da zaslužuje poseban odlomak. Činjenica da je korištenje TikToka korelirano s povjerenjem u sadržaj ne znači da korištenje TikToka uzrokuje veće povjerenje (niti obratno). Moguće je da treća varijabla, poput dobi, objašnjava obje pojave. Mladi ljudi i više koriste TikTok i općenito imaju drugačiji odnos prema digitalnim medijima. Ovo je toliko čest problem da ima i ime: **confounding** (zbunjivanje) varijabli.\n\nNavarro koristi sjajan primjer: broj utopljavanja koreliran je s prodajom sladoleda. To ne znači da sladoled uzrokuje utapljanje. Treća varijabla (vrućina) objašnjava oboje: kad je vruće, ljudi i kupuju sladoled i idu plivati, a plivanje povećava rizik od utapljanja.\n\n**Ekstremne vrijednosti mogu drastično utjecati na korelaciju.** Jedna ili dvije ekstremne točke mogu stvoriti iluziju korelacije tamo gdje je zapravo nema, ili maskirati korelaciju koja zapravo postoji.\n\n**Ograničeni raspon smanjuje korelaciju.** Ako vaš uzorak pokriva samo uzak raspon jedne varijable, korelacija će biti niža nego u populaciji. Na primjer, ako istražujete vezu između IQ-a i akademskog uspjeha, ali vaš uzorak uključuje samo studente na elitnom sveučilištu (gdje svi imaju visok IQ), korelacija će biti niska jer nema dovoljno varijabilnosti u IQ-u.\n\n::: {.callout-important}\n## Važna napomena\n\nKad god izračunate korelaciju, obavezno napravite i scatterplot. Postoje poznati primjeri (poput Anscombeovog kvarteta, a u novije vrijeme i Datasaurus Dozen) u kojima potpuno različiti skupovi podataka imaju identičnu korelaciju, a vizualno su potpuno različiti. Grafiku ćemo detaljno raditi sljedeći tjedan, ali zapamtite ovo pravilo od sada. Brojke bez grafike mogu lako zavarati.\n:::\n\n---\n\n## Rad s nedostajućim vrijednostima {#sec-nedostajuce-vrijednosti}\n\nU stvarnom svijetu podaci gotovo nikad nisu potpuni. Ispitanici preskoče pitanje u anketi, senzor prestane raditi, sustav ne zabilježi klik. R koristi oznaku `NA` (not available) za nedostajuće vrijednosti, i ove vrijednosti zahtijevaju posebnu pažnju.\n\n### Kako R tretira nedostajuće vrijednosti\n\nProblem je u tome što većina R funkcija za deskriptivnu statistiku vraća `NA` ako u podacima postoji ijedna nedostajuća vrijednost.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimjer <- c(10, 20, NA, 40, 50)\n\n# Ovo vraća NA\nmean(primjer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\n# Ovo ignorira NA i računa prosjek od preostalih vrijednosti\nmean(primjer, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30\n```\n\n\n:::\n:::\n\n\nTo je zapravo dobro ponašanje jer vas prisiljava da svjesno odlučite što ćete učiniti s nedostajućim podacima. Ali u praksi, najčešće rješenje je dodati argument `na.rm = TRUE` koji govori R u da ignorira nedostajuće vrijednosti.\n\nUnutar tidyverse pipeline, `na.rm = TRUE` se stavlja unutar svake funkcije u `summarise()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(\n    prosjek = mean(daily_minutes, na.rm = TRUE),\n    sd = sd(daily_minutes, na.rm = TRUE),\n    medijan = median(daily_minutes, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  prosjek    sd medijan\n    <dbl> <dbl>   <dbl>\n1    56.9  38.6      50\n```\n\n\n:::\n:::\n\n\n### Tipovi nedostajućih vrijednosti\n\nNavarro u knjizi ne ulazi duboko u ovu temu, ali za komunikologe je korisno poznavati osnove. Postoje tri tipa nedostajućih vrijednosti.\n\n**MCAR (Missing Completely at Random)** znači da je nedostajanje potpuno nasumično, nepovezano ni s jednom varijablom u podacima. Na primjer, ispitanik je slučajno preskočio pitanje jer mu je kliznuo prst na touchscreenu. U tom slučaju, ignoriranje nedostajućih vrijednosti (`na.rm = TRUE`) ne uvodi nikakvu pristranost.\n\n**MAR (Missing at Random)** znači da je nedostajanje povezano s drugim varijablama u podacima, ali ne s nedostajućom vrijednošću samom. Na primjer, stariji ispitanici češće preskaču pitanja o TikToku jer smatraju da se to na njih ne odnosi. Nedostajanje je povezano s dobi, ali ne izravno s korištenjem TikToka. U tom slučaju, ignoriranje nedostajućih vrijednosti može uvesti pristranost, ali postoje statističke metode za korekciju.\n\n**MNAR (Missing Not at Random)** znači da je nedostajanje izravno povezano s vrijednošću koja nedostaje. Na primjer, ljudi koji provode izrazito mnogo vremena na TikToku možda preskaču to pitanje jer ih je sram priznati koliko vremena tamo provode. Ovo je najproblematičniji slučaj jer ga je teško detektirati i ispraviti.\n\nZa uvodni kolegij, dovoljno je biti svjestan da nedostajuće vrijednosti nisu uvijek nasumične. Kad god imate nedostajuće podatke, razmislite zašto nedostaju i je li sigurno jednostavno ih ignorirati.\n\n### Provjera nedostajućih vrijednosti\n\nPrije bilo kakve analize uvijek provjerite koliko nedostajućih vrijednosti imate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  summarise(across(everything(), ~sum(is.na(.x)))) |>\n  pivot_longer(everything(), names_to = \"varijabla\", values_to = \"broj_NA\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 2\n   varijabla             broj_NA\n   <chr>                   <int>\n 1 respondent_id               0\n 2 age                         0\n 3 age_group                   0\n 4 gender                      0\n 5 daily_minutes               0\n 6 weekly_videos_watched       0\n 7 likes_given                 0\n 8 comments_posted             0\n 9 follows_creators            0\n10 trust_score                 0\n11 education                   0\n```\n\n\n:::\n:::\n\n\nU našem datasetu nema nedostajućih vrijednosti jer su podaci simulirani. Ali u stvarnom radu ih gotovo sigurno hoćete imati. Navikavanje na `na.rm = TRUE` od početka će vam uštedjeti mnogo frustracije.\n\n::: {.callout-tip}\n## Praktični savjet\n\nAko neka varijabla ima velik postotak nedostajućih vrijednosti (recimo više od 20%), razmislite treba li uopće koristiti tu varijablu u analizi. Također, umjesto `na.rm = TRUE`, ponekad je bolje koristiti `tidyr::drop_na()` na početku analize kako biste radili s kompletnim opažanjima. Razlika je u tome što `na.rm = TRUE` radi po varijabli (svaka statistika koristi sva dostupna opažanja), dok `drop_na()` eliminira cijele retke koji imaju bilo koju nedostajuću vrijednost. Koja opcija je bolja ovisi o konkretnoj situaciji.\n:::\n\n---\n\n## Sve zajedno: kompletna deskriptivna analiza {#sec-kompletna-analiza}\n\nDa bismo zaokružili ovo predavanje, napravimo kompletnu deskriptivnu analizu našeg dataseta o korištenju TikToka. Ovo je obrazac koji ćete koristiti na početku gotovo svake analize: učitajte podatke, pogledajte strukturu, izračunajte deskriptivne statistike ukupno i po grupama, provjerite korelacije.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  group_by(age_group) |>\n  summarise(\n    n = n(),\n    prosjek_min = round(mean(daily_minutes), 1),\n    sd_min = round(sd(daily_minutes), 1),\n    medijan_min = median(daily_minutes),\n    prosjek_trust = round(mean(trust_score), 1),\n    sd_trust = round(sd(trust_score), 1),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  age_group     n prosjek_min sd_min medijan_min prosjek_trust sd_trust\n  <chr>     <int>       <dbl>  <dbl>       <dbl>         <dbl>    <dbl>\n1 18-24       102       104.    17.1       104             6.7      0.8\n2 25-34        86        52.6    7.8        52.5           4.5      0.5\n3 35-44        62        22.3    2.7        22             3        0  \n4 45+          50        10.7    2.2        11             2        0  \n```\n\n\n:::\n:::\n\n\nOva tablica u šest redova sažima informacije koje bi vam inače trebale stranice i stranice sirovih podataka. Vidimo jasne obrasce. Mladi (18 do 24) koriste TikTok oko 100 minuta dnevno s umjerenom varijabilnošću. Srednja skupina (25 do 34) koristi ga upola manje. Starije skupine jedva ga koriste, ali su unutar tih skupina ispitanici prilično ujednačeni (mala standardna devijacija). Povjerenje u sadržaj prati isti obrazac jer je snažno korelirano s intenzitetom korištenja.\n\nDopunimo ovu tablicu korelacijama unutar svake skupine.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiktok |>\n  group_by(age_group) |>\n  summarise(\n    n = n(),\n    r_minute_trust = round(cor(daily_minutes, trust_score), 2),\n    r_minute_videos = round(cor(daily_minutes, weekly_videos_watched), 2),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  age_group     n r_minute_trust r_minute_videos\n  <chr>     <int>          <dbl>           <dbl>\n1 18-24       102           0.94            1   \n2 25-34        86           0.86            1   \n3 35-44        62          NA               0.99\n4 45+          50          NA               0.99\n```\n\n\n:::\n:::\n\n\nOvaj korak je važan jer korelacije mogu biti različite u podskupovima nego u ukupnom uzorku. Na primjer, ukupna korelacija između korištenja i povjerenja može biti visoka dijelom zato što obje varijable koreliraju s dobi (mlađi koriste više i imaju veće povjerenje). Korelacija unutar svake dobne skupine govori nam postoji li veza i nakon što smo kontrolirali za dob. Ovo je uvod u koncept kontrole varijabli koji ćemo detaljno obraditi kad budemo radili regresiju.\n\n---\n\n::: {.callout-important}\n## Ključni zaključci\n\n1. Deskriptivna statistika sažima podatke u manji broj smislenih brojki, ali svako sažimanje znači i gubitak informacija.\n\n2. Mjere centralne tendencije (sredina, skraćena sredina, medijan, mod) odgovaraju na pitanje gdje se podaci nalaze. Svaka ima svoja svojstva: sredina koristi sve podatke ali je osjetljiva na outliere, medijan je robustan ali ignorira većinu podataka, skraćena sredina je kompromis.\n\n3. Mjere varijabilnosti (raspon, AAD, varijanca, SD, IQR) odgovaraju na pitanje koliko su podaci raspršeni. Varijanca dijeli s $N-1$ umjesto $N$ (Besselova korekcija) kako bi bila nepristrana procjena populacijske varijance.\n\n4. Asimetrija i zaobljenost opisuju oblik distribucije. Medijske metrike gotovo uvijek imaju pozitivnu asimetriju (dugačak rep prema desno).\n\n5. Z-scores standardiziraju varijable na zajedničku skalu (sredina 0, SD 1) i omogućuju usporedbu varijabli s različitim mjernim jedinicama.\n\n6. Kombinacija `group_by()` i `summarise()` je temeljni alat za izračunavanje deskriptivnih statistika po grupama u R u.\n\n7. Pearsonov koeficijent korelacije mjeri linearnu povezanost, a Spearmanov mjeri monotonu povezanost. Korelacija nije uzročnost i mjeri samo specifičan tip veze.\n\n8. Nedostajuće vrijednosti (`NA`) zahtijevaju svjesnu odluku o tome kako ih tretirati. Različiti tipovi nedostajanja (MCAR, MAR, MNAR) impliciraju različite posljedice za analizu.\n\n9. Uvijek kombinirajte numeričke statistike s vizualizacijom. Brojke bez grafike mogu zavarati (Anscombeov kvartet).\n:::\n\n---\n\n::: {.callout-warning}\n## Priprema za sljedeći tjedan\n\nSljedeći tjedan bavimo se **vizualizacijom podataka s ggplot2**. To je prirodni nastavak ovog predavanja jer ćemo naučiti kako sve statistike koje smo danas izračunali prikazati grafički. Histogrami, boxplotovi, scatterplotovi i bar chartovi su alati koji daju život brojkama.\n\nZa pripremu napravite sljedeće:\n\n1. Ponovite današnje R primjere i eksperimentirajte s njima. Promijenite varijable u `summarise()` pozivu i pogledajte što se događa.\n2. Razmislite o tome koje bi grafičke prikaze htjeli vidjeti za naše TikTok podatke. Histogram dnevnog korištenja? Boxplot po dobnim skupinama? Scatterplot dobi i korištenja?\n3. Pročitajte poglavlje 3 iz knjige Kieran Healy, *Data Visualization* (besplatno dostupno online).\n4. Instalirajte paket `patchwork` ako ga nemate: `install.packages(\"patchwork\")`. Koristit ćemo ga za kombiniranje grafika.\n:::\n\n---\n\n## Dodatno čitanje\n\n**Obavezno**\n\nNavarro, D. (2018). *Learning Statistics with R*, Chapter 5: Descriptive Statistics. Besplatno dostupno na [learningstatisticswithr.com](https://learningstatisticswithr.com/lsr-0.6.pdf). Poglavlje pokriva iste teme kao ovo predavanje, uključujući trimmed mean, kovarijancu i Spearmanovu korelaciju, ali s primjerima iz psihologije i u base R sintaksi.\n\n**Preporučeno**\n\nWickham, H. & Grolemund, G. (2023). *R for Data Science* (2nd edition), Chapters 3 i 4. Besplatno dostupno na [r4ds.hadley.nz](https://r4ds.hadley.nz). Odlično pokrivanje tidyverse pristupa manipulaciji i sažimanju podataka.\n\nHealy, K. (2018). *Data Visualization: A Practical Introduction*. Besplatno dostupno na [socviz.co](https://socviz.co). Poglavlje 1 daje izvrsnu motivaciju zašto je vizualizacija neodvojiva od deskriptivne statistike.\n\nCohen, J. (1988). *Statistical Power Analysis for the Behavioral Sciences* (2nd edition). Klasična referenca za interpretaciju veličine efekata, uključujući smjernice za korelacije.\n\n---\n\n## Pojmovnik\n\n| Pojam | Objašnjenje |\n|---|---|\n| Aritmetička sredina (mean) | Zbroj svih vrijednosti podijeljen s brojem opažanja. Koristi sve podatke ali je osjetljiva na ekstremne vrijednosti. |\n| Skraćena sredina (trimmed mean) | Aritmetička sredina izračunata nakon uklanjanja određenog postotka najmanjih i najvećih vrijednosti. Kompromis između sredine i medijana. |\n| Medijan (median) | Srednja vrijednost kad se podaci poredaju po veličini. Robusna mjera centralne tendencije jer ne ovisi o ekstremnim vrijednostima. |\n| Mod (mode) | Vrijednost koja se najčešće pojavljuje. Jedina smislena mjera centralne tendencije za kategoričke podatke. |\n| Raspon (range) | Razlika između najveće i najmanje vrijednosti u podacima. Jednostavna ali nerobusna mjera varijabilnosti. |\n| Prosječno apsolutno odstupanje (AAD) | Prosjek apsolutnih razlika svake vrijednosti od sredine. Intuitivnija ali matematički manje pogodna od varijance. |\n| Varijanca (variance) | Prosječno kvadrirano odstupanje od aritmetičke sredine (s $N-1$ u nazivniku). Mjeri raspršenost podataka. |\n| Standardna devijacija (SD) | Korijen iz varijance. Izražena u istim mjernim jedinicama kao izvorni podaci. |\n| Besselova korekcija | Dijeljenje s $N-1$ umjesto $N$ pri izračunu varijance uzorka, kako bi procjena populacijske varijance bila nepristrana. |\n| Interkvartilni raspon (IQR) | Razlika između 75. i 25. percentila. Raspon unutar kojeg se nalaze srednjih 50% podataka. Robusna mjera varijabilnosti. |\n| Percentil | Vrijednost ispod koje se nalazi određeni postotak podataka. 50. percentil je medijan. |\n| Asimetrija (skewness) | Mjera simetrije distribucije. Pozitivna asimetrija znači dugačak rep prema desno, negativna prema lijevo. |\n| Zaobljenost (kurtosis) | Mjera težine repova distribucije u usporedbi s normalnom distribucijom. |\n| Standardni rezultat (z-score) | Broj standardnih devijacija za koji se neka vrijednost razlikuje od aritmetičke sredine. Omogućuje usporedbu varijabli na različitim skalama. |\n| Kovarijanca (covariance) | Mjera zajedničkog variranja dviju varijabli. Ovisi o mjernim jedinicama, pa se koristi korelacija kao standardizirana verzija. |\n| Pearsonov koeficijent korelacije ($r$) | Standardizirana kovarijanca. Mjera linearne povezanosti dviju numeričkih varijabli. Kreće se od minus 1 do plus 1. |\n| Spearmanov koeficijent korelacije ($r_s$) | Pearsonov koeficijent izračunat na rangovima. Mjeri monotonost veze i robusniji je od Pearsonovog koeficijenta. |\n| MCAR, MAR, MNAR | Tri tipa nedostajućih vrijednosti: potpuno nasumično, nasumično uvjetovano drugim varijablama, te sustavno povezano s nedostajućom vrijednošću. |\n",
    "supporting": [
      "week-04_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}